### ISSUE TITLE
Please provide an AppImage for download

### ISSUE THREAD

**Issue by probonopd** [kanasimi/work_crawler#10]
https://github.com/kanasimi/work_crawler/blob/2990a8d95eb25a214b298896e76c83094e54855a/package.json#L33

Please provide an AppImage for download on the project's GitHub Releases page.

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by kanasimi** [comment]
Thanks for your suggestion. I might provide an AppImage, but it will take some time to implement the features.

**Comment by probonopd** [comment]
Actually I think electron-builder can "just do" it...

**Comment by probonopd** [comment]
This was closed, why? Is it available for download now?

**Comment by kanasimi** [comment]
Thank you for your attention. I try to create an executable package but it seems still some problems. Please wait a while...

**Comment by probonopd** [comment]
Please let me know if I can help. Which issues are you running into?

**Comment by kanasimi** [comment]
I try to make an executable package. It seems OK on .exe, but it is sad that I don't have a linux environment. May you please help me to check if the linux executable or not? Thank you!

**Comment by probonopd** [comment]
Yes I can test, is it available for download? Thanks.

**Comment by kanasimi** [comment]
I plase it on https://github.com/kanasimi/work_crawler/releases.

**Comment by probonopd** [comment]
`work_crawler` seems to be a ELF 32-bit LSB executable. Can you upload a 64-bit one please? Thanks.

**Comment by kanasimi** [comment]
OK, I have uploaded a x64 version. And it is strange that after I running <code>electron-builder -wl</code>, the .exe file lies outside of the win-unpacked directory, but the linux file is inside the linux-unpacked directory. Is it normal for an AppImage?

**Comment by probonopd** [comment]
Normally you should get a file with ".AppImage" at the end of the filename. Not sure what is going on here.

**Comment by kanasimi** [comment]
Follow the instructions on https://www.electron.build/configuration/linux#appimageoptions , I set "executableName" : "work_crawler-linux.AppImage" and get a AppImage file. May you help me to test it? Thank you.

**Comment by probonopd** [comment]
Looks like you have renamed the Linux executable to "AppImage" but this is not an AppImage. I am not an `electron-builder` expert but I think the AppImage should be generated in the same location where the `deb` is also generated.

**Comment by kanasimi** [comment]
So it is a deb file. But when I specify "AppImage" only, it's still the same file. Do you know any projects using electron-builder to generate AppImage?

**Comment by probonopd** [comment]
Possibly a bug? cc @develar

**Comment by kanasimi** [comment]
By the way, I use Windows 7 to run:
```
> node_modules\.bin\electron-builder --linux --x64
electron-builder 19.49.3
No native production dependencies
Packaging for linux x64 using electron 1.8.1 to build\linux-unpacked
Schedule remote appImage build for arch x64
>
```
and no file lies outside build\linux-unpacked.

**Comment by probonopd** [comment]
Ah, you are using a Windows machine to do the builds? I am not 100% sure whether this can do AppImages. I know that macOS can do, but I am not sure about Windows. (If it can't, I'd expect an error message though...)

**Comment by develar** [comment]
electron-builder provides cloud service to build AppImage on Windows. It is in testing phase. It seems due to some bug cloud service doesn't build AppImage for you.

**Comment by kanasimi** [comment]
Well, I borrow a linux machine and find that electron-builder just works. It seems `electron-builder --linux` won't work on Windows.

@develar By the way, I try to specify a png file as icon, but it do not shown as expected. Are there any other things I need to be aware of?

**Comment by develar** [comment]
@kanasimi https://github.com/electron-userland/electron-builder/issues/748 https://github.com/electron-userland/electron-builder/issues/2269#issuecomment-342168989

**Comment by kanasimi** [comment]
@develar Thank you! But even I set `new BrowserWindow({icon:...})` and run under command line, the icon is still a blue "?" sign. Perhaps I should try another method...
