### ISSUE TITLE
仍舊是7zip問題

### ISSUE THREAD

**Issue by Ecauchy** [kanasimi/work_crawler#101]
﻿

* **Version**: 最新懶人版
* **Interface**: 命令行

![image](https://user-images.githubusercontent.com/7821408/46914462-997c2f80-cfd0-11e8-9466-633f45958284.png)

**Comment by Ecauchy** [comment]
P.S.如果7zip出錯，fall back可不可以設置成「不要壓縮直接存檔」啊？也好過一無所有……

**Comment by kanasimi** [comment]
出這個訊息主要是提醒無法正常壓縮
但是圖片檔案應該還在
