### ISSUE TITLE
安装了7-zip，但还是不能压缩漫画

### ISSUE THREAD

**Issue by MUTI-Thread** [kanasimi/work_crawler#102]
Error @CeL: 0 [Error] (facility code 0): Command failed: "%ProgramFiles%\7-Zip\7z.exe" a -sccUTF-8 -scsUTF-8 -tzip -mx=9 -r -sdel -- "D:/Users/JY/Downloads/gufengmh/yuzhouxiongdi 宇宙兄弟/0001 《#1》弟弟日日人与哥哥六太.zip" "D:/Users/JY/Downloads/gufengmh/yuzhouxiongdi 宇宙兄弟/0001 《#1》弟弟日日人与哥哥六太/"

**Comment by kanasimi** [comment]
本工具最新版本會嘗試取得7-Zip的執行路徑
可能是這個部分失敗了

請提供下列訊息以幫助我們解決問題
謝謝

* **Version**: 
* **Interface**: 
* 7-Zip的執行檔路徑 例如 "D:\Program Files\7-Zip\7z.exe"

您可貼上錯誤訊息或者執行時的畫面

**Comment by MUTI-Thread** [comment]
version：安装包
interface：图形界面
路径：D:\Program Files\7-Zip\7z.exe

**Comment by kanasimi** [comment]
下一版本的安裝包將會納入這個功能
您可以先嘗試懶人安裝法
