### ISSUE TITLE
出現 .txt 黃字是否有影響

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#106]
先前我還不知如何操作下載mrblue
我自己亂測試
<img width="369" alt="default" src="https://user-images.githubusercontent.com/42042168/47616225-ea257980-daf4-11e8-820e-1109e1cf697d.PNG">
來到這步驟時
我忘記我打了甚麼
結果跑出
733mh.txt	
9mdm.txt
comico.txt	
dajiaochong.txt	
dm5.txt
dmzj.txt
dongman.txt	
gufengmh.txt	
hhcool.txt
(類似這樣的黃字,一行一行的跑,在命令行介面)
我現在想不起來如何還原當時情況

我想請問這應該不會影響甚麼吧
像是程式
或是放漫畫的資料夾

**Comment by gfhghfghfh** [comment]
抱歉講的很含糊
希望您能幫我想想

**Comment by kanasimi** [comment]
您應該是執行了 comic.cmn-Hans-CN.bat
這個沒有影響

**Comment by gfhghfghfh** [comment]
那可以請問
這代表我做了什麼
執行了什麼

**Comment by kanasimi** [comment]
This is a batch file to show how to execute every crawler in one click. You must setup .txt title list file first.
