### ISSUE TITLE
由於環境原因，我電腦需要設置代理IP才能訪問網站，比如說：漫畫台

### ISSUE THREAD

**Issue by irsunshine** [kanasimi/work_crawler#107]
最新 master 版本，能否增加選項，設置代理IP，用於下載漫畫
或者指點下，如何修改 CeJS 中的文件也行，我懂 C++ 程序開發，對於 javascript 不是很懂

**Comment by kanasimi** [comment]
related: #74

**Comment by kanasimi** [comment]
e.g., `node 23us "斗罗大陆Ⅲ龙王传说" proxy=localhost:8080`
