### ISSUE TITLE
Mrblue用id 下載問題

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#110]
http://www.mrblue.com/webtoon/wt_startbaby_wzz

下載一集就結束了

**Comment by gfhghfghfh** [comment]
http://www.mrblue.com/webtoon/wt_carpediem_E
無法下載

**Comment by kanasimi** [comment]
wt_startbaby_wzz:
不存在這個檔:
http://comics.mrblue.com/MrBlueComicsData_04/webtoon/wt_startbaby_wzz/1/001.jpg
因此不能下載
未來沒有打算要解析這個網站

wt_carpediem_E:
這邊下載正常
沒有遇到您所提到的問題
