### ISSUE TITLE
cookie中包含 uin和skey就可以下載到收費漫畫 是甚麼意思

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#111]
cookie中包含 uin和skey就可以下載到收費漫畫

請問是甚麼意思

**Comment by kanasimi** [comment]
據 https://github.com/abcfy2/getComic/issues/20
有VIP帳號的時候
網站用這兩個值來判別是否為VIP
可惜這邊沒有VIP帳戶
因此也無法做測試

**Comment by gfhghfghfh** [comment]
可以順便問下畫質問題嗎
如果有1100px
是會取1100px
沒錯吧

**Comment by kanasimi** [comment]
本工具會取得能夠獲得的最高畫質
