### ISSUE TITLE
請求增加MRBLUE 的만화

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#116]
http://www.mrblue.com/comic/genre/all

http://comics.mrblue.com/MrBlueComicsData_01/daewon/dw_0818_2/2/001.jpg
http://comics.mrblue.com/MrBlueComicsData_01/gtplan/gt_0079/1/004.jpg
http://comics.mrblue.com/MrBlueComicsData_01/daewon/dw_1160/1/004.jpg
http://comics.mrblue.com/MrBlueComicsData_01/daewon/dw_1161/1/001.jpg
http://comics.mrblue.com/MrBlueComicsData_02/haksan/swtguy_w/1/001.jpg
http://comics.mrblue.com/MrBlueComicsData_02/haksan/haksan_0126/2/002.jpg
http://comics.mrblue.com/MrBlueComicsData_04/seoul/se_0134/1/001.jpg
http://comics.mrblue.com/MrBlueComicsData_04/wbeast/wbeast_0005/1/004.jpg
http://comics.mrblue.com/MrBlueComicsData_04/teruten_jp/HQ_0635_MG39_3/2/004.jpg
http://comics.mrblue.com/MrBlueComicsData_05/kocn/kocncm_0101/1/003.jpg
利用網址的方式
因為http://comics.mrblue.com/MrBlueComicsData  的後方似乎有三個不一樣的地方,應該是無法利用id

<img width="474" alt="default" src="https://user-images.githubusercontent.com/42042168/48340507-bb3b0600-e6a5-11e8-9148-b080ed9428c1.PNG">

**Comment by gfhghfghfh** [comment]
만화中含有非條漫的韓漫
上述的例子基本上都是

**Comment by gfhghfghfh** [comment]
希望您願意採納

**Comment by gfhghfghfh** [comment]
請問不能像之前做的那樣
只是多幾個變數
請問不可行嗎

**Comment by gfhghfghfh** [comment]
若有失言請見諒

**Comment by gfhghfghfh** [comment]
https://user-images.githubusercontent.com/42042168/48340507-bb3b0600-e6a5-11e8-9148-b080ed9428c1.PNG

**Comment by gfhghfghfh** [comment]
改動後三個

**Comment by kanasimi** [comment]
是的 這樣子的例外太多太繁雜了
本來所有的網站都應該要經過解析才下載
可惜這邊讀不懂韓文網站
對於例外的情況
只能麻煩您手動下載

**Comment by gfhghfghfh** [comment]
好的
謝謝您的閱讀
