### ISSUE TITLE
漫畫櫃 無法保存書籤 也無法保存下載偏好選項

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#118]
漫畫櫃   書籤無法保存下載選項偏好也無法保存

命令行介面的圖形介面

**Comment by gfhghfghfh** [comment]
用完程式
關閉後
重新開啟程式
書籤仍沒有

**Comment by kanasimi** [comment]
請問您指的是命令行見面或者圖形介面?

**Comment by gfhghfghfh** [comment]
用命令行介面開啟的圖形介面

**Comment by gfhghfghfh** [comment]
<img width="228" alt="default" src="https://user-images.githubusercontent.com/42042168/48667597-e940a000-eb14-11e8-8b4b-612fd791be93.PNG">
<img width="784" alt="1" src="https://user-images.githubusercontent.com/42042168/48667598-eba2fa00-eb14-11e8-9938-75e086be9712.PNG">

**Comment by gfhghfghfh** [comment]
下載完後再開啟
書籤沒保存
下載選項也回復成原來的

**Comment by gfhghfghfh** [comment]
抱歉
剛剛又可以了(但我昨天試了很多次

**Comment by gfhghfghfh** [comment]
當我尚未有在某個網站下載時
若我此時更動下載選項以及書籤
再次開啟仍回到原本
<img width="943" alt="default" src="https://user-images.githubusercontent.com/42042168/48667631-f27e3c80-eb15-11e8-90df-d96b7543958c.PNG">

**Comment by gfhghfghfh** [comment]
D:\work_crawler-master>node_modules\.bin\electron .   || C:\Users\abc\node_modules\.bin\electron .

用命令行開啟的圖形介面

**Comment by gfhghfghfh** [comment]
好像是要先有漫畫網站名稱的資料夾
才可以開始保存
