### ISSUE TITLE
可以添加动漫屋/极速漫画的支持吗？

### ISSUE THREAD

**Issue by mengmo** [kanasimi/work_crawler#12]
动漫屋 http://www.dm5.com/
极速漫画 http://www.1kkk.com/
据悉，这两个网站的网页`URL`格式不同，但是大部分漫画的内容应该都是一样的。

**Comment by kanasimi** [comment]
這個網站圖片似乎不能並行下載，下載速度較慢。
若是您還需要添加极速漫画，另外開一個主題，謝謝。

**Comment by mengmo** [comment]
http://www.dm5.com/manhua-moukexuedechaodiancipao/

目前还存在一些问题：
* 因为网站的章节的默认排序是`倒序`的，所以下载后的目录也是倒序排列的
* 下载后的文件扩展名全部都是`.undefined`
* 只能下载标示为`连载`下的章节内容，`卷`和`番外`的内容无法下载
* 由于章节量多，下载一定章节后触发了网站的保护策略，先是下载了一定量的警告图片，后边直接404了
* 目前也不支持按`id`进行下载，不过这 id `manhua-moukexuedechaodiancipao`也是与众不同啊
***
如果并不需要下载全本，可以单章节或选择章节下载是不是更好？
如果需要下载全本，`连载`、`卷`和`番外`下载到同一目录下应该不太好区分，考虑也分到不同目录下？或者可以按需下载`连载`还是`卷`或者`番外`？
***
另外，关于极速漫画
http://www.1kkk.com/manhua4246/
我能看到的，两个网站的`URL`格式完全不一样
除了目录页的`URL`格式不一样
动漫屋的章节`URL`格式一般都是这样的`http://www.dm5.com/m558687/`
而极速漫画的
> 连载`http://www.1kkk.com/ch99-558687/`
> 卷 `http://www.1kkk.com/vol11-538603/`
> 番外`http://www.1kkk.com/other429661/`
> 番外`http://www.1kkk.com/sp8-144849/`

也不太懂其他方面，但是这样会不会工作量太大？
***
刚在两个页面的网页源代码的发现了这些
```
var DM5_COMIC_TEMPLATE=2;        var DM5_COMIC_SORT=2;        var DM5_COMIC_MID=4246;        var DM5_COMIC_MNAME="某科学的超电磁炮";        var DM5_COMIC_URL="/manhua-moukexuedechaodiancipao/";        var DM5_USERID=0;        var COMIC_MID=4246;        var DM5_PAGETYPE = 4;        var DM5_PAGEINDEX = 1;        var DM5_PAGEPCOUNT = 235;        var DM5_POSTCOUNT=2346;        var DM5_LOADINGIMAGE='http://css99tel.cdndm5.com/v201801302028/dm5/images/loading.gif';
```
```
var DM5_COMIC_TEMPLATE=2;        var DM5_COMIC_SORT=2;        var DM5_COMIC_MID=4246;        var DM5_COMIC_MNAME="某科学的超电磁炮";        var DM5_COMIC_URL="/manhua4246/";        var DM5_USERID=0;        var COMIC_MID=4246;        var DM5_PAGETYPE = 4;        var DM5_PAGEINDEX = 1;        var DM5_PAGEPCOUNT = 235;        var DM5_POSTCOUNT=2346;        var DM5_LOADINGIMAGE='http://css99tel.cdndm5.com/v201801302028/blue/images/loading.gif';
```
这么看来`4246`就是/才是真正的`id`，而且动漫屋和极速漫画确实应该是一家了。
~~如果支持按`id`下载，还得翻`动漫屋`的网页源代码~~

**Comment by kanasimi** [comment]
謝謝您的測試。
上面的問題大部分已經解決了。

您若是需要下載特定的章節，可以使用 chapter_filter 這個參數。例如假如只想要下載"外传"的話，請執行
`node dm5.js 某科学的超电磁炮 chapter_filter=外传`

**Comment by kanasimi** [comment]
謝謝您的試用。
上面的問題已解決。不過 **您需要下載 _CeL.updater.node.js**。
