### ISSUE TITLE
动漫之家下载错误404

### ISSUE THREAD

**Issue by xiamuguizhi** [kanasimi/work_crawler#13]
https://manhua.dmzj.com/dblyloxdhjznqpav/53885.shtml#@page=1

动漫之家链接地址是：.shtml   而不是html 这是否是报错的原因?

**Comment by kanasimi** [comment]
@xiamuguizhi 能麻煩您貼一下錯誤訊息或者執行時的畫面嗎？這邊執行
`node dmzj.js 当不了一流偶像的话就只能去拍AV`
的結果是可以下載……

另外您或許需要更新到最新版？

**Comment by xiamuguizhi** [comment]
# 这是在windows客户端运行的  报错如下！

> 其他漫画网站平台下载漫画正确，唯独动漫之家下载错误提示！

![](https://ws1.sinaimg.cn/large/b07e5053gy1fp3yydjus3j20yj0kd40r.jpg)

[📝]dmzj: Starting dblyloxdhjznqpav, 儲存至 dmzj\
[📝]dblyloxdhjznqpav 当不了一流偶像的话就只能去拍AV: 4 話. 连载中
[⚠][30.598s] get_URL_node: [https://www.dmzj.com/view/dblyloxdhjznqpav/53885.html]: status 404
[📝]get_URL_node: Retry 1/4: BAD STATUS
[⚠][118.11] get_URL_node: [https://www.dmzj.com/view/dblyloxdhjznqpav/53885.html]: status 404
[📝]get_URL_node: Retry 2/4: BAD STATUS
[⚠][106.655] get_URL_node: [https://www.dmzj.com/view/dblyloxdhjznqpav/53885.html]: status 404
[📝]get_URL_node: Retry 3/4: BAD STATUS
[⚠][158.88] get_URL_node: [https://www.dmzj.com/view/dblyloxdhjznqpav/53885.html]: status 404
[📝]get_URL_node: Retry 4/4: BAD STATUS
[⚠][117.065] get_URL_node: [https://www.dmzj.com/view/dblyloxdhjznqpav/53885.html]: status 404
[☠][1.73] dmzj: Error on chapter url: https://www.dmzj.com/view/dblyloxdhjznqpav/53885.html

**Comment by kanasimi** [comment]
看起來需要包裝新版本才行

**Comment by kanasimi** [comment]
謝謝您的測試與愛用。
