### ISSUE TITLE
快看漫畫某些擋ip的漫畫如何下載

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#132]
https://www.kuaikanmanhua.com/web/topic/1815/

請問這個擋ip
要如何處理

**Comment by kanasimi** [comment]
您或許可以嘗試使用proxy
e.g., `node kuaikan "我亲爱的上线了" proxy=localhost:8080`

**Comment by gfhghfghfh** [comment]
那請問8080是指連到哪個國家嗎
抱歉因為我沒用過代理伺服器

**Comment by gfhghfghfh** [comment]
https://free-proxy-list.net/
請問是像裡面列的一樣嗎

**Comment by kanasimi** [comment]
8080是port(埠)
https://www.itread01.com/content/1541148783.html
不過若是自己在大陸沒有專用的代理伺服器大概會很慢吧

**Comment by gfhghfghfh** [comment]
可以請問您有任何國家proxy的資訊可以提供嗎（貌似很多地方沒擋ip

**Comment by gfhghfghfh** [comment]
還是說
其實照打
e.g., node kuaikan "我亲爱的上线了" proxy=localhost:8080還是可以用，只是速度不快

**Comment by kanasimi** [comment]
舉上面的為例
假如有 Proxy IP "123.123.123.123", Proxy Port "3128" 這樣子的proxy
那就可以輸入
`node kuaikan "我亲爱的上线了" proxy=123.123.123.123:3128`

**Comment by gfhghfghfh** [comment]
那麼我貼的網址是可用的嗎
只是照您說的速度不快
是這樣嗎

**Comment by gfhghfghfh** [comment]
請問快看漫畫是否仍不適用proxy
因為https

**Comment by gfhghfghfh** [comment]
請問您有成功下載到嗎，我這邊還是失敗

**Comment by kanasimi** [comment]
這邊在本機上架設了proxy
發現可以下載其他的作品
這程式本身proxy機制沒有問題

至於您那邊沒有辦法下載到
最起碼有兩個可能原因
一個是因為您沒有可供使用的大陸proxy
上面網頁列的那一些不見得有用

另外一個原因可能是就算使用proxy
但是快看漫畫網站還是不給下載
那麼您可能就要嘗試使用[虛擬私人網路](https://zh.wikipedia.org/wiki/%E8%99%9B%E6%93%AC%E7%A7%81%E4%BA%BA%E7%B6%B2%E8%B7%AF)(VPN)了

**Comment by gfhghfghfh** [comment]
那能否請您試試
就算不是用中國的
別國的也行
因為我之前用過goolge 的vpn 連到加拿大的似乎也看的到（所以似乎只擋TW
我只是想了解無法運行的精確原因
感謝您

**Comment by gfhghfghfh** [comment]
另外想請問工具檔名後面要打的is
以後都不用打出來嗎
您給的範例沒看到kuaikan.js 的js

**Comment by kanasimi** [comment]
其實可以不用打副檔名...
