### ISSUE TITLE
 能否讓懶人安裝法的圖形介面不要卡在0% 而是顯示像懶人安裝法的命令行的字

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#136]
像此類動漫之家不能下載的漫畫
https://manhua.dmzj.com/sjdydcl
https://manhua.dmzj.com/yaojingdeweibazero
https://manhua.dmzj.com/haizeiwang

在用懶人安裝法的圖形介面中會一直卡在0%不動

但若用懶人安裝法的命令行會顯示
 Can not get chapter count! 或許作品已被刪除或者網站改版了? (dmzj)

能否讓懶人安裝法的圖形介面不要卡在0% 而是顯示像懶人安裝法的命令行的字

**Comment by gfhghfghfh** [comment]
因為卡在那時下載的取消、暫停功能無法運作，卡在那讓我有點不敢直接關掉程式

**Comment by gfhghfghfh** [comment]
感謝閱讀

**Comment by kanasimi** [comment]
請問您是怎麼輸入的呢
輸入作品ID或者作品名稱?

**Comment by gfhghfghfh** [comment]
都有試過
id與作品名稱都會卡在0%

**Comment by gfhghfghfh** [comment]
<img width="953" alt="default" src="https://user-images.githubusercontent.com/42042168/50084178-06aa7c00-0231-11e9-9815-878e560d4cc2.PNG">

**Comment by gfhghfghfh** [comment]
就像這樣卡在0%

**Comment by gfhghfghfh** [comment]
不會像用命令行一樣顯示Can not get chapter count! 或許作品已被刪除或者網站改版了? (dmzj)
