### ISSUE TITLE
可以請教瀏覽器識別的用途嗎

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#137]
如果在用此程式時
同時在用google chrome 的https://chrome.google.com/webstore/detail/touch-vpn/bihmplhobchoageeokmgbdihknkjbknd
此類vpn的擴充功能

會影響到程式嗎

我個人是希望不會

**Comment by gfhghfghfh** [comment]
感謝閱讀

**Comment by kanasimi** [comment]
只要運行前後始終保持相同的瀏覽器識別
應該就不會影響到

**Comment by gfhghfghfh** [comment]
<img width="535" alt="default" src="https://user-images.githubusercontent.com/42042168/50148159-c3184680-02f2-11e9-9ede-20354641084a.PNG">
您的意思是說
只要塗紅色部分的內的字保持相同內容應該就不會影響到程式

**Comment by gfhghfghfh** [comment]
是這樣嗎

**Comment by kanasimi** [comment]
是的
