### ISSUE TITLE
請求增加土豪漫画 https://www.tohomh.com/

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#138]
理由
因為裡面似乎有很多快看漫畫的收費漫畫
但是是免費的
https://www.tohomh.com/nvwangdeshoushudao/
https://www.tohomh.com/buyaoxiaokannvpeijiao/
https://www.tohomh.com/gongjuedeqiyaoweihunqi/
先舉幾例

貌似與dm5相似

**Comment by gfhghfghfh** [comment]
感謝閱讀
請您慢慢來

**Comment by kanasimi** [comment]
每一個章節似乎都只能看到第一頁?

**Comment by gfhghfghfh** [comment]
是下拉式的漫畫

**Comment by gfhghfghfh** [comment]
上面的例子，我用是沒問題？

**Comment by gfhghfghfh** [comment]
或許您找到的資源是有的
那麼我晚點在多確認其他資源

**Comment by gfhghfghfh** [comment]
我會陸續將找到的貼上來
https://www.tohomh.com/modaozushi/

**Comment by kanasimi** [comment]
也不是那麼像...

**Comment by gfhghfghfh** [comment]
抱歉因為點開章節以前，幾乎一樣
