### ISSUE TITLE
socket hang up抛错

### ISSUE THREAD

**Issue by yakongxing** [kanasimi/work_crawler#14]
下载的时候频繁抛出socket hang up错误.
![shortup](https://upload.cc/i1/2018/04/04/CRjvgy.png)

**Comment by kanasimi** [comment]
socket hang up 表示連線中斷了。經過這邊之前的測試，在網路雜沓的時候比較容易出現這樣子的現像。單單測試上面所列出的作品時回應正常。不曉得您重新執行，也會在相同的地方一直遇到 socket hang up 的問題嗎？

**Comment by yakongxing** [comment]
出错后,我重新下载了数次,总是下载一段时间就再次抛出该错误,不过不是同一地方,是紧接着上次下载后面的地方,我再测试其他的作品.

**Comment by kanasimi** [comment]
@yakongxing 若是您的測試有了結果，麻煩請回報一下，謝謝。

**Comment by kanasimi** [comment]
@yakongxing 若是您沒有其他意見，將關閉這個議題。
