### ISSUE TITLE
有些漫畫資料夾裡的JavaScript 指令檔

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#148]
<img width="511" alt="default" src="https://user-images.githubusercontent.com/42042168/50412353-8512a980-0841-11e9-8f5d-2ef2cd4cdd14.PNG">
<img width="503" alt="1" src="https://user-images.githubusercontent.com/42042168/50412354-8512a980-0841-11e9-908c-f32b48067d9a.PNG">
<img width="540" alt="2" src="https://user-images.githubusercontent.com/42042168/50412355-8512a980-0841-11e9-8750-541c1c7f2739.PNG">
<img width="517" alt="3" src="https://user-images.githubusercontent.com/42042168/50412356-85ab4000-0841-11e9-88ca-be65961dd2db.PNG">

### 少了他們會有甚麼影響?

**Comment by gfhghfghfh** [comment]
少了他們會有甚麼影響

**Comment by gfhghfghfh** [comment]
因為當我將下載位置改到別處
<img width="586" alt="default" src="https://user-images.githubusercontent.com/42042168/50412448-3580ad80-0842-11e9-8017-6d0e219fb652.PNG">




就不會再出現下面這種檔案
<img width="511" alt="50412353-8512a980-0841-11e9-8f5d-2ef2cd4cdd14" src="https://user-images.githubusercontent.com/42042168/50412460-50532200-0842-11e9-9c40-5609abd59fae.PNG">

**Comment by gfhghfghfh** [comment]
所以我想請問少了
<img width="511" alt="50412353-8512a980-0841-11e9-8f5d-2ef2cd4cdd14" src="https://user-images.githubusercontent.com/42042168/50412483-7a0c4900-0842-11e9-9b25-dbfdeaf3176b.PNG">

會造成甚麼影響

**Comment by kanasimi** [comment]
您看到的檔案來自於有些 crawler 會 cache 網站整體的設定，以備不時之需。因為是 cache，就算刪掉了也沒關係。只是下次下載的時候還會再重新擷取並且儲存一次。

**Comment by gfhghfghfh** [comment]
您是說即使資料夾沒有這種檔案，如果需要用到他們時，程式會自己去製作這些檔案（是這個意思嗎）

**Comment by kanasimi** [comment]
修改了一下存放檔案的位置
請您看一下這樣子有沒有比較正常

**Comment by gfhghfghfh** [comment]
問題1
那請問您是說即使資料夾沒有這種檔案，如果需要用到他們時，程式會自己去製作這些檔案（是這個意思嗎）


問題2
所以即使您未修改前,也不會影響到檔案是嘛

**Comment by gfhghfghfh** [comment]
可以在請問一下

問題1
那請問您是說即使資料夾沒有這種檔案，如果需要用到他們時，程式會自己去製作這些檔案（是這個意思嗎）


問題2
所以即使您未修改前,也不會影響到檔案是嘛

**Comment by kanasimi** [comment]
問題1: yes
問題2: yes

**Comment by gfhghfghfh** [comment]
謝謝您
