### ISSUE TITLE
請求增加英語漫画 https://www.webnovel.com/comicList

### ISSUE THREAD

**Issue by KiraYamatoSD** [kanasimi/work_crawler#151]
請求增加 英語漫画 https://www.webnovel.com/comicList

Thanks.

**Comment by kanasimi** [comment]
英文或韓文的網站麻煩您利用 Free Manga Downloader 之類軟體會比較好。這邊幾乎不會上英文或者韓文的漫畫網站，就算做了出來也很少在做維護，沒有專門看英文韓文網站的工具維護得勤勞。
