### ISSUE TITLE
Python Wrapper for WorkCrawler

### ISSUE THREAD

**Issue by DonaldTsang** [kanasimi/work_crawler#159]
Reasoning: To allow for better interface usage with Hydrus (https://github.com/hydrusnetwork/hydrus), and Hydrus is written in Python.

Goals: Allows for the downloading of contents into files, and dump tags into .txt or .json files for Hydrus to use for file sorting.

Other examples of such system: https://github.com/mikf/gallery-dl/issues/146
Other examples of how the downloader would look like in Python: https://github.com/Xonshiz/comic-dl and https://github.com/JimmXinu/FanFicFare

**Comment by kanasimi** [comment]
It is an interesting challenge. May you tell me what kind of API specifications does Hydrus need?

這是個有趣的挑戰。請問 Hydrus 需要什麼樣子的API規格？
