### ISSUE TITLE
汗汗酷漫下载错误

### ISSUE THREAD

**Issue by HJCFLY** [kanasimi/work_crawler#16]
![33](https://user-images.githubusercontent.com/38662362/39966964-aa15500a-56e6-11e8-9efa-3842750c0a06.png)

**Comment by kanasimi** [comment]
您需要直接到 GitHub 下載最新版本 CeJS + work_crawler 壓縮檔，解開後配置。

**Comment by HJCFLY** [comment]
ok 谢谢
