### ISSUE TITLE
請求增加 [lots and lots of websites]

### ISSUE THREAD

**Issue by DonaldTsang** [kanasimi/work_crawler#160]
- [ ] https://github.com/Xonshiz/comic-dl/blob/master/Supported_Sites.md
    - [ ] Mangafox.me
    - [x] Comic Naver
    - [ ] Readcomiconline.to
    - [ ] mangahere.co
    - [ ] raw.senmanga
    - [ ] omgbeaupeep.com
    - [x] ac.qq.com
    - [ ] striputopija.blogspot.si
    - [ ] mangareader.net
    - [ ] readcomicbooksonline.net
    - [ ] mangarock.com
    - [ ] hqbr.com.br
    - [ ] comicextra.com
    - [ ] readcomics.io
    - [ ] otakusmash.com
- [ ] https://github.com/JimmXinu/FanFicFare/wiki/SupportedSites

**Comment by kanasimi** [comment]
I am sorry that for English or Korean sites, using Free Manga Downloader is much suitable. For of the deficiency of time, it is hard to maintain the tools instantly.

**Comment by DonaldTsang** [comment]
@kanasimi leave it open for the future, in that case.
