### ISSUE TITLE
請求增加布卡漫畫http://www.buka.cn/news.html

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#163]
請求增加布卡漫畫http://www.buka.cn/news.html

未找到的資源
http://www.buka.cn/detail/213741
http://www.buka.cn/detail/221978.html
http://www.buka.cn/detail/774.html
http://www.buka.cn/detail/101792.html
http://www.buka.cn/detail/102746.html
http://www.buka.cn/detail/102343.html
http://www.buka.cn/detail/101976.html
http://www.buka.cn/detail/212847.html
http://www.buka.cn/detail/213741.html
http://www.buka.cn/detail/213906.html
http://www.buka.cn/detail/214464.html
http://www.buka.cn/detail/216547.html
http://www.buka.cn/detail/216587.html
http://www.buka.cn/detail/217346.html
http://www.buka.cn/detail/222223
http://www.buka.cn/detail/222322
http://www.buka.cn/detail/221491
http://www.buka.cn/detail/220986
http://www.buka.cn/detail/222013
http://www.buka.cn/detail/220736
http://www.buka.cn/detail/221778
http://www.buka.cn/detail/221676
http://www.buka.cn/detail/220658
http://www.buka.cn/detail/219879
http://www.buka.cn/detail/220286
http://www.buka.cn/detail/220806
http://www.buka.cn/detail/221597
http://www.buka.cn/detail/221363
http://www.buka.cn/detail/220174
http://www.buka.cn/detail/220453
http://www.buka.cn/detail/217953
http://www.buka.cn/detail/221879
http://www.buka.cn/detail/220142
http://www.buka.cn/detail/221099
http://www.buka.cn/detail/219641
http://www.buka.cn/detail/215514
http://www.buka.cn/detail/220351
http://www.buka.cn/detail/220595
http://www.buka.cn/detail/217452
http://www.buka.cn/detail/222113
http://www.buka.cn/detail/219988
http://www.buka.cn/detail/219451
http://www.buka.cn/detail/220454
http://www.buka.cn/detail/219161
http://www.buka.cn/detail/219788
http://www.buka.cn/detail/220254
http://www.buka.cn/detail/219244
http://www.buka.cn/detail/216503
http://www.buka.cn/detail/217147
http://www.buka.cn/detail/217643
http://www.buka.cn/detail/220186
http://www.buka.cn/detail/221229
http://www.buka.cn/detail/220224
http://www.buka.cn/detail/214600
http://www.buka.cn/detail/220031
http://www.buka.cn/detail/218811
http://www.buka.cn/detail/219280
http://www.buka.cn/detail/219732
http://www.buka.cn/detail/219577
http://www.buka.cn/detail/220094
http://www.buka.cn/detail/219842

感謝閱讀
請您慢慢來

**Comment by kanasimi** [comment]
add on https://github.com/kanasimi/work_crawler/commit/5242a98f4d13cb2ebba53b1acfe611100789c546
