### ISSUE TITLE
下載新章節問題

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#169]
懶人安裝法 圖形介面

⓵dm5

<img width="826" alt="default" src="https://user-images.githubusercontent.com/42042168/51436614-6500c980-1ccb-11e9-88c2-35defa635acc.PNG">
我在下載時是這樣配置的

但我發現程式不會下載到位於翻外的新章節
<img width="482" alt="default" src="https://user-images.githubusercontent.com/42042168/51436632-a72a0b00-1ccb-11e9-9af1-4dc896e4b82b.PNG">

只會下載到連載的新章節
<img width="492" alt="default" src="https://user-images.githubusercontent.com/42042168/51436651-20296280-1ccc-11e9-83ac-06035c6595e6.PNG">

**Comment by gfhghfghfh** [comment]
我想或許古風也會有相同問題

**Comment by gfhghfghfh** [comment]
<img width="826" alt="51436614-6500c980-1ccb-11e9-88c2-35defa635acc" src="https://user-images.githubusercontent.com/42042168/51436909-a5167b00-1cd0-11e9-8369-25c98b009877.PNG">

我在下載時是這樣配置的





https://web-ace.jp/youngaceup/contents/1000088/episode/
<img width="719" alt="gffffgdfgfsgfdgsf" src="https://user-images.githubusercontent.com/42042168/51436917-c9725780-1cd0-11e9-96ee-2471ee2fda4a.PNG">


但我只下載到68沒下載到67-2
(67-1以前的話數之前都下載過了)

**Comment by kanasimi** [comment]
能麻煩您把下載的網站和作品名稱標示清楚嗎

**Comment by kanasimi** [comment]
這邊下載 古风漫画网 jueduandi 决断地 沒有遇到缺話的問題
