### ISSUE TITLE
write_chapter_metadata 和write_image_metadata用途

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#175]
不好意思
可以請教
<img width="686" alt="ghdfghdg" src="https://user-images.githubusercontent.com/42042168/51454382-51169f80-1d7f-11e9-912e-6481216c8275.PNG">

這兩個新功能的用途嗎

**Comment by kanasimi** [comment]
方便其他工具匯入用。 see #159

**Comment by gfhghfghfh** [comment]
所以不影響圖檔是嗎

**Comment by kanasimi** [comment]
yes

**Comment by gfhghfghfh** [comment]
感謝您的回覆
