### ISSUE TITLE
添加章节选择下载

### ISSUE THREAD

**Issue by enuff** [kanasimi/work_crawler#18]
软件非常的棒，我喜欢下载漫画到电脑上看，但是下载只能从头开始下载吗，我想从某个章节开始下载

**Comment by kanasimi** [comment]
謝謝您的使用。請問您用的是圖形介面或是或是命令列介面呢？若是使用命令列介面，您可以採用 start_chapter 這個參數，就可以挑選開始下載的章節。

e.g.,
``node qq 作品名 start_chapter=20``

**Comment by enuff** [comment]
我这个人比较懒，用的是图形界面

**Comment by enuff** [comment]
命令界面测试可行，就是找漫画的时候有点费事，切换也有点麻烦，软件思路很清晰

**Comment by kanasimi** [comment]
已經在無形界面中加入此功能。必須麻煩您下載最新版本 CeJS 與 work_crawler。

**Comment by kanasimi** [comment]
已經在圖形介面中加入此功能。得麻煩您下載最新版本 CeJS 與 work_crawler。

**Comment by kanasimi** [comment]
圖形介面在右手邊的 **下載選項** 應該可以看到有一個 **start_chapter: 將開始/接續下載的章節編號。必須要配合 .recheck。 (number)**。
請和上面的 recheck 一起指定就可以了。
