### ISSUE TITLE
偵錯工具的訊息

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#180]
<img width="431" alt="gdfgdfgd" src="https://user-images.githubusercontent.com/42042168/51514038-fd708880-1e48-11e9-93c5-c1bd29784dea.PNG">

我每次打開時都會出現這些

請問會影響到我下載嗎

**Comment by kanasimi** [comment]
不會影響到下載

**Comment by gfhghfghfh** [comment]
那顯示這些是正常的嗎

**Comment by kanasimi** [comment]
上面紅色那段應該是更新時出現錯誤

詳細情況得要偵錯
但是這邊沒有遇到這樣的情況...

**Comment by gfhghfghfh** [comment]
那第一塊的紅色部分
和第三塊的黃色部分都是正常的嗎

**Comment by kanasimi** [comment]
第一塊正常
第三塊提示這邊應該要用安全一點的 eval

**Comment by gfhghfghfh** [comment]
是我這邊要改嗎?(第三塊提示這邊應該要用安全一點的 eval)

**Comment by kanasimi** [comment]
是程式碼裡面
但是現在還沒找到比較安全又不會影響到下載的方法

**Comment by gfhghfghfh** [comment]
好的
謝謝您
第二塊我再觀察看看

**Comment by gfhghfghfh** [comment]
我重新下載了一次
<img width="426" alt="default" src="https://user-images.githubusercontent.com/42042168/51516003-b71f2780-1e50-11e9-8ba2-5612bd928734.PNG">


請問這樣正常了嗎

**Comment by kanasimi** [comment]
yes

**Comment by gfhghfghfh** [comment]
不好意思
您是說上面兩個問題的答案都是yes嗎

**Comment by kanasimi** [comment]
yes

**Comment by gfhghfghfh** [comment]
感謝您的回覆
