### ISSUE TITLE
嘗試更動 漫畫名.js檔

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#184]
想請問
我嘗試更動mrblue.js((work_crawler/comic.cmn-Hans-CN/mrblue.js))的內容

除了影響到mrblue的下載
其餘都不會影響吧

**Comment by gfhghfghfh** [comment]
我只有將35行的部分從
return 'MrBlueComicsData_04/webtoon/' + work_id + '/';

改成

return 'MrBlueComicsData_01/dcwcomic/' + work_id + '/';

**Comment by kanasimi** [comment]
應該只會影響到mrblue的下載
