### ISSUE TITLE
乙女漫畫下載問題

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#187]
想請問為甚麼
是顯示手機板的
mobile-agent:mobile-agent %E2%86%92format=xhtml; url=http://m.nokiacn.net/yinv/baojianshibeidejian/

還是說,還是取得網頁版的,只是上面那行只是網頁的資訊?

<img width="560" alt="gfhfghf" src="https://user-images.githubusercontent.com/42042168/51789453-f5f00d00-21c3-11e9-8a85-28afe93c868e.PNG">

**Comment by kanasimi** [comment]
這是上次  #177 的遺毒
上面那行只是網頁的資訊

**Comment by gfhghfghfh** [comment]
所以說您說的遺毒，新的程式碼已經改過來了，然後紫色一條條的資訊就是改正後的資訊

**Comment by gfhghfghfh** [comment]
2.手機版的網站的網址只是網頁資訊，仍舊是用網頁版下載
是這樣嗎

**Comment by kanasimi** [comment]
1. 2. yes
