### ISSUE TITLE
regenerate:章節數量無變化時依舊利用 cache 重建資料(如ebook)。 (boolean)

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#189]
<img width="547" alt="default" src="https://user-images.githubusercontent.com/42042168/51800433-8a607b00-2269-11e9-8de3-6311a88610d0.PNG">

請問此功能的用途

**Comment by kanasimi** [comment]
如下載小說時不重新取得網頁資料，只重建ebook檔

**Comment by gfhghfghfh** [comment]
只對小說有用嗎

**Comment by kanasimi** [comment]
漫畫不需要重建電子書檔案
