### ISSUE TITLE
甚麼條件下會出現dm5: 章節數量無變化，共 8 章，跳過本作品不處理。

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#190]
<img width="498" alt="default" src="https://user-images.githubusercontent.com/42042168/51815983-6b142d00-22ff-11e9-95d7-70bc2baa0504.PNG">

**Comment by kanasimi** [comment]
章節數量無變化時

**Comment by gfhghfghfh** [comment]
但如果有些情況章節數目有刪除或增加，導致章節數相同，這樣不就檢查不到了

**Comment by gfhghfghfh** [comment]
我是在打開 .recheck的狀態試的

**Comment by gfhghfghfh** [comment]
manhua-beizhaihefan 北斋和饭

**Comment by kanasimi** [comment]
請取消勾選後重新勾選試試看

**Comment by gfhghfghfh** [comment]
謝謝
