### ISSUE TITLE
安裝包的優勢

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#199]
想請問安裝包有什麼優勢嗎
因為若是圖形介面的話，懶人安裝法也做得到，懶人安裝法得到的版本也比較新

**Comment by kanasimi** [comment]
因為有些使用者不熟悉命令行界面
因此有安裝包對他們來說更方便

另外您可以參考
 #27

**Comment by gfhghfghfh** [comment]
那照您這樣說起來
懶人安裝法還是比較有優勢嗎（除了可能會不熟悉怎麼使用

**Comment by kanasimi** [comment]
懶人安裝法更新比較快速

感謝您這些日子來對本工具的熱心關注
歡迎您參加本工具的翻譯計畫
尤其是韓語的部分 🙂

**Comment by gfhghfghfh** [comment]
謝謝您的回覆
不好意思
不是我不願意
只是我真的不會韓語(雖然我有想學)
會想收藏韓語漫畫是因為漢化版的通常會有很多水印
或是會利用google(因為現在可以翻譯圖片)
讓您誤會真是不好意思
