### ISSUE TITLE
下載問題

### ISSUE THREAD

**Issue by qqqqqwwwwwww** [kanasimi/work_crawler#20]
我下載這個總是失敗https://tw.manhuagui.com/comic/20063/
還有http://www.manhuatai.com/xianganweijing/
請問可以幫我解決問題嗎
謝謝您

**Comment by kanasimi** [comment]
請問您說的白屏是圖片出問題，或者您使用了網頁介面下載時出問題呢？

若是有出現錯誤訊息，是不是能夠post出來呢？

**Comment by qqqqqwwwwwww** [comment]
我等等post圖
白屏是指下載視窗變白

**Comment by qqqqqwwwwwww** [comment]
![default](https://user-images.githubusercontent.com/41066147/42625398-40ccde72-85fa-11e8-81b3-595f9ee84ef7.PNG)
![gnjk](https://user-images.githubusercontent.com/41066147/42625399-40feb924-85fa-11e8-9fbd-40ef3c263fb1.PNG)

**Comment by qqqqqwwwwwww** [comment]
白屏每次都是突然發生

**Comment by qqqqqwwwwwww** [comment]
順便請教一下會出現retry1/4是正常的嗎

**Comment by kanasimi** [comment]
@qqqqqwwwwwww 白屏的原因找到了，下一版會修正。

retry 表示下載出了問題，重新嘗試。

**Comment by qqqqqwwwwwww** [comment]
謝謝您
那麼重新嘗試後若沒出現紅字或黃字
就是沒問題了嗎

**Comment by kanasimi** [comment]
yes. 重新嘗試後若沒出現紅字或黃字 就是沒問題了

**Comment by qqqqqwwwwwww** [comment]
謝謝您

**Comment by kanasimi** [comment]
問題還沒解決 所以我先開著

**Comment by qqqqqwwwwwww** [comment]
可以再請教一下這個程式是安全的嗎
(對不起我知道這樣問不太好,請見諒)
因為我電腦原有的掃毒軟體
會顯示不安全之類的訊息

**Comment by kanasimi** [comment]
應該是因為使用的CeJS函式庫包山包海，裡面有一些專門用於檔案操作的函數、FileSystemObject 物件、WScript 物件，所以掃毒軟體就以為有問題。不過這個程式我天天都在測試，漫畫下載並不會用到這些功能，您大可放心。

**Comment by qqqqqwwwwwww** [comment]
謝謝您

**Comment by kanasimi** [comment]
@qqqqqwwwwwww 請問 manhuatai 下載的時候也會出現白屏嗎
或者出現的是其他什麼問題？
問題會重複出現嗎? (第二次第三次依舊出現同樣的問題?)

**Comment by qqqqqwwwwwww** [comment]
是的
manhuatai 下載的時候也會出現白屏
會重複出現
(我試過好幾次)

**Comment by kanasimi** [comment]
這個問題已經在最新的版本修復，您需要直接到 GitHub 下載最新版本 CeJS 與 work_crawler。
