### ISSUE TITLE
快看漫画无法下载VIP付费内容

### ISSUE THREAD

**Issue by GooglePlugin** [kanasimi/work_crawler#200]
﻿

* **Version**: Lastest Release
* **Interface**: 图形界面

无法下载快看漫画付费章节

**Comment by kanasimi** [comment]
yes.  已確認本工具無法下載VIP付費內容

**Comment by GooglePlugin** [comment]
多谢解答，请问是否需要关闭这个issue?

**Comment by kanasimi** [comment]
這邊沒有快看漫画帳號
因此無法取得快看漫画的付費漫畫
