### ISSUE TITLE
ECHO Please install electron first!   && PAUSE

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#206]
懶人安裝圖形介面

<img width="933" alt="default" src="https://user-images.githubusercontent.com/42042168/52532344-7daa4f80-2d5e-11e9-87d7-f3bf3dea2e6d.PNG">

我記得以前沒有
 ECHO Please install electron first!   && PAUSE

請問這樣正常嗎

**Comment by kanasimi** [comment]
yes. 正常

**Comment by gfhghfghfh** [comment]
請問您是改成|| C:\Users\qwe\node_modules\.bin\electron .   || ECHO Please install electron first!   && PAUSE


都不會顯示嗎

**Comment by kanasimi** [comment]
出問題才會顯示
