### ISSUE TITLE
漫畫目錄名稱不須包含分部號碼。使章節目錄名稱不包含 part_NO。

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#207]
漫畫目錄名稱不須包含分部號碼。使章節目錄名稱不包含 part_NO。
(https://github.com/kanasimi/CeJS/commits?author=kanasimi)

可以問一下這句話的意思嗎
不太清楚更動了甚麼

**Comment by kanasimi** [comment]
小說才有第一部第二部之分，漫畫分部不會有號碼(part_NO)，因此去掉漫畫目錄名稱名稱之號碼標示。

**Comment by gfhghfghfh** [comment]
以前漫畫目錄名稱名稱有號碼嗎?

**Comment by kanasimi** [comment]
yes...

**Comment by gfhghfghfh** [comment]
請問您能截圖
章節目錄名稱的分部號碼嗎
的畫面嗎
不好意思

**Comment by kanasimi** [comment]
e.g.,
"01 单话 0001 第371回"

**Comment by gfhghfghfh** [comment]
但漫畫有分部會有 01 单话 0001 第371回
沒分部的就只有 0001 第371回

原本就是這樣

**Comment by kanasimi** [comment]
"01 单话 0001 第371回"
→"单话 0001 第371回"

**Comment by gfhghfghfh** [comment]
我剛剛操作好像還是01 单话 0001 第371回

**Comment by gfhghfghfh** [comment]
請問您有要改動古風和動漫屋的部分嗎?

**Comment by kanasimi** [comment]
yes

**Comment by gfhghfghfh** [comment]
目前還是有分部號碼

**Comment by gfhghfghfh** [comment]
目前古風和動漫屋還是有分部號碼
