### ISSUE TITLE
增加網站: webtoons

### ISSUE THREAD

**Issue by sandycheng1** [kanasimi/work_crawler#21]
請問可以增加這個網站嗎
https://comic.naver.com/webtoon/weekday.nhn

**Comment by kanasimi** [comment]
這個網站...我會非常需要翻譯支援...

**Comment by sandycheng1** [comment]
那https://www.webtoons.com/zh-hant/((中文版的

**Comment by kanasimi** [comment]
這個可以評估看看

**Comment by sandycheng1** [comment]
謝謝

**Comment by sandycheng1** [comment]
可以問一下我該怎麼加進去
不好意思這方面我是新手

**Comment by kanasimi** [comment]
您可參考 https://carolhsu.gitbooks.io/django-girls-tutorial-traditional-chiness/content/intro_to_command_line/README.html

**Comment by sandycheng1** [comment]
我打開了命令提示字元
請問我該如何進到本工具安裝的目錄

**Comment by kanasimi** [comment]
這邊增加了一些說明
https://github.com/kanasimi/work_crawler#lazy-installation-%E6%87%B6%E4%BA%BA%E5%AE%89%E8%A3%9D%E6%B3%95
麻煩您看一下
還有哪邊需要加強說明

**Comment by kanasimi** [comment]
最近的幾個議題處理一下後
會再釋出新的安裝包

那麼您或許可以直接把這個議題關掉
並且等新安裝包釋出了

**Comment by sandycheng1** [comment]
感謝

**Comment by kanasimi** [comment]
@sandycheng1 其實我很希望能夠把文檔寫到您能夠了解並且操作的地步
若是您不嫌棄的話
不曉得能夠能夠描述一下
您大概在哪個部分遇到困難
所以沒有辦法執行嗎
謝謝您

**Comment by kanasimi** [comment]
新的安裝包已經出來了
您可以試試

**Comment by sandycheng1** [comment]
抱歉現在才看到
好的,我會試著重新再看一遍,找出不懂的部分
不過當我再用的時候
會與直接下載安裝包衝突嗎

另外我不知道為甚麼
當我下載https://www.webtoons.com/zh-hant/thriller/maogusongran/list?title_no=528
出現
[📝]webtoons: 2018-07-16T11:59:59.351Z Starting 2015毛骨悚然特輯, 儲存至 webtoons\
[📝]webtoons: Find cache: 2015毛骨悚然特輯→528
[ℹ][1:23.582] 528 [短篇集] 2015毛骨悚然特輯: 38 章. 恐怖,完結
[📝]528 2015毛骨悚然特輯: 38 章 done. 本作品下載作業結束.

然後也沒有下載到東西

**Comment by sandycheng1** [comment]
還有當我想移動work_crawler時(因為空間不夠)
只要把work_crawler整個資料夾
移動到新位置就可以了嗎

**Comment by sandycheng1** [comment]
![1](https://user-images.githubusercontent.com/41149813/42758193-4b2b9f8c-8935-11e8-93d2-f30002aaea12.PNG)
黃色框框的部分
我不清楚在做甚麼

**Comment by kanasimi** [comment]
空間不夠的時候
只要把整個work_crawler資料夾都移動到新位置就可以了

2015毛骨悚然特輯
這個作品有互動功能
很遺憾的沒有辦法當作圖片來下載

**Comment by kanasimi** [comment]
黃色框框的部分是在linux下直接操作時的指令，Windows用戶可以跳過。

**Comment by sandycheng1** [comment]
我剛剛不小心弄到卸載(剛剛有點慌亂)
重新安裝後只要把
像是gufengmh
hhcool
webtoons
之類的檔移過去就行了嗎

**Comment by sandycheng1** [comment]
那Setup GUI 設定視窗型態介面 的部分
其實也是要等您增加完按鈕才能使用新功能嗎

**Comment by kanasimi** [comment]
若是檔案都還在的話只要重新移過去就可以了
不過卸載的話不是會把附屬檔案也一起刪除嗎?

**Comment by sandycheng1** [comment]
我是按到Uninstall work_crawler

**Comment by kanasimi** [comment]
您可以檢查看看
若是檔案都還在的話只要重新移過去就可以了

**Comment by sandycheng1** [comment]
如果修正bug後
我去下載修正後的work_crawler-master
執行懶人安裝法的步驟
 
修正的結果會到work_crawler嗎(之前從直接下載安裝包出來的資料夾)

**Comment by sandycheng1** [comment]
我想請問一下
為甚麼不能在程式的介面中
複製
貼上
之類的動作

**Comment by kanasimi** [comment]
應該會解開到 work_crawler-master 目錄
您可以把裡面的檔案全部移動
並且覆蓋舊的檔案就可以了

**Comment by sandycheng1** [comment]
不能在程式的介面中
複製
貼上
之類的動作
是指
![1](https://user-images.githubusercontent.com/41149813/42759609-2ceb5d3c-893a-11e8-9354-b775cf2a818f.PNG)

**Comment by kanasimi** [comment]
複製貼上快速鍵:
Ctrl + X | 剪下選取的項目
Ctrl + C (或Ctrl + Insert) | 複製選取的項目
Ctrl + V (或Shift + Insert) | 貼上選取的項目
Ctrl + Z | 復原動作

**Comment by sandycheng1** [comment]
謝謝您

**Comment by sandycheng1** [comment]
https://www.webtoons.com/zh-hant/slice-of-life/yumi-cell/list?title_no=461
https://www.webtoons.com/zh-hant/comedy/pingxingshijie/list?title_no=535
這兩個也是不支持嗎

**Comment by kanasimi** [comment]
剛剛修復了
您需要直接到 GitHub 下載最新版本 CeJS 與 work_crawler。
