### ISSUE TITLE
關於add 儲存最愛作品清單的檔案

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#212]
﻿我想問一下
<img width="339" alt="default" src="https://user-images.githubusercontent.com/42042168/52703158-aded2a80-2fb8-11e9-8d79-3455e56e9452.PNG">

為甚麼會這樣寫?
原本就有preference的檔案會記錄最愛作品清單

請問您是改變了甚麼

若問了蠢問題請見諒
我想確保我不會使用不當

感謝閱讀

**Comment by kanasimi** [comment]
可以把最愛作品清單放在獨立的檔案，更便於編輯。

**Comment by gfhghfghfh** [comment]
那我不用改動任何東西，新的程式自己會改是嗎？

**Comment by kanasimi** [comment]
1. yes
2. 若有問題請馬上回報 請勿存檔
