### ISSUE TITLE
改回舊有最愛清單遇到重複項時的處理方式

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#214]
### **以前**
我覺得以前的方式較好
舉例
當遇到重複項時
<img width="313" alt="default" src="https://user-images.githubusercontent.com/42042168/52787942-676ffc80-309a-11e9-9231-46765df1ad0d.PNG">

按下
💾儲存最愛作品清單
後
自動消去重複項
<img width="535" alt="default" src="https://user-images.githubusercontent.com/42042168/52788009-9a19f500-309a-11e9-9674-da3da28bf718.PNG">

當再次編輯時
重複項也不會存在
<img width="352" alt="default" src="https://user-images.githubusercontent.com/42042168/52788060-bae24a80-309a-11e9-949d-98ea3a398912.PNG">

此方式似乎比現在的方式方便

**Comment by gfhghfghfh** [comment]
現在的方式
還要按下🔨重新整理列表檔案
按了之後
再次編輯
<img width="338" alt="default" src="https://user-images.githubusercontent.com/42042168/52788289-67243100-309b-11e9-8037-2085b7f7670d.PNG">

我認為沒有比較方便

**Comment by gfhghfghfh** [comment]
希望您能改回來
感謝閱讀

**Comment by gfhghfghfh** [comment]
剛剛測試
還是
<img width="247" alt="default" src="https://user-images.githubusercontent.com/42042168/52789153-0c400900-309e-11e9-8272-cf4c9a4288ee.PNG">

**Comment by kanasimi** [comment]
fixed
