### ISSUE TITLE
最愛清單的顯示

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#217]
<img width="535" alt="default" src="https://user-images.githubusercontent.com/42042168/53002802-8b4f8b80-3468-11e9-83ce-ab5725e6e71e.PNG">

請問可以回復以前**沒有**紅色叉叉的樣子嗎
感覺很容易按錯
畫面有點亂

**Comment by kanasimi** [comment]
請問您之前有下載過這個作品嗎
照理來說有下載過應該就會變成藍色的了

**Comment by gfhghfghfh** [comment]
是還沒
但是我是表達叉叉的部分
會讓畫面有點稜亂
感覺很容易按錯

**Comment by kanasimi** [comment]
紅色是要加強提醒
預防不小心按錯...

**Comment by gfhghfghfh** [comment]
預防不小心按錯
請問您是指按錯甚麼

**Comment by kanasimi** [comment]
按錯叉叉
