### ISSUE TITLE
使用qTcms2017系統的網站一定要開啟圖形介面中的one_by_one 才能下載嗎

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#218]
https://github.com/kanasimi/CeJS/blob/master/application/net/work_crawler/qTcms2017.js
想請問上述的網址

裡面在第54到55行寫著
// 因為要經過轉址，所以一個圖一個圖來。
		// one_by_one : true,

請問是說使用qTcms2017系統的網站一定要開啟圖形介面中的one_by_one 才能下載嗎

**Comment by kanasimi** [comment]
話是這麼說...
其實現在還是用並行下載
只是預防有些網站會限制罷了

**Comment by gfhghfghfh** [comment]
所以說還是可以繼續使用並行下載
除非遇到問題嗎

**Comment by kanasimi** [comment]
yes
