### ISSUE TITLE
請問favorite.txt.bak用途

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#219]
<img width="202" alt="default" src="https://user-images.githubusercontent.com/42042168/53003998-2d707300-346b-11e9-8d0a-16a196b2fd32.PNG">

**Comment by kanasimi** [comment]
backup old favorite list file 預防一不小心操作錯誤時還可以補救

**Comment by gfhghfghfh** [comment]
請問是備份最後一次修改前的書籤嗎
例如
第一次修改
第二次修改
第三次修改
第四次修改

然後備份第三次的書籤嗎

**Comment by kanasimi** [comment]
yes

**Comment by gfhghfghfh** [comment]
抱歉因為我剛修改了幾次
能您請您在回覆一次嗎

請問是備份最後一次修改前的書籤嗎
例如 第一次修改 第二次修改 第三次修改 第四次修改

然後備份第三次的書籤嗎

**Comment by kanasimi** [comment]
備份最後一次修改前的書籤，預防一不小心操作錯誤時還可以補救。
