### ISSUE TITLE
改成增加http://mangahasu.se

### ISSUE THREAD

**Issue by sandycheng1** [kanasimi/work_crawler#22]
可以增加下面這個網站嗎
http://www.mangago.me/

**Comment by kanasimi** [comment]
這個網站有保護 不好下手

**Comment by sandycheng1** [comment]
那請問這個能嗎
http://mangahasu.se

**Comment by kanasimi** [comment]
這個網站也有 Cloudflare 的保護...

**Comment by sandycheng1** [comment]
最後能再幫我試試
https://www1.mangamew.com/
或是這個嗎
http://mangatopnew.com/home
謝謝

**Comment by xuelainiao** [comment]
@sandycheng1 漫画终极粉丝啊，这么多站点

**Comment by sandycheng1** [comment]
請問一下
我剛剛看了https://github.com/kanasimi/work_crawler/commit/2fd3fe39efd3e0697013bbbab4ab127ec5947b62
裡面的網址是另一個網站
這代表上述剩下的兩個網址也是受到保護的嗎

**Comment by kanasimi** [comment]
點擊
http://mangatopnew.com/home
進入漫畫頁面之後
您會發現漫畫連到這個網站
http://manganew.net/
因此這邊採用的就是最後連結到的網站
