### ISSUE TITLE
按鈕問題

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#222]
﻿目前當我按到書籤多的網站時
會卡
照您的說法
<讀取作品資訊檔案以判別作品是否已下載過、是否完結。選擇網站時，這可能造成幾十秒鐘無回應。>

但當我滑至底部
出現
<img width="809" alt="default" src="https://user-images.githubusercontent.com/42042168/53009609-dec8d600-3476-11e9-989d-f99bb99f3c70.PNG">

意思是還沒讀取
按了按鈕才會讀取嗎
如果還沒讀取的話
那為甚麼按到書籤多的網站會卡

如有冒犯請見諒,並無冒犯之意

**Comment by kanasimi** [comment]
這次改版用上了功能比較強的解析器
但是也造成解析速度比較慢
這點請見諒

**Comment by gfhghfghfh** [comment]
那請問最下面的兩個按鈕功能有差別嗎
<img width="809" alt="default" src="https://user-images.githubusercontent.com/42042168/53010305-7f6bc580-3478-11e9-859f-06cc992c5cab.PNG">

**Comment by gfhghfghfh** [comment]
@kanasimi 
請問
<img width="765" alt="default" src="https://user-images.githubusercontent.com/42042168/53010978-416fa100-347a-11e9-91a6-4742edbe8a96.PNG">

這兩個按鈕的差別

**Comment by kanasimi** [comment]
本網站 vs. 所有網站

**Comment by gfhghfghfh** [comment]
那請問在**只有**點擊**網站按鈕**時
程式會讀取作品資訊檔案以判別作品是否已下載過、是否完結嗎
<img width="144" alt="default" src="https://user-images.githubusercontent.com/42042168/53011868-65cc7d00-347c-11e9-828e-a2fa2bb684ff.PNG">

**Comment by kanasimi** [comment]
no

**Comment by gfhghfghfh** [comment]
不會讀取的話
請問點擊**網站按鈕**的時候為甚麼會卡

**Comment by kanasimi** [comment]
這次改版用上了功能比較強的解析器
但是也造成解析速度比較慢

**Comment by gfhghfghfh** [comment]
<img width="656" alt="default" src="https://user-images.githubusercontent.com/42042168/53013112-e50f8000-347f-11e9-836e-80484e575749.PNG">


那請問書籤少的為甚麼就不會有
<img width="765" alt="default" src="https://user-images.githubusercontent.com/42042168/53014395-50a71c80-3483-11e9-98f8-24db7cd94101.PNG">
