### ISSUE TITLE
乙女漫畫按鈕無法點選

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#228]
﻿
<img width="192" alt="default" src="https://user-images.githubusercontent.com/42042168/53262034-857bd380-3710-11e9-8d4a-9ae99d28703f.PNG">

**Comment by kanasimi** [comment]
您可能得刪除掉作品目錄下面的 search.json，重新搜尋
另外您必須要提供整個畫面以及訊息欄
比較容易判別問題所在

**Comment by gfhghfghfh** [comment]
因為沒有出現訊息欄所以才沒有提供的
