### ISSUE TITLE
請求增加 哔哩哔哩漫画 https://manga.bilibili.com/m

### ISSUE THREAD

**Issue by faxianzhilu** [kanasimi/work_crawler#229]
发现之前有一个人提出类似问题，但是发现使用谷歌浏览器开发者工具还是可以在Network里发现jpg图片的，是不是考虑增加一个抓取哔哩哔哩漫画图片的功能，本人不会编程，不懂此类技术，但是既然浏览器中可以找到图片链接，应该是能实行抓取的，还请您再研究一下解决方案？

**Comment by kanasimi** [comment]
duplicated #164

**Comment by kanasimi** [comment]
Duplicate of #164

**Comment by kanasimi** [comment]
最近陸續有幾個帖提到哔哩哔哩漫画
https://github.com/ipcjs/bilibili-helper/issues/353
https://github.com/feilongfl/Cimoc/issues/27
聽說[哔哩哔哩漫画的畫質最高](https://github.com/abcfy2/getComic/issues/23)
這有點說服我
但不能搜尋還是硬傷
我猜哔哩哔哩假如想經營PC端這一塊
未來還會把搜尋功能做出來
而且能下載的漫畫現在還太少了

**Comment by faxianzhilu** [comment]
感谢增加此网站！
