### ISSUE TITLE
这工具实在牛逼，不过想请教一下移动端如何看下载下来的漫画图片比较好

### ISSUE THREAD

**Issue by xuelainiao** [kanasimi/work_crawler#23]
图片自动打包成zip，我试着转化成epub格式，但是图片并没有自动拼接起来，找了一下网络并没有比较合适的看多图漫画的软件，求个推荐，谢谢！

**Comment by kanasimi** [comment]
有個方法是不要打包
並且多產生一個網頁檔案
然後利用網頁把圖片拼接起來
不曉得您覺得這個點子怎麼樣

**Comment by xuelainiao** [comment]
我昨天饶有兴趣的试了IOS上面很多漫画软件，最后找到一种比较不错的办法，就是将下载好的漫画ZIP文件放入一个文件夹中，然后导入到手机的**布卡漫画**的文件夹中即可观看，效果是非常不错的
感谢您这么快给予回复，谢谢！

**Comment by kanasimi** [comment]
謝謝您提供解決方法 :)

**Comment by xuelainiao** [comment]
好的~~
