### ISSUE TITLE
想請問安裝位置的限制

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#230]
﻿使用懶人安裝法時
我將work_crawler-master 資料夾
放到D:\新增資料夾\work_crawler-master
或是放到其他**含有中文或是特殊字元或是含空格**的資料夾內(也就是上行新增資料夾的位置**含有中文或是特殊字元或是含空格**)

請問會影響到程式運作嗎

**Comment by kanasimi** [comment]
照理來說是不會有問題
若是您遇到什麼問題
麻煩請回報一下

**Comment by gfhghfghfh** [comment]
因為剛學程式
上面是說
專案名稱與資料夾位置
1. 不要用中文
2. 不要用特殊字元
3. 不要包含空格
4. 最好只用：大小寫英文
字母 a~zA~Z、阿拉伯數
字 0~9、底線_

但使用一般做好的程式(像您這個程式)
基本上是不會有這個問題
是嗎

**Comment by kanasimi** [comment]
有時要看程式設計時有沒有考量到這些因素

**Comment by gfhghfghfh** [comment]
<近期的程式會比較少遇到這樣的問題>

您的意思是說通常使用者放的位置沒有限制嗎

**Comment by kanasimi** [comment]
近期的程式多會考量到這些因素

**Comment by gfhghfghfh** [comment]
保險起見您請您看下,下面沒有出錯吧
<img width="267" alt="default" src="https://user-images.githubusercontent.com/42042168/53537486-13a6ee00-3b45-11e9-99df-6b34b3052ea9.PNG">

**Comment by kanasimi** [comment]
這邊的幾條訊息都正常

**Comment by gfhghfghfh** [comment]
不好意思再問一次
近期的程式多會考量到使用者放的位置可能含有中文,特殊字元,含空格
是這樣嗎

**Comment by kanasimi** [comment]
yes
