### ISSUE TITLE
命令行介面訊息數問題

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#231]
﻿

* **Version**: 
* **Interface**:

**Comment by kanasimi** [comment]
命令行介面本來就沒有限制行數...

**Comment by gfhghfghfh** [comment]
但是前面的訊息真的消失了

**Comment by gfhghfghfh** [comment]
剛剛查了是因為命令行介面最大的行數是9999
請問圖形介面的不限行數真的是不限行數嗎

**Comment by kanasimi** [comment]
只要您的電腦記憶體夠大
程式不會掛掉
就不會被限制

**Comment by gfhghfghfh** [comment]
順便請問一下，當我在使用圖形介面時
那些訊息是暫存在哪裡（因為您說記憶體夠大，就不會有限制

**Comment by kanasimi** [comment]
暫存在記憶體
