### ISSUE TITLE
请求支持增加网易和腾讯的vip下载

### ISSUE THREAD

**Issue by adsl95** [kanasimi/work_crawler#232]
如果自己有会员的话呢?
作者是否愿意增加登陆界面?
账号有vip支持的话应该下载下来没太多问题.
感谢.

**Comment by kanasimi** [comment]
抱歉這邊沒有帳號
因此不能做相關的測試

**Comment by kanasimi** [comment]
若您無其他意見，這個議題將在下次安裝包釋出前關閉。
