### ISSUE TITLE
bilibili漫画app版【可正常搜索】 https://manga.bilibili.com/twirp/comic.v1.Comic/Search

### ISSUE THREAD

**Issue by mabDc** [kanasimi/work_crawler#233]
哔哩哔哩漫画 搜索功能可以借助app版，漫画详情与章节内容可选择网页版。
搜索方法如下
api接口 https://manga.bilibili.com/twirp/comic.v1.Comic/Search
post form or json，{"page_num":number,"page_size": number,"key_word":keyword}
一个例子如下
POST https://manga.bilibili.com/twirp/comic.v1.Comic/Search HTTP/1.1
Host: manga.bilibili.com
Content-Type: application/json
Content-Length: 55

{"page_num":1,"page_size":10,"key_word":"蜉蝣一梦"}
![image](https://user-images.githubusercontent.com/19526331/53684905-6d2e3900-3d4e-11e9-8ace-a59c307273b2.png)
例子中详情页与目录页对应于 [蜉蝣一梦 https://manga.bilibili.com/m/detail/mc25915](https://manga.bilibili.com/m/detail/mc25915) <--JSON.data.id
如有计划，或许可做尝试。
感谢阅读

**Comment by kanasimi** [comment]
Duplicate of #229, #164

**Comment by kanasimi** [comment]
Duplicate of #229
Duplicate of #164

**Comment by kanasimi** [comment]
Duplicate of #164

**Comment by kanasimi** [comment]
Duplicate of #229

**Comment by kanasimi** [comment]
收費作品太多，PC端只給看10話，感覺很難用。並且系統太複雜，每次改版恐怕得花許多時間來修正，因此恐不再維護。
