### ISSUE TITLE
下载速度为零肿么回事啊

### ISSUE THREAD

**Issue by app911** [kanasimi/work_crawler#237]
RT
![121](https://user-images.githubusercontent.com/8065600/53929645-6b0b0800-40c9-11e9-87d4-742a2d492136.jpg)

**Comment by kanasimi** [comment]
請問您使用的是安裝包或者懶人安裝法呢
懶人安裝法似乎沒有這樣的問題
另外有些網站需要等一段時間才能下載完第一個章節

**Comment by app911** [comment]
今天好用了 昨天不知道烦什么抽风^~^

**Comment by kanasimi** [comment]
若是沒有問題的話請關掉此議題
謝謝

**Comment by app911** [comment]
怎么关闭呀 左上的closed点不了啊 我是小白 第一次提问的说~_~

**Comment by kanasimi** [comment]
麻煩請截個全螢幕的圖
