### ISSUE TITLE
manhuagui 漫画柜下载总是报错无法正常下载 希望能修复一下

### ISSUE THREAD

**Issue by xuelainiao** [kanasimi/work_crawler#24]
今天看到漫画柜整理的挺好的，但是使用这个工具无法正常下载，希望老哥能修复一下，特感激~~

**Comment by kanasimi** [comment]
不曉得您直接上 manhuagui 網頁的時候能不能看得到
若是看不到了
代表這個工具抓取的頻率太頻繁
這個問題會在下個版本修復

但是若是您看得到 manhuagui 網頁
再請您回覆一下
這可能是另外一個問題

**Comment by xuelainiao** [comment]
刚测试了另外一个github的程序，针对manhuagui的，https://github.com/stx0821/manhuagui-autodownload   可以使用，老哥看是否能进借鉴一下，整合进来使此软件更强大。

**Comment by kanasimi** [comment]
@xuelainiao 這個工具一樣會遇到封鎖IP的問題
其實出了錯誤之後還會再嘗試
並且這個工具會檢查圖片有沒有完整
不完整就會再次下載

只要出錯就會顯示錯誤訊息
但是會繼續嘗試
最多會嘗試4次

不曉得您的意思是不是
嘗試錯誤的時候不用顯示
直到最後還是沒辦法成功
再顯示的意思呢

**Comment by xuelainiao** [comment]
不是不是，是我使用上面说的链接的工具，使用那个能正常下载，我是赶脚，是不是不是IP封锁问题了呢，或者能更改采集频率更好。
您的软件非常棒，毋容置疑的~^_^~

**Comment by kanasimi** [comment]
哎 這邊可能要先確認一下到底是什麼問題

因為已經將 http 改成 https
這邊沒有辦法重現 #25 畫面裡面提到的問題 (似乎已經解決?)
若是您採用最新版本
依舊錯誤的話
是不是能把錯誤的訊息複製貼來這邊呢

**Comment by xuelainiao** [comment]
我更新了您的代码到本地，然后使用“看漫画/漫画柜” id是 4146，报错如下：
``manhuagui: 2018-07-13T11:04:26.661Z Starting 4146, 儲存至 manhuagui\
[☠][1:45.188] get_URL_node: Get error when retrieving [https://www.manhuagui.com/comic/4146/36485.html]:
[☠][.08] 医龙: Failed to get data of chapter 2
[📝]process_chapter_data: Retry 3/4...
[📝]get_URL_node: Retry 1/4: Error: connect ETIMEDOUT 192.200.110.149:443
[📝]get_URL_node: Retry 1/4: Error: connect ETIMEDOUT 14.49.38.185:443
[📝]get_URL_node: Retry 2/4: Error: connect ETIMEDOUT 192.200.110.149:443
[📝]get_URL_node: Retry 2/4: Error: connect ETIMEDOUT 14.49.38.185:443
[📝]get_URL_node: Retry 3/4: Error: connect ETIMEDOUT 192.200.110.149:443
[📝]get_URL_node: Retry 3/4: Error: connect ETIMEDOUT 14.49.38.185:443
[📝]get_URL_node: Retry 4/4: Error: connect ETIMEDOUT 192.200.110.149:443

**Comment by kanasimi** [comment]
當一次下載上百張相片的時候，就會被封鎖IP。因此改成一個個下載圖像。
