### ISSUE TITLE
取消 アルファポリス 公式漫画 收費章節沒有獲取到任何圖片時的警告

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#241]
﻿#239
好像同時也造成
www.alphapolis.co.jp
偵錯
<img width="804" alt="111" src="https://user-images.githubusercontent.com/42042168/54047672-a36a2d80-4212-11e9-9439-87c6273ba012.PNG">
還是請您改回來好了
不好意思

**Comment by kanasimi** [comment]
雖然是漫畫，但是本章節沒有獲取到任何圖片時的警告為既定策略
您若遇到這樣的網站
可以另外提報議題
