### ISSUE TITLE
能否把覆蓋圖的功能變成下載選項

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#242]
因為不太清楚如何描述此功能,希望下面的圖片能讓您明白我的意思
<img width="755" alt="dfgfgdf" src="https://user-images.githubusercontent.com/42042168/54068273-0ea11780-4286-11e9-8b21-266053e47f21.PNG">

理由
最近大陸漫畫查得比較嚴
所以導致有時候原本的漫畫圖片被重新改過
(以下是舉例,礙於一些理由不方便放出實際例子)
![20161012170524071364072](https://user-images.githubusercontent.com/42042168/54068525-a0aa1f80-4288-11e9-84df-28c1ced6cc05.jpg)

經過修飾的圖可能會比原圖大
因此被覆蓋掉
造成原本的圖消失

但不是每個網站都會和諧圖片
目前我比較有觀察到有發生這樣網站是腾讯漫画,不過別的也可能發生

所以我希望能依照網站的性質個別處理

所以希望您能將覆蓋圖的功能變成下載選項
而不是一定要覆蓋圖

**Comment by kanasimi** [comment]
依照現在的下載機制
當之前已存在完整的圖片時
應該就不會再嘗試下載圖片
您可以更詳細的描述一下是什麼樣的例子嗎

**Comment by gfhghfghfh** [comment]
照下面這張圖來說
https://user-images.githubusercontent.com/42042168/54068273-0ea11780-4286-11e9-8b21-266053e47f21.PNG
意思不就是
如果圖檔比較大就會被覆蓋掉嗎
實際測試也是如此
不過目前(上面的圖片)會發生此狀況好像只有PNG(我不確定)


以下是我的觀察和測試方法
我第一次下載365漫畫的gufeng_shifuyouzailiaowoliaoren
因為有偵錯
所以我重新下載
然後出現了下圖的訊息
https://user-images.githubusercontent.com/42042168/54068273-0ea11780-4286-11e9-8b21-266053e47f21.PNG
雖然我不清楚為甚麼之後下載的33-030和33-13和33-019變小了

但我想說如果第二次下載的圖檔比第一次大
是不是第二次會覆蓋第一次
結果會

測試方法
我用小畫家編輯圖片使得33-030變得比原來的183KB還要小
之後按了重新下載
結果圖片真的被覆蓋掉了

**Comment by gfhghfghfh** [comment]
會發生此狀況好像只有PNG(我不確定)

**Comment by gfhghfghfh** [comment]
另外您說
依照現在的下載機制
當之前已存在完整的圖片時
應該就不會再嘗試下載圖片
那麼
CeJS/application/net/work_crawler.js
的大約4478行
} else if (old_file_status
							&& old_file_status.size > contents.length) {
						library_namespace.log('存在較大的舊檔 ('
								+ old_file_status.size + '>' + contents.length
								+ ')，將不覆蓋：' + image_data.file);

請問為甚麼要這樣設定

**Comment by gfhghfghfh** [comment]
@kanasimi 
<當之前已存在完整的圖片時
應該就不會再嘗試下載圖片>

我偏好這樣的設置
所以能請您
改掉
CeJS/application/net/work_crawler.js
的大約4478行
有可能會覆蓋到舊檔的設定嗎

**Comment by gfhghfghfh** [comment]
如果我打的部分有那裡看不懂
麻煩請跟我說
感謝您的閱讀

**Comment by gfhghfghfh** [comment]
這邊再詳細說明一次
不希望新檔覆蓋舊檔的理由是因為
網站上的圖片可能因為政策而被刪減
如果刪減後的圖檔比刪減前的圖檔大
再加上圖片若是PNG 檔
那麼我以前下載過的刪減前的圖檔就會消失

**Comment by gfhghfghfh** [comment]
如果我打的部分有那裡看不懂
麻煩請跟我說
感謝您的閱讀
如有冒犯請見諒

**Comment by gfhghfghfh** [comment]
@kanasimi 
能否請問您改了甚麼

**Comment by kanasimi** [comment]
可以接受的副檔名/檔案類別

**Comment by gfhghfghfh** [comment]
請問不能把
CeJS/application/net/work_crawler.js
的大約4478行
} else if (old_file_status
&& old_file_status.size > contents.length) {
library_namespace.log('存在較大的舊檔 ('
+ old_file_status.size + '>' + contents.length
+ ')，將不覆蓋：' + image_data.file);

改掉就好嗎
我只是不希望新檔覆蓋到舊檔

如有冒犯請見諒

**Comment by kanasimi** [comment]
因為之前遇到過原先檔案壞了
後來修好
或者網站把檔案改成高質量圖片的情況

**Comment by gfhghfghfh** [comment]
但是覆蓋檔案的功能就我測試好像只有對PNG有效不是嗎
依我上面的方法測試
您遇到的是PNG 檔嗎?

**Comment by gfhghfghfh** [comment]
1.原先檔案壞了後來修好
或者網站把檔案改成高解析度圖片
2.覆蓋到原本為刪減的檔

因為可能的狀況不同所以一開始我是希望您可以把它改成下載選項
依照狀況不同決定是否要使用

**Comment by gfhghfghfh** [comment]
問題三
麻煩您能在多點說明嗎
<img width="536" alt="JHJFHJFHG" src="https://user-images.githubusercontent.com/42042168/54071536-b6c7d800-42a8-11e9-975c-c900955d04b6.PNG">

我不是很懂
不好意思

**Comment by kanasimi** [comment]
當之前下載時發現檔案類別並非預設的檔案，例如預設JPG但取得PNG檔案時，會將副檔名改為所取得圖像實際的格式/副檔名。但是這樣一來可能就會找不到了。因此需要設定acceptable_types。

**Comment by gfhghfghfh** [comment]
預設的檔案是說像dm5.js會預設下載的檔案是jpg?

**Comment by kanasimi** [comment]
```
		// {String}預設的圖片延伸檔名/副檔名/filename extension。
		default_image_extension : 'jpg',
```

**Comment by gfhghfghfh** [comment]
所以說您預設所有漫畫網站的副檔名是jpg?

**Comment by kanasimi** [comment]
yes

**Comment by gfhghfghfh** [comment]
那在您還未加上acceptable_types : 'images',

如果我下載的漫畫裡有圖片是png檔會怎樣

**Comment by kanasimi** [comment]
將會測試是否已經下載過一切可接受的檔案類別。

**Comment by gfhghfghfh** [comment]
所以說還是會把png完整的下載下來？

**Comment by kanasimi** [comment]
yes

**Comment by gfhghfghfh** [comment]
那加上acceptable_types : 'images',
後的差別是？

**Comment by kanasimi** [comment]
將會測試是否已經下載過一切可接受的檔案類別。
當之前已存在完整的圖片時，就不再嘗試下載圖片。

**Comment by gfhghfghfh** [comment]
@kanasimi

♦️加上前
將會測試是否已經下載過一切可接受的檔案類別。
♦️加上之後
當之前已存在完整的圖片時，就不再嘗試下載圖片。

請問是這樣嗎

**Comment by kanasimi** [comment]
♦️加上前
會測試是否已經下載過.jpg。
♦️加上之後
將會測試是否已經下載過一切可接受的檔案類別。
當之前已存在完整的圖片時，就不再嘗試下載圖片。

**Comment by gfhghfghfh** [comment]
@kanasimi
那加上＂前＂，遇到png會怎樣

**Comment by kanasimi** [comment]
找不到JPG檔就會重新下載

**Comment by gfhghfghfh** [comment]
意思是說重新下載png是嗎

然後修改後
就不會再重新下載png

是這樣嗎？

**Comment by kanasimi** [comment]
找不到JPG檔就會重新下載

**Comment by gfhghfghfh** [comment]
找不到JPG檔就會重新下載
這裡的重新下載是指重新下載什麼

**Comment by kanasimi** [comment]
重新下載png圖片

**Comment by gfhghfghfh** [comment]
@kanasimi 
請問您將把覆蓋圖的功能變成下載選項了嗎
我看到您有修改
https://github.com/kanasimi/CeJS/commit/5f19ce9641cc6e866120e4faaba54b0d5a5ae4aa
但是圖形介面好像還是沒有
感謝閱讀

**Comment by kanasimi** [comment]
看起來會用到這個選項的
應該都是需要提報issue的
因此這個選項不會列出來
麻煩請提報issue
謝謝
