### ISSUE TITLE
 能否把覆蓋圖的功能變成圖形介面下載選項

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#245]

**Comment by gfhghfghfh** [comment]
@kanasimi

**Comment by kanasimi** [comment]
Duplicate of #242

**Comment by kanasimi** [comment]
會用到這個選項的
應該都是需要提報issue的
因此這個選項不會列出來
麻煩請在個別網站遇到此情況時提報issue
謝謝

**Comment by gfhghfghfh** [comment]
不好意思
我不太明白您的意思

**Comment by kanasimi** [comment]
例如在騰訊漫畫遇到這個問題的時候
就提報騰訊漫畫作品名稱以及圖片類別出來

**Comment by gfhghfghfh** [comment]
然後圖片就不會被覆蓋掉嗎
儘管修改後的圖檔比較修改前的圖檔大

**Comment by kanasimi** [comment]
設定acceptable_types之後
當之前已存在完整的圖片時，就不再嘗試下載圖片。

**Comment by gfhghfghfh** [comment]
所以此網站就不可能出現https://user-images.githubusercontent.com/42042168/54068273-0ea11780-4286-11e9-8b21-266053e47f21.PNG
是這樣嗎

**Comment by kanasimi** [comment]
應該是這樣
