### ISSUE TITLE
關於覆蓋圖檔的發生時機

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#246]
<img width="177" alt="tddtdrt" src="https://user-images.githubusercontent.com/42042168/54210113-dfa2d400-4519-11e9-944e-13631566bd48.PNG">
<img width="264" alt="擷取" src="https://user-images.githubusercontent.com/42042168/54210127-e3365b00-4519-11e9-9e85-c0316b6d0574.PNG">

**Comment by gfhghfghfh** [comment]
問題一
第二張圖您指的是像下圖這種含有bad名稱檔案沒錯吧
![130468-61-003 bad](https://user-images.githubusercontent.com/42042168/54210208-082ace00-451a-11e9-882e-bb92bbd36845.jpg)

**Comment by gfhghfghfh** [comment]
問題二
照第二張圖意思是後來的圖檔變大就會被覆蓋嗎?
但這樣不就與圖一所說的矛盾了

**Comment by kanasimi** [comment]
1. 包括但不限於
2. 只有在會重新下載檢測檔案的圖片下才具有覆蓋功能

會用到這個選項的
應該都是需要提報issue的
因此這個選項不會列出來
麻煩請在個別網站遇到此情況時提報issue

例如在騰訊漫畫遇到這個問題的時候
就提報騰訊漫畫 **作品名稱** 以及 **圖片類別** 出來
謝謝

**Comment by gfhghfghfh** [comment]
會重新下載檢測檔案的圖片

請問您是指像之前騰訊漫畫的png圖檔
在未加上acceptable_type前
嗎

**Comment by gfhghfghfh** [comment]
只有在會重新下載檢測檔案的圖片下才具有覆蓋功能

請問上文指的＂會重新下載檢測檔案的圖片＂
是指像之前騰訊漫畫的png圖檔
在未加上acceptable_type前
的狀態嗎

**Comment by gfhghfghfh** [comment]
問題四
所以基本上就算有後來有高畫質圖檔出現，仍舊不會覆蓋到原先的完整圖檔
是嗎？

**Comment by gfhghfghfh** [comment]
問題五
您說
每張圖片都要檢核所有可接受的圖片類別
會加大硬碟讀取負擔

您是想告訴我
為什麼不能每個網站都設定acceptable_type
是嗎

**Comment by kanasimi** [comment]
3. 4. 5. yes

每張圖片都要檢查實際存在的圖片檔案。當之前已存在完整的圖片時，就不再嘗試下載圖片。
工作機制：
檢核預設的圖片延伸檔名/副檔名(.default_image_extension)。若是不存在預設的圖片延伸檔名/副檔名，將會檢查所有可以接受的圖片類別(.acceptable_types)。
每張圖片都要檢核所有可接受的圖片類別，會加大硬碟讀取負擔。
會用到.overwrite_old_file這個選項的，應該都是需要提報issue的，因此這個選項不會列出來。麻煩請在個別網站遇到此情況時提報issue，列出作品名稱以及圖片類別，以供這邊確認圖片類別。
只要存在完整無損害的預設圖片類別或是可接受的圖片類別，就不再嘗試下載圖片。否則會重新下載圖片。
當下載的圖片以之前的圖片更大時，就會覆蓋原先的圖片。
若下載的圖片類別並非預設的圖片類別(.default_image_extension)，例如預設JPG但取得PNG檔案時，會將副檔名改為所取得圖像實際的格式/副檔名。這時需要設定.acceptable_types才能找得到圖片。

**Comment by gfhghfghfh** [comment]
問題六
不好意思再確認一次

**只要存在完整無損害的預設圖片類別或是可接受的圖片類別，就不再嘗試下載圖片。否則會重新下載圖片。
當下載的圖片以之前的圖片更大時，就會覆蓋原先的圖片。**


當下載的圖片比之前的圖片更大時，就會覆蓋原先的圖片。
上述的情況是**不成立於**
存在完整無損害的預設圖片類別或是可接受的圖片類別

只成立於非預設的圖片和含有bad 名稱的檔案嗎

問題七
<img width="519" alt="擷取" src="https://user-images.githubusercontent.com/42042168/54265977-6c4ca100-45b1-11e9-854d-70083cc6350e.PNG">

黃色的部分是接續2的
而不是接續1的
是嗎

**Comment by kanasimi** [comment]
只要存在完整無損害的預設圖片類別或是可接受的圖片類別，就不再嘗試下載圖片。

**Comment by gfhghfghfh** [comment]
<img width="410" alt="擷取" src="https://user-images.githubusercontent.com/42042168/54266433-568bab80-45b2-11e9-8907-48b87083c56b.PNG">
所以黃色的部分是在說明紅色(也就是否則的情況下)的內容嗎

**Comment by kanasimi** [comment]
yes

**Comment by gfhghfghfh** [comment]
謝謝您的耐心說明
這邊本來就偏好完整的圖片**不會**被覆蓋
感謝您的設置

**Comment by gfhghfghfh** [comment]
@kanasimi 
不好意思,真的最後再問一次
<img width="543" alt="擷取" src="https://user-images.githubusercontent.com/42042168/54267949-2db8e580-45b5-11e9-9bbe-75203a0e01c7.PNG">

黃色的部分是**### 不成立**於1(完整無損害的預設圖片類別或是可接受的圖片)的情況下
是吧

**Comment by kanasimi** [comment]
yes
只要存在完整無損害的預設圖片類別或是可接受的圖片類別，就不再嘗試下載圖片。直接跳過不再處理這張圖片。

**Comment by gfhghfghfh** [comment]
再次感謝您
