### ISSUE TITLE
請讓知音漫客設定acceptable_type

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#247]
理由
這個網站圖片好像也有png檔

**Comment by kanasimi** [comment]
麻煩請舉出作品名稱

**Comment by gfhghfghfh** [comment]
請問為什麼會需要舉出作品名稱

**Comment by kanasimi** [comment]
#246 
每張圖片都要檢查實際存在的圖片檔案。當之前已存在完整的圖片時，就不再嘗試下載圖片。
工作機制：
檢核預設的圖片延伸檔名/副檔名(.default_image_extension)。若是不存在預設的圖片延伸檔名/副檔名，將會檢查所有可以接受的圖片類別(.acceptable_types)。
每張圖片都要檢核所有可接受的圖片類別，會加大硬碟讀取負擔。
會用到.overwrite_old_file這個選項的，應該都是需要提報issue的，因此這個選項不會列出來。麻煩請在個別網站遇到此情況時提報issue，列出作品名稱以及圖片類別，以供這邊確認圖片類別。
只要存在完整無損害的預設圖片類別或是可接受的圖片類別，就不再嘗試下載圖片。否則會重新下載圖片。
當下載的圖片以之前的圖片更大時，就會覆蓋原先的圖片。
若下載的圖片類別並非預設的圖片類別(.default_image_extension)，例如預設JPG但取得PNG檔案時，會將副檔名改為所取得圖像實際的格式/副檔名。這時需要設定.acceptable_types才能找得到圖片。

**Comment by gfhghfghfh** [comment]
好的
那麻煩您等個幾天
因為檔案目前不在身邊
無法確認是哪個漫畫
只知道有png

**Comment by gfhghfghfh** [comment]
93
可在93-137-011發現
也有別的圖是png
