### ISSUE TITLE
當出現< 章節數量??  比將開始/接續之下載章節編號 ??還少，或許因為章節有經過重整，或者上次下載時中途增刪過章節>時卡在那

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#248]
<img width="560" alt="擷取" src="https://user-images.githubusercontent.com/42042168/54362145-646d2980-46a3-11e9-8004-81f8d8ee18e7.PNG">

然後就一直卡在那
附上偵錯訊息
<img width="249" alt="tyjytjjt" src="https://user-images.githubusercontent.com/42042168/54362320-b1e99680-46a3-11e9-8b5f-60a6f33e70e8.PNG">

**Comment by gfhghfghfh** [comment]
<img width="249" alt="tyjytjjt" src="https://user-images.githubusercontent.com/42042168/54362320-b1e99680-46a3-11e9-8b5f-60a6f33e70e8.PNG">

**Comment by kanasimi** [comment]
似乎無法重現...
您能夠描述必然會出現這種情況的操作流程嗎

**Comment by gfhghfghfh** [comment]
原先忘記把章節數87換成1（87是用來下載別的漫畫的）
結果發現下載會卡住不動

**Comment by kanasimi** [comment]
所以您的操作流程是...

**Comment by gfhghfghfh** [comment]
一開始忘記把87改成1
然後按了下載623291這個漫畫
出現訊息或許因為章節有經過重整，或者上次下載時中途增刪過章節
結果發現卡在那

**Comment by gfhghfghfh** [comment]
然後我擔心如果遇到真的增減章節的情況
也會卡住
因此回報這個議題

**Comment by kanasimi** [comment]
您在前一個作品設定了start_chapter嗎?

**Comment by gfhghfghfh** [comment]
是的
如果遇到真的增減章節的情況不會卡住

只是單純因爲我把章節數改成比原漫畫章節數多才會遇到卡住的話

還請您不用做修改關閉議題即可

**Comment by gfhghfghfh** [comment]
例
沒下載過這漫畫
但卻設定章節數大於此漫畫的章節數
所以出現章節數量?? 比將開始/接續之下載章節編號 ??還少
然後下載卡住

**Comment by gfhghfghfh** [comment]
@kanasimi 
<img width="944" alt="擷取" src="https://user-images.githubusercontent.com/42042168/54432785-246e7b00-4765-11e9-93c3-4414cb3677e4.PNG">
<img width="250" alt="擷取" src="https://user-images.githubusercontent.com/42042168/54432820-394b0e80-4765-11e9-81df-fd8d261aa554.PNG">


請問現在這樣正常嗎

**Comment by gfhghfghfh** [comment]
@kanasimi 
還是跟上圖一樣的情況

**Comment by kanasimi** [comment]
應該有不一樣的訊息了
麻煩請貼一下
謝謝

**Comment by gfhghfghfh** [comment]
@kanasimi 
<img width="250" alt="擷取" src="https://user-images.githubusercontent.com/42042168/54471247-ea4abb00-47f0-11e9-8811-e579674a4c6e.PNG">

**Comment by kanasimi** [comment]
上面訊息列的部分是?

**Comment by gfhghfghfh** [comment]
偵錯訊息的部分

**Comment by gfhghfghfh** [comment]
<img width="960" alt="擷取" src="https://user-images.githubusercontent.com/42042168/54471279-7a890000-47f1-11e9-8ec0-5ce5e4d53b08.PNG">

**Comment by kanasimi** [comment]
既然您設定至87張開始下載
那麼這個結果是正常的

若是想要重新下載
那麼您必須要改回start_chapter這個設定

**Comment by gfhghfghfh** [comment]
那如過是真的遇到增減章節的情況會正常運作嗎

**Comment by kanasimi** [comment]
如訊息所述
應該會重新下載
