### ISSUE TITLE
想請問fix: node.js 在讀取 "/D:/"... 這一種檔案時會轉換成 "/D:/D:/"... 是修復了甚麼

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#249]
﻿https://github.com/kanasimi/CeJS/commit/7ff9fb15d2c673fd1a38e0c6d711f68ab2f63f13
想請問fix: node.js 在讀取 "/D:/"... 這一種檔案時會轉換成 "/D:/D:/"... 是
**從甚麼
修復成了甚麼**

**Comment by gfhghfghfh** [comment]
不好意思
還是沒有很懂
從甚麼
修復成了甚麼

**Comment by kanasimi** [comment]
這您只有在某些環境使用安裝包 才會遇到
我想就您的狀況來說刻意忽略這個bug

**Comment by gfhghfghfh** [comment]
所以懶人安裝法不會有這個bug?

**Comment by kanasimi** [comment]
yes
