### ISSUE TITLE
漫画柜网站无法下载

### ISSUE THREAD

**Issue by hjp070928** [kanasimi/work_crawler#25]
最近漫画柜网站给自己加密访问了，所以普通的http不管用了，现在变成https了，以前一直在漫画柜里扒漫画，最近改了也没法下载了

**Comment by kanasimi** [comment]
不曉得您直接上 manhuagui 網頁的時候能不能看得到
若是看不到了
代表這個工具抓取的頻率太頻繁
這個問題已經在最新的版本修復

但是若是您看得到 manhuagui 網頁
再請您回覆一下
這可能是另外一個問題

若是有錯誤訊息也麻煩您貼出來
謝謝

**Comment by xuelainiao** [comment]
![bjiv1yct87fu vzonntw](https://user-images.githubusercontent.com/3192890/42667021-495d5cde-867b-11e8-9c16-bba70619d9a8.png)
请查看一下这个截图，网站是能打开的，想下载漫画的页面也能打开，只是上来就有报错，谢谢您~

**Comment by kanasimi** [comment]
@xuelainiao 這個工具一樣會遇到封鎖IP的問題
其實出了錯誤之後還會再嘗試
並且這個工具會檢查圖片有沒有完整
不完整就會再次下載

只要出錯就會顯示錯誤訊息
但是會繼續嘗試
最多會嘗試4次

不曉得您的意思是不是
嘗試錯誤的時候不用顯示
直到最後還是沒辦法成功
再顯示的意思呢
