### ISSUE TITLE
https://comic.pixiv.net/ 無法下載

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#254]
﻿

* **Version**: 
* **Interface**:

**Comment by kanasimi** [comment]
麻煩描述得詳細點
包括作品名稱以及錯誤訊息

**Comment by gfhghfghfh** [comment]
好像都不能下載，然後照網址去找圖看都是404，可能是新的防止下載的機制？，請問有辦法解決嗎
