### ISSUE TITLE
請問怎麼處理

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#255]
<img width="960" alt="擷取" src="https://user-images.githubusercontent.com/42042168/54473084-2ccec080-480e-11e9-83bf-5be5fff2179e.PNG">
﻿

**Comment by kanasimi** [comment]
關掉偵錯工具應該就能執行了吧

**Comment by gfhghfghfh** [comment]
所以是不能一直開著嗎

**Comment by kanasimi** [comment]
倒不是這樣
是因為設定了中斷點

https://dotblogs.com.tw/kevinya/2016/06/22/171608

**Comment by gfhghfghfh** [comment]
所以按了右上角的叉叉
<img width="983" alt="擷取" src="https://user-images.githubusercontent.com/42042168/54473534-01e76b00-4814-11e9-8c29-a7f02247303c.PNG">

然後程式就會繼續運行了
不會損害到甚麼吧
像是圖檔

**Comment by kanasimi** [comment]
除非正在讀取網路資訊的時候被中斷
否則應不會出問題

**Comment by gfhghfghfh** [comment]
那如果是那個時候被中斷
受影響的只會有624102(上面下載進行到一半的漫畫）
是這樣嗎

**Comment by kanasimi** [comment]
正在讀取網路資訊的時候被中斷
會造成讀取逾時
不過這時候應該會出錯誤訊息

**Comment by gfhghfghfh** [comment]
那受影響的只會有624102(最上面下載進行到一半的漫畫）
是這樣嗎

**Comment by kanasimi** [comment]
出錯誤訊息?
