### ISSUE TITLE
下载时候出现错误提示

### ISSUE THREAD

**Issue by ha7rock** [kanasimi/work_crawler#265]
您好，

已透过执行updater更新至最新版。

下载manhuadb的某作品时，出现如下错误：

> 工具檔似乎沒有設定應設定的 `work_data.chapter_list.part_NO`?

求解何故?

谢谢！

**Comment by kanasimi** [comment]
不曉得您下載的是哪個網站的哪個作品呢?
若是可以的話能夠把錯誤訊息也一起貼出來嗎?

**Comment by kanasimi** [comment]
請提供更清楚的訊息
若有需要再重開此議題
謝謝
