### ISSUE TITLE
youngaceup下載白屏

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#268]
<img width="207" alt="gfdgfgdfgdf" src="https://user-images.githubusercontent.com/42042168/55672806-e7b02280-58d1-11e9-9c79-e08b76d515ac.PNG">

**Comment by gfhghfghfh** [comment]
以下是當時下載的書籤
1000117
1000081
1000049
1000104
1000068
1000074
1000084
1000012
1000080
1000029
1000015
1000010
1000088
1000112
1000072
1000073
1000075
1000071
1000046
1000099
1000052
1000100

**Comment by kanasimi** [comment]
請問這個問題是每次下載都會出現
或者是偶爾出現
另外出問題的時候下載到哪個作品呢?

**Comment by gfhghfghfh** [comment]
倒數第二和第一

**Comment by gfhghfghfh** [comment]
好像不是每次
但常常會

**Comment by kanasimi** [comment]
請問是哪個網站呢

**Comment by gfhghfghfh** [comment]
標題寫的youngaceup(ヤングエースUP)
會發生在使用這個網站時
因為突然白屏
所以我只能提供當時下載狀況

**Comment by kanasimi** [comment]
通常發生在用很久
或者剛開啟程式的時候呢?

**Comment by gfhghfghfh** [comment]
兩個都有，所以覺得應該與使用時間無關
這邊在持續觀察好了

**Comment by kanasimi** [comment]
通常發生在一次下載很多網站嗎
或者一次下載一個網站也會發生呢?

**Comment by gfhghfghfh** [comment]
這邊不會並行下載多個網站
所以是只有下載youngaceup(ヤングエースUP)
有時候會發生白屏

**Comment by kanasimi** [comment]
還是無法重現
要麻煩您觀察一下可能是什麼樣的情況才會出現這種問題了

**Comment by gfhghfghfh** [comment]
好的

**Comment by kanasimi** [comment]
請提供更精確的訊息
若有需要再重開此議題
謝謝
