### ISSUE TITLE
快看漫畫下載失敗

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#272]
顯示
process_work_data: 無法取得/未設定作品標題

**Comment by kanasimi** [comment]
不曉得您下載的是哪個網站的哪個作品呢?
若是可以的話能夠把更詳細(包括前後)的錯誤訊息也一起貼出來嗎?

**Comment by gfhghfghfh** [comment]
都失敗的樣子(貌似改版?
