### ISSUE TITLE
親親漫畫下載失敗

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#274]

**Comment by gfhghfghfh** [comment]
﻿
<img width="614" alt="擷取" src="https://user-images.githubusercontent.com/42042168/56215520-68b9a780-6092-11e9-9ea7-d78a6b215182.PNG">
每張圖都下載不下來
但從上面的網址取圖
圖片都是正常的

作品id 18668
下載別的似乎情況相同

**Comment by kanasimi** [comment]
親親漫畫拒絕服務的標準有些難以拿捏。恐怕還需要再一段時間的測試...

**Comment by gfhghfghfh** [comment]
好的，那就麻煩您了

**Comment by kanasimi** [comment]
好像又測不出來了
多執行幾遍好像就有機會下載成功?

**Comment by gfhghfghfh** [comment]
議題可以再開個幾天，確認之後再關掉嗎

**Comment by kanasimi** [comment]
OK. 也請麻煩回報您的測試結果

**Comment by gfhghfghfh** [comment]
正常
