### ISSUE TITLE
汗汗酷漫 下載中出現複數問題

### ISSUE THREAD

**Issue by myocytebd** [kanasimi/work_crawler#275]
* **Version**: 懶人安裝法
* **Interface**: 圖形介面

請描述出了什麼問題
A. [影響度低]下載幾集后會出現timeout
B. [影響度中]下載任務無法取消和停止
C. [影響度中]cache目錄下的内容影響到重新下載

造成問題的操作步驟
1. 從 汗汗酷漫 下載任意漫畫，例如"舌尖上的百合"
2. 下載數集后，出現[問題A]。類似這樣：
```
[📝]29/47 [0029 029集] 21 images.
[ℹ][31.817s] get_URL_node: timeout 30s [http://www.hhimm.com/cool156859/12.html?s=11]
[☠][.5] get_URL_cache_node.cache: Error to get URL: [http://www.hhimm.com/cool156859/12.html?s=11].
```
3. [問題B]嘗試停止或者取消下載任務，明顯沒有相應。只有如下一行log。
```
[ℹ][6:37.844] hhcool: 準備設定暫停下載作業
```
4. 因此，只能進行reload。
5. Reload后暴露出[問題C]。
- 直接重新下載，仍然在同樣的地方timeout，失敗率10/10。
- 刪除cache目錄下所有文件，重新下載立即成功，復現率8/8。

希望的行爲：
B. 下載任務可以取消和停止。
C. 下載任務開始和停止時自動清除cache。
A. 取消或者調整cache策略？
    目前的做法似乎是在下載圖片前一次性下載所有html？這個方式可能觸發了服務器的防禦機制。例如，當一集是單行本大小，我這裡幾乎不能成功下載，總是在第170+個html出現timeout。

**Comment by gfhghfghfh** [comment]
關於取消跟停止的問題
那個如果按了取消跟停止
程式會等到正在下載的章節下載完才會停止

**Comment by kanasimi** [comment]
感謝您回報錯誤
您的報告真詳細 😃
