### ISSUE TITLE
土豪漫畫換位置下載問題

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#278]
當我移動檔案存放位置時
也改了圖形介面的檔案下載位置
但卻發生檔案無法寫入的錯誤

**Comment by kanasimi** [comment]
請貼上錯誤訊息或者執行時的畫面，謝謝。

**Comment by gfhghfghfh** [comment]
我將1.檔案位置和2.圖形介面的下載位置從
D:\tohomh\改成D:\qazwsx\tohomh\

<img width="880" alt="擷取" src="https://user-images.githubusercontent.com/42042168/56865102-c340f500-69fc-11e9-8f89-cdb8334692a0.PNG">

**Comment by gfhghfghfh** [comment]
我將檔案位置和
<img width="576" alt="擷取" src="https://user-images.githubusercontent.com/42042168/56865134-0c914480-69fd-11e9-8453-6e37b0236536.PNG">

從D:\tohomh\改成D:\qazwsx\tohomh\

<img width="880" alt="擷取" src="https://user-images.githubusercontent.com/42042168/56865102-c340f500-69fc-11e9-8f89-cdb8334692a0.PNG">

**Comment by kanasimi** [comment]
請刪除 \tohomh\作品目錄\ 下的 作品id.json 就可以了
