### ISSUE TITLE
MAGCOMI下載卡住

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#281]

**Comment by gfhghfghfh** [comment]
<img width="720" alt="擷取HGFHGHFG" src="https://user-images.githubusercontent.com/42042168/57175791-88b6dc80-6e82-11e9-9e3d-516241f15a3e.PNG">
<img width="857" alt="FGDFGDFGDF" src="https://user-images.githubusercontent.com/42042168/57175792-8a80a000-6e82-11e9-9ff3-de1ca2858e4f.PNG">

**Comment by kanasimi** [comment]
這邊測試正常
不曉得您在什麼樣的情況會遇到這個問題?

**Comment by gfhghfghfh** [comment]
多下載一點
可能就能試到

**Comment by kanasimi** [comment]
這邊還是沒有測試出這樣的錯誤
或許您等一段時間就能正常下載了?

**Comment by gfhghfghfh** [comment]
這邊是希望
能不能重試4次沒成功
就在進度條顯示錯誤
而不是卡在那

**Comment by gfhghfghfh** [comment]
顯示Can not get chapter count! 或許作品已被刪除或者網站改版了?

**Comment by kanasimi** [comment]
> 這邊是希望
> 能不能重試4次沒成功
> 就在進度條顯示錯誤
> 而不是卡在那

了解了
您可以一開始就提出建議
這邊能夠比較會做出應對
