### ISSUE TITLE
亲亲漫画

### ISSUE THREAD

**Issue by fenger7** [kanasimi/work_crawler#286]
我想请问下，亲亲漫画使用aes加密，那个密码的数据你是怎么得到的呢？

**Comment by kanasimi** [comment]
See https://github.com/kanasimi/CeJS/blob/master/application/net/work_crawler/SinMH.js#L360

**Comment by fenger7** [comment]
感谢你的回复，谢谢！参考文件中的密码已经过期了。

**Comment by fenger7** [comment]
亲亲漫画源网站对js文件进行了混淆，而且还增加了debugger反调试功能。由于我对js反调试这块不熟，想请教下你该怎么做呢？

**Comment by kanasimi** [comment]
這邊現在完全看不到圖片
等到圖片顯示正常之後再來看看吧

**Comment by gfhghfghfh** [comment]
@kanasimi 貌似恢復了
