### ISSUE TITLE
關於無法寫入圖像檔案

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#287]

**Comment by gfhghfghfh** [comment]
❶ 您在https://github.com/kanasimi/work_crawler/issues/278
是教我刪除 \tohomh\作品目錄\ 下的 作品id.json 

❷但
https://github.com/kanasimi/CeJS/blob/1670642f6883dcf4954b6b0a79c337b487cf6c79/application/net/work_crawler.js
寫的方法是
若您之前曾經下載過本作品的話，請封存原有作品目錄
或將作品資訊 cache 檔（作品目錄下的 作品id.json）改名之後嘗試全新下載。


問題一
作品資訊 cache 檔（作品目錄下的 作品id.json）改名之後嘗試全新下載
是因為要讓程式不去讀取原先的 cache 檔
但仍保留原先的 cache 檔嗎

問題二
①作品資訊 cache 檔（作品目錄下的 作品id.json）改名之後嘗試全新下載
②刪除 \tohomh\作品目錄\ 下的 作品id.json

①和②是只差在
①沒有保留原先的 cache 檔嗎






問題三
封存原有作品目錄
是等同讓程式從無
去重新下載作品嗎

**Comment by kanasimi** [comment]
❓問題一
yes

❓問題二
yes

❓問題三
等同讓程式重新下載作品

**Comment by gfhghfghfh** [comment]
所以基本上當遇到無法寫入圖像檔案
直接刪除
 \漫畫網站\作品目錄\ 下的 作品id.json
就可以了嗎

**Comment by kanasimi** [comment]
移動檔案存放位置時
卻發生檔案無法寫入的錯誤
...yes
