### ISSUE TITLE
問題反饋

### ISSUE THREAD

**Issue by YukariMurasakibara** [kanasimi/work_crawler#290]
* **Version**: 安裝包work_crawler.Setup.2.0.0 
* **Interface**: 用的安裝包，應該屬於圖形界面？

問題描述：
按照您的要求，下載了7Zip、Node、CeJS-master、work_crawler-master及安裝包本體，並成功安裝，但是打開並運行軟件時就出現
![image](https://user-images.githubusercontent.com/50821483/58009497-2ec04300-7b21-11e9-8a13-572829daaab7.png)，請問是什麽問題，應該如何解決？小白，非常感謝！

![image](https://user-images.githubusercontent.com/50821483/58009611-6929e000-7b21-11e9-894c-aec2d6820d10.png)

**Comment by kanasimi** [comment]
做了點修正
麻煩您再試試看

**Comment by YukariMurasakibara** [comment]
重開軟件後還是如此，是需要我重新安裝嗎？

**Comment by kanasimi** [comment]
yes.
請手動執行 work_crawler.updater.js

**Comment by YukariMurasakibara** [comment]
手動運行後的問題
![image](https://user-images.githubusercontent.com/50821483/58010557-2c5ee880-7b23-11e9-8dfb-f4a51e067040.png)

重裝軟件重開後的問題
![image](https://user-images.githubusercontent.com/50821483/58010621-4a2c4d80-7b23-11e9-9c98-e3af41661dd6.png)

_(:з」∠)_我是不是和這個神器無緣了呢

**Comment by kanasimi** [comment]
work_crawler.updater.js 這支更新程式不能直接點擊執行
必須採用[Lazy installation 懶人安裝法](https://github.com/kanasimi/work_crawler#lazy-installation-%E6%87%B6%E4%BA%BA%E5%AE%89%E8%A3%9D%E6%B3%95)的第三點方法（在命令列介面下執行安裝檔 work_crawler.updater.js。）
麻煩您再試試看

**Comment by YukariMurasakibara** [comment]
![image](https://user-images.githubusercontent.com/50821483/58012780-d476b080-7b27-11e9-895e-f570daa4d0d4.png)
抱歉，臨時有工作回復晚了。我個人尋找壹部古早漫畫書，網上有資源的站不多，現在很多漫畫工具都不能用了，到處檢索信息，正好在國內的吾愛破解論壇看到分享您開發的軟件的鏈接，就壹路爬了過來^^

**Comment by kanasimi** [comment]
請執行
```
node work_crawler.updater.js
```
試試

**Comment by YukariMurasakibara** [comment]
腳本開始在執行了，我等它執行完畢再看看^^，感謝您的回復，問題解決後會來repo的^^

**Comment by YukariMurasakibara** [comment]
![image](https://user-images.githubusercontent.com/50821483/58015364-a5633d80-7b2d-11e9-8035-efcf183121cd.png)
![image](https://user-images.githubusercontent.com/50821483/58015410-bdd35800-7b2d-11e9-9391-dcec266068f6.png)
執行完畢後重開軟件還是之前那樣子……

**Comment by kanasimi** [comment]
這邊重新釐清了一下問題
麻煩您再更新一次
謝謝

**Comment by YukariMurasakibara** [comment]
更新完畢，開始運行軟件啦！！非常感謝您！
就是顯示了很久下載任務初始化中有些著急
