### ISSUE TITLE
pixivcomic 遇到大量下載時會白屏以及進度條偵錯問題

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#291]
請您先看完❓報錯1和❓報錯2
再開始處理

感謝

**Comment by gfhghfghfh** [comment]
﻿因為之前文件夾名稱出了問題

所以我全部從新下載
但會發生白屏
下圖是白屏前的最後看到的樣子
<img width="788" alt="1" src="https://user-images.githubusercontent.com/42042168/58161044-21868e00-7cb2-11e9-8db4-486f2c0b261f.PNG">

下面是當時下載的作品
[favorite.txt](https://github.com/kanasimi/work_crawler/files/3206517/favorite.txt)

**Comment by gfhghfghfh** [comment]
❓報錯2
<img width="945" alt="1" src="https://user-images.githubusercontent.com/42042168/58162052-0583ec00-7cb4-11e9-8322-457503c1ec3f.PNG">

**Comment by gfhghfghfh** [comment]
@kanasimi 還是會白屏

**Comment by kanasimi** [comment]
麻煩在關掉調試功能的情況下執行
試試看是否還是會白屏

**Comment by gfhghfghfh** [comment]
@kanasimi 我沒有開(๑•́ ₃ •̀๑)

**Comment by kanasimi** [comment]
有個可能是記憶體使用過多
但是這邊試不出來

**Comment by gfhghfghfh** [comment]
我有限制訊息數
所以那邊可以完全下載都不白屏嗎

**Comment by kanasimi** [comment]
yes

**Comment by gfhghfghfh** [comment]
@kanasimi 是全部重新下載嗎(從無到有

**Comment by kanasimi** [comment]
這個怕是對網站負擔太重...
