### ISSUE TITLE
pixivcomic日文字編號顯示問題

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#292]

**Comment by gfhghfghfh** [comment]
<img width="228" alt="擷取" src="https://user-images.githubusercontent.com/42042168/58247394-2750a200-7d8c-11e9-9b2a-b12395e24623.PNG">

**Comment by gfhghfghfh** [comment]
想請問一下

// 漆 : '柒',
// 什 : '拾',

為什麼這邊是用成註解

**Comment by kanasimi** [comment]
去除常用字以防 false positive
