### ISSUE TITLE
请求docker版本

### ISSUE THREAD

**Issue by ha7rock** [kanasimi/work_crawler#295]
请问作者大大是否考虑制作支持docker的版本呢？

**Comment by kanasimi** [comment]
@see https://www.electron.build/multi-platform-build#docker

**Comment by kanasimi** [comment]
It seems too large.
https://hub.docker.com/r/kanasimi/work_crawler

**Comment by ha7rock** [comment]
太感谢了，我来试试看，辛苦K桑
