### ISSUE TITLE
可以請您幫我再增加 Rocaca 嗎

### ISSUE THREAD

**Issue by sandycheng1** [kanasimi/work_crawler#30]
http://www.rocaca.com

**Comment by kanasimi** [comment]
這個網站架構比較獨特
寫起來費時間
有此網站獨有的作品嗎?

**Comment by sandycheng1** [comment]
有的
他跟原本我之前給的mangago一樣
某類型的部分較豐富
需要直接說是哪類型嗎(這有點害羞

**Comment by kanasimi** [comment]
這個網站編碼比較複雜
得要等有時間了

**Comment by sandycheng1** [comment]
好的
謝謝您的告知

**Comment by sandycheng1** [comment]
謝謝您
可以請問一下
![2](https://user-images.githubusercontent.com/41149813/43014462-cd9e4950-8c7e-11e8-9289-47c172c0d57c.PNG)
這個狀況有辦法解決嗎
圖案亂了
http://www.rocaca.com/manga/the_last_zombie/
