### ISSUE TITLE
請問關於  刪除已存在的作品資料 cache

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#302]

**Comment by gfhghfghfh** [comment]
﻿https://github.com/kanasimi/CeJS/commit/d9602225269efc1a80c062761426b377b8a55ad4

2500行所提到  刪除已存在的作品資料 cache

請問是用於何種情況下

**Comment by kanasimi** [comment]
明確指定 .preserve_work_page = false

**Comment by gfhghfghfh** [comment]
請問有直接應用的例子嗎（我尚未了解程式太深
感謝您

**Comment by kanasimi** [comment]
您可以試試設定 preserve_work_page = true
會保留作品資料 cache

**Comment by gfhghfghfh** [comment]
請問作品資料 cache
是指
<img width="233" alt="擷取" src="https://user-images.githubusercontent.com/42042168/59088705-d1a6f880-893a-11e9-8a56-3fef0ac55741.PNG">

**Comment by kanasimi** [comment]
應該是了

**Comment by gfhghfghfh** [comment]
這邊看不出差別?
請問是在何種預設情況下發生
不太清楚為甚麼要刪除已存在的作品資料

**Comment by kanasimi** [comment]
一般人不會需要留存作品資訊

**Comment by gfhghfghfh** [comment]
那個json不是用來也用來記錄下載嗎，所以不太懂為什麼要刪
還是我哪裡誤會了

**Comment by kanasimi** [comment]
...不是json檔
應該是網頁檔
