### ISSUE TITLE
古風某漫畫下載出錯

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#303]

**Comment by gfhghfghfh** [comment]
id  wodeshashounanyou
<img width="960" alt="擷取" src="https://user-images.githubusercontent.com/42042168/59085496-61e04000-8931-11e9-9a09-873eb70a6562.PNG">

**Comment by kanasimi** [comment]
網站似乎掛了

**Comment by gfhghfghfh** [comment]
好像沒有全部

上面那個網址是網站沒掛時還是有缺的部分
會造成後續下載無法進行
您可以嘗試從68開始下載(就是那章節)

**Comment by kanasimi** [comment]
可以列出您發現出問題的作品標題嗎

**Comment by gfhghfghfh** [comment]
圖片上面的給的id行嗎

**Comment by kanasimi** [comment]
麻煩請列出文字 謝謝

**Comment by gfhghfghfh** [comment]
我是指圖片上方的id

我的杀手男友

**Comment by gfhghfghfh** [comment]
會造成停止的章節數是68

https://www.gufengmh8.com/manhua/wodeshashounanyou/742494.html

**Comment by gfhghfghfh** [comment]
感謝
