### ISSUE TITLE
請問能否指導如何修改可預測的圖片網址序列的範例,使其符合另一可預測的圖片網址

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#305]
﻿
https://toon.bookcube.com/toon/viewer/image.asp?webtoon_num=150087&split_num=001&file_idx=1
<img width="897" alt="59126141-e74a0b80-8996-11e9-97ad-07cfa24c4c2e" src="https://user-images.githubusercontent.com/42042168/59126753-6724a580-8998-11e9-8989-203eb4872c58.png">

我更動https://github.com/kanasimi/work_crawler/blob/033b7792cdb1758791fb03515364b3117b5b0475/comic.cmn-Hans-CN/mrblue.js

<img width="782" alt="59126516-dbab1480-8997-11e9-9bf8-9f9bd90212f8" src="https://user-images.githubusercontent.com/42042168/59126769-70157700-8998-11e9-87a4-a37257acad01.png">

之後不太清楚如何改動
請問可以給予協助嗎
拜託您了
感謝

**Comment by kanasimi** [comment]
增加了點註解
您再參考看看

**Comment by gfhghfghfh** [comment]
[mrblue.zip](https://github.com/kanasimi/work_crawler/files/3268011/mrblue.zip)

這邊改完**https://toon.bookcube.com/toon/viewer/image.asp?webtoon_num=150087&split_num=**
的部分

無法成功改好這邊**001&file_idx=1**

**Comment by gfhghfghfh** [comment]
試著改動黃色的部分
但是沒有成功
<img width="592" alt="擷取" src="https://user-images.githubusercontent.com/42042168/59141065-fbaef800-89d8-11e9-96c2-f249d6889c4d.PNG">

**Comment by gfhghfghfh** [comment]
① /1/001.jpg
②001&file_idx=1

①的章節數型態為1   
②的章節數型態為001


①某章節圖片序列為001
②某章節圖片序列為1


此外試著將**&file_idx=**放入
但都無法成功

**Comment by kanasimi** [comment]
您需要一定的基礎程式訓練來修改程式碼

這邊只提供引導
不會維護這個網站

**Comment by gfhghfghfh** [comment]
好的,感謝您

**Comment by gfhghfghfh** [comment]
@kanasimi 
能請您將 base_URL的部分改成 https://toon.bookcube.com/ 嗎

還有加上MIN_LENGTH : 6000,

麻煩您了
感謝
