### ISSUE TITLE
無法按照需求更改recheck

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#307]
懶人安裝法: 圖形介面,

點擊recheck無反應

**Comment by gfhghfghfh** [comment]
@kanasimi 
請問保留空格是必須的嗎
<img width="322" alt="擷取" src="https://user-images.githubusercontent.com/42042168/59159515-432ea480-8afd-11e9-890e-25a1b8ced809.PNG">

希望可以跟之前一樣沒有空格

**Comment by kanasimi** [comment]
必須的
可能包含字串值

**Comment by gfhghfghfh** [comment]
@kanasimi 
點擊的時候
要先跳至另一網站再回來
空格裡面的字才會改變
有些影響判讀

能否改成不用先跳至別的網站
空格的內容就會變化

**Comment by gfhghfghfh** [comment]
@kanasimi 有些網站的初始狀態是顯示
<img width="355" alt="擷取" src="https://user-images.githubusercontent.com/42042168/59356581-b3d2fc80-8d5b-11e9-8bf2-4f83a0be0b9a.PNG">
請問屬正常現象嗎

**Comment by kanasimi** [comment]
yes
