### ISSUE TITLE
English version + drag and drop function 

### ISSUE THREAD

**Issue by Ha5yA** [kanasimi/work_crawler#308]
Hello i came across this,
would there be an English version ?
are you on discord ?
google translate
你好，我遇到过这个，
会有英文版吗？

在嘛 discord?

**Comment by kanasimi** [comment]
Hi.
Thank you for using this tool.
We have English version as you see in the introduction page.
![支援不同語系](https://lh3.googleusercontent.com/-EOQgYAap6YPw7iKQRlvlA4-fr37-4SddypCw44H2uhgpgmQ6FtpjjJ-qg_gJHbwfNRn8GNvvoYqE46yIQwg3xOVzR-5mzfqX8tPhOM06iYdF2gXOuIddcN5rNlCMhmmIxYye7SX8g=w2400)

And we translate the tool on  Google Docs.
You may get the link on #185.

**Comment by Ha5yA** [comment]
Thank you...
Is it possible for me to request additional sites ?

**Comment by kanasimi** [comment]
Sure!
But I am sorry that for English or Korean sites, using Free Manga Downloader is much suitable. For the deficiency of time, it is hard to maintain the tools instantly.

**Comment by Ha5yA** [comment]
I see,
One more query...
In free manga downloader , we can drop the link and it will fetch title page and available chapters to download...
Would it be possible to have a similar feature in this wonderful software ?
As majority button and sites check box being in Chinese it's next impossible for someone who doesn't know to read Chinese to download something ... As in its pretty hard to select the source and put id cause we would not know the Chinese name of it..
Thank you

**Comment by kanasimi** [comment]
You may also paste the url to the "Series title / id" field, the tool will download the url if it knows it.

**Comment by Ha5yA** [comment]
Alright..
Thanks for making this software
Will be handy
