### ISSUE TITLE
skip_error功能

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#309]
skip_error:忽略/跳過圖片錯誤。當404圖片不存在、檔案過小，或是被偵測出非圖片(如不具有EOI)時，依舊強制儲存檔案。	(真偽)

請問當**開啟**的時候,程式會 **強制儲存檔案**

**關閉**的時候,程式會**顯示錯誤,不儲存有問題的檔案**

是這樣嗎

因為不太清楚忽略/跳過圖片錯誤和強制儲存檔案的邏輯,所以才問的

**Comment by kanasimi** [comment]
yes
