### ISSUE TITLE
問題

### ISSUE THREAD

**Issue by sandycheng1** [kanasimi/work_crawler#31]
謝謝您
可以請問一下
![2](https://user-images.githubusercontent.com/41149813/43014462-cd9e4950-8c7e-11e8-9289-47c172c0d57c.PNG)
這個狀況有辦法解決嗎
圖案亂了
http://www.rocaca.com/manga/the_last_zombie/
有部份都會這樣

**Comment by kanasimi** [comment]
這個網站在用網頁呈現圖案的時候會再加工
由於本工具純粹只是下載圖片檔案
因此不會對圖片再編碼
這種情況恐怕只能麻煩您到網站上面看了 😞
