### ISSUE TITLE
CentOS Linux 服務器如何使用這個工具？

### ISSUE THREAD

**Issue by chennanpo** [kanasimi/work_crawler#310]
沒看懂文檔

**Comment by kanasimi** [comment]
不曉得您是不是能使用發行版
https://github.com/kanasimi/work_crawler/releases
裡面的Linux版安裝包呢

**Comment by chennanpo** [comment]
不是桌面Linux
是CentOS Linux 7的

**Comment by kanasimi** [comment]
可否安裝 Node.js 與 7-Zip 18.01 以上的版本?
https://github.com/kanasimi/work_crawler#lazy-installation-%E6%87%B6%E4%BA%BA%E5%AE%89%E8%A3%9D%E6%B3%95

**Comment by chennanpo** [comment]
讓妳費心了，WIN桌面已經體驗過了，很不錯的程序，只是我現在長時間使用的是CentOS Linux 7，我也只是詢問下CentOS Linux是否可運行

**Comment by kanasimi** [comment]
若可否安裝 Node.js 與 7-Zip 18.01 以上的版本，應可執行CLI 命令列版本。
事實上這邊平常也是採CLI 命令列版本批次執行。

**Comment by chennanpo** [comment]
可以安裝 但是7z
Installing : p7zip-16.02-10.el7.x86_64
Verifying  : p7zip-16.02-10.el7.x86_64

**Comment by kanasimi** [comment]
若您只下載漫畫，16.02版應該也夠用了。
不曉得可否執行CLI 命令列版本？

**Comment by chennanpo** [comment]
没

**Comment by kanasimi** [comment]
所以您可以使用CLI或GUI嗎?

**Comment by chennanpo** [comment]
有可能我知識有限，我試了壹天沒辦法再命令界面執行CLI！T-T

**Comment by kanasimi** [comment]
不曉得您遇到了什麼問題呢
有沒有錯誤訊息?

**Comment by kanasimi** [comment]
@chennanpo 
這邊費了點時間
安裝了CentOS 7
發現可以執行命令列模式
圖形介面還有問題，似乎是electron的程式庫問題

無論如何最起碼CLI應該是可以使用的
您可能必須要提供您嘗試時的錯誤訊息
這邊才能幫您解決

**Comment by chennanpo** [comment]
...能否提供下妳的安裝操作循序...

**Comment by kanasimi** [comment]
@chennanpo 
這邊下載了ISO檔
用vishalbox安裝完畢
為了測試gui
因此這邊選擇gnome

再利用上面網址提到的方法安裝7-zip和nodejs
之後採用懶人安裝法提到的方法
https://github.com/kanasimi/work_crawler#lazy-installation-%E6%87%B6%E4%BA%BA%E5%AE%89%E8%A3%9D%E6%B3%95
下載work_crawler.updater.js這個安裝檔之後執行完就能測試了

**Comment by chennanpo** [comment]
`[root@izj6c6ess9jm3yjiorhkwez comic.cmn-Hans-CN]# node manhuaniu.js "极寒攻略" skip_error=true
skip_error: undefined
From CLI → true
manhuaniu: 2019/6/17 13:9:56 Starting 极寒攻略, save to manhuaniu/
Get 1 servers from [https://www.manhuaniu.com/js/config.js]: https://res.nbhbzl.com/
get_URL_node: timeout 30s [https://www.manhuaniu.com/manhua/10316/]
無法取得 10316 的作品資訊：Error: Timeout 30s: https://www.manhuaniu.com/manhua/10316/
`

`Trace: MESSAGE_NEED_RE_DOWNLOAD
    at Work_crawler.onerror (eval at load_named (eval at <anonymous> (/www/wwwroot/work_crawler/work_crawler-master/CeJS-master/_for include/node.loader.js:78:10)), <anonymous>:693:13)
    at Work_crawler.process_work_data (eval at load_named (eval at <anonymous> (/www/wwwroot/work_crawler/work_crawler-master/CeJS-master/_for include/node.loader.js:78:10)), <anonymous>:2379:9)
    at _onfail (eval at load_named (eval at <anonymous> (/www/wwwroot/work_crawler/work_crawler-master/CeJS-master/_for include/node.loader.js:78:10)), <anonymous>:1704:36)
    at Timeout._ontimeout (eval at load_named (eval at <anonymous> (/www/wwwroot/work_crawler/work_crawler-master/CeJS-master/_for include/node.loader.js:78:10)), <anonymous>:2311:4)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

undefined:696
                                throw this.id + ': ' + (new Date).format('%Y/%m/%d %H:%M:%S')
                                ^
manhuaniu: 2019/6/17 13:12:29 MESSAGE_NEED_RE_DOWNLOAD
`

**Comment by chennanpo** [comment]
圖形界面的話是可以取的，就是不知道這命令模式下怎麽使用！
比如我要：
×：reget_chapter:重新取得每個所檢測的章節內容。 (boolean)
√：archive_images:漫畫下載完畢後壓縮圖像檔案。 (boolean)
√：write_image_metadata:將每個圖像的資訊寫入同名(添加.json延伸檔名)的JSON檔，方便其他工具匯入用。 (boolean)

**Comment by kanasimi** [comment]
看起來似乎無法成功連線
會不會是被防火牆擋住了?

**Comment by chennanpo** [comment]
這個需要開放什麽端口？

**Comment by kanasimi** [comment]
需要允許 node 向外索取資料

**Comment by kanasimi** [comment]
> 圖形界面的話是可以取的，就是不知道這命令模式下怎麽使用！
> 比如我要：
> ×：reget_chapter:重新取得每個所檢測的章節內容。 (boolean)
> √：archive_images:漫畫下載完畢後壓縮圖像檔案。 (boolean)
> √：write_image_metadata:將每個圖像的資訊寫入同名(添加.json延伸檔名)的JSON檔，方便其他工具匯入用。 (boolean)

e.g.,
`node manhuaniu.js "极寒攻略" archive_images=false`

**Comment by kanasimi** [comment]
manhuaniu 確實連線不好
您要不要試試其他連線快速的網站?

**Comment by chennanpo** [comment]
多命令是這麽寫的嗎？
node gufengmh.js "極寒攻略" archive_images=true write_image_metadata=true

archive_images: true
    From CLI → true
write_image_metadata: **undefined**
          From CLI → true

**Comment by chennanpo** [comment]
`# node manhuaniu.js "極寒攻略"archive_images=true write_image_metadata=true
write_image_metadata: undefined
          From CLI → true
manhuaniu: 2019/6/17 13:52:35 Starting 極寒攻略archive_images=true, save to manhuaniu/
Get 1 servers from [https://www.manhuaniu.com/js/config.js]: https://res.nbhbzl.com/
[極寒攻略archive_images=true]: Get 0 works: []
manhuaniu: 未搜尋到與《極寒攻略archive_images=true》相符者。
`

怎麽設置最愛的漫畫目錄？

node ikanman "l=ikanman.txt" recheck=true

這個命令是什麽意思
還有設置保存漫畫的路徑

**Comment by chennanpo** [comment]
# node gufengmh.js "极寒攻略" archive_images=true write_image_metadata=true
archive_images: true
    From CLI → true
write_image_metadata: undefined
          From CLI → true
gufengmh: 2019/6/17 13:55:56 Starting 极寒攻略, save to gufengmh/
Get 1 servers from [https://www.gufengmh8.com/js/config.js]: https://res.gufengmh8.com/
jihangonglue [三千瓦] 极寒攻略: 20 章. 连载中
get_URL_node: timeout 30s [https://www.gufengmh8.com/manhua/jihangonglue/776238.html]
get_URL_node: Retry 1/4: Error: Timeout 30s: https://www.gufengmh8.com/manhua/jihangonglue/776238.html
SyntaxError: 
1/20 [0001 预告] 11 images.
SyntaxError: hapter 2/20, 預估還需 13.2 min 下載完本作品。...
2/20 [0002 初冬] 38 images.
Get data of chapter 3/20, 預估還需 8.4 min 下載完本作品。...

**Comment by kanasimi** [comment]
![image](https://user-images.githubusercontent.com/186866/59581710-526aaf00-9108-11e9-94ed-009f11607b92.png)

**Comment by chennanpo** [comment]
哈哈，感謝，我都忘記有命令說明這事了。。。我仔細看看

**Comment by chennanpo** [comment]
# node gufengmh.js "l=gufengmh.txt" archive_images=true write_image_metadata=true
archive_images: true
    From CLI → true
write_image_metadata: undefined
          From CLI → true
gufengmh: 2019/6/17 15:16:29 Starting l=gufengmh.txt, save to gufengmh/
get_URL_node: timeout 30s [https://www.gufengmh8.com/js/config.js]
get_URL_node: Retry 1/4: Error: Timeout 30s: https://www.gufengmh8.com/js/config.js


這個gufengmh.txt 我是放在JS同目錄下是不是正確的？

**Comment by chennanpo** [comment]
還有這個錯誤是什麽意思？

`get_URL_node: Get error when retrieving [https://res.gufengmh8.com/images/comic/326/650659/1553380811XKbbpcdbYNT59Dji.jpg]:
{ Error: socket hang up
    at createHangUpError (_http_client.js:268:15)
    at TLSSocket.socketOnEnd (_http_client.js:360:23)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:978:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9) code: 'ECONNRESET' }
Failed to get image. No contents: https://res.gufengmh8.com/images/comic/326/650659/1553380811XKbbpcdbYNT59Dji.jpg
`

這個圖片也明明存在

**Comment by kanasimi** [comment]
gufengmh8剛剛也不太順
重新下載或許就好了?

**Comment by kanasimi** [comment]
> 這個gufengmh.txt 我是放在JS同目錄下是不是正確的？
yes

**Comment by chennanpo** [comment]
為撒用不上？不會自動壓縮嗎？

**Comment by kanasimi** [comment]
archive_images=true is default
write_image_metadata=true is for hydrus. See #159

**Comment by chennanpo** [comment]
如何采集的時候圖片地址都保存到JSON裏？linux操作的時候發現不會保存進去，但是PC就能保存地址到漫畫名稱的JSON裏

**Comment by kanasimi** [comment]
照理來說應該都會
您必須要提供更詳細的錯誤訊息
包括下載的是哪個網站的哪個作品
以作品ID或者作品名稱下載的

**Comment by chennanpo** [comment]
比如說 dongman.js   1335編號的漫畫
我設置
write_chapter_metadata=true的話就變成壹個壓縮包壹個JSON
write_image_metadata=true的話就變成每張圖片壹個JSON

**Comment by chennanpo** [comment]
而主要的  1335 心動預警.json 文件不會保存圖片地址到裏面

**Comment by kanasimi** [comment]
這個網站就算在PC端上也不會儲存圖片網址啊
或許您可以試試看 write_image_metadata=true 甚至 write_image_metadata=true 會不會儲存圖片網址
不曉得您需要圖片網址有特別的用途嗎

**Comment by chennanpo** [comment]
L服务器下载后，在家或者在外面就调用json看

**Comment by kanasimi** [comment]
通常這類型網站會有下載防護
例如需要post data
Referer
或者是暫時性的圖片網址
因此還是建議您下載下來之後再做傳輸
光是圖片網址恐怕不可靠
不能夠直接下載

**Comment by chennanpo** [comment]
就是下载下来后的本地地址也没存在json里，难道要我自己再去生成个json才行？

**Comment by kanasimi** [comment]
> 下载下来后的本地地址

您指的是 main_directory 嗎

**Comment by chennanpo** [comment]
這個工具有的漫畫不是會生成的JS裏包含"file":"manhuaniu/10316 極寒攻略/0018 殺人者？/10316-18-003.jpg"這種本地地址嗎。。有的漫画网站又不会生成

**Comment by kanasimi** [comment]
不會生成的通常是一些圖片下載時經過特殊處理的網站
不過file這個field
人工的話 基本上用推測的就可以想得出來
不曉得您是需要用程式來讀取json檔嗎
