### ISSUE TITLE
請求增加 友绘漫画网 手機版 http://m.wuyouhui.net/

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#311]
與365相似

**Comment by kanasimi** [comment]
平台上的作品大多下架了?

**Comment by gfhghfghfh** [comment]
轉成手機版，似乎看的到，有辦法利用手機版，知道如何爬取電腦版的圖嗎

**Comment by kanasimi** [comment]
http://m.wuyouhui.net/
必須重寫新的程式碼

**Comment by gfhghfghfh** [comment]
好的,此外https://www.gufengmh8.com/manhua/huangdidedushengnu/
像這種轉成手機板似乎也可取得

**Comment by gfhghfghfh** [comment]
請問一下**下載機制**
<img width="665" alt="擷取" src="https://user-images.githubusercontent.com/42042168/59594733-fd8a6100-9126-11e9-913c-f3403e55823f.PNG">
意思是
360漫画​、我要去漫画​、365漫画网  **只下載pc端**不下載手機端
友绘漫画网 **只下載手機端**不下載pc端

是這樣嗎
​

**Comment by kanasimi** [comment]
yes
