### ISSUE TITLE
請求增加 古風漫畫 手機板 https://m.gufengmh8.com/

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#312]
﻿

* **Version**: 
* **Interface**:

**Comment by gfhghfghfh** [comment]
https://www.gufengmh8.com/manhua/huangdidedushengnu/
像這種轉成手機板似乎也可取得

如果您有意願支持
希望可以增加為古風漫畫手機板
不跟電腦版的古風漫畫混在一起

**Comment by kanasimi** [comment]
同樣也必須重寫程式嗎
