### ISSUE TITLE
希望增加可以下载单独链接功能

### ISSUE THREAD

**Issue by hjp070928** [kanasimi/work_crawler#314]
漫画里某一话或者某一卷都有单独链接，希望能增加单独链接下载，直接复制链接就可以下载某一话或者某一卷，这样就不用费劲去数章节了

**Comment by kanasimi** [comment]
請問您會需要用到這個功能
通常是因為要下載單話
或者是某幾話？

通常是最新的幾話、最新的一話
或者是中間的一段、最初的一段？

**Comment by hjp070928** [comment]
1.我的意思是說，例如這一話或者這一卷會有一個鏈接，複製這個鏈接就可以把整話或者整卷下載完成
2.我知道軟體有分章節下載，但是下載是從所有話的排序開始計算，有的網站話數排序是正序，而有的是倒序，而且有的裡面還摻雜著特別篇之類的，這樣摻雜的也算一個章節，要是下載的話難道還要去數哪一話是第幾個章節？
