### ISSUE TITLE
強制將非圖片檔儲存為圖片 訊息顯示問題

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#316]
命令行介面

下載bookcube 時
出現
<img width="596" alt="fgdgdfgdf" src="https://user-images.githubusercontent.com/42042168/59944666-eeddda00-9497-11e9-9222-b4d6687e5e6a.PNG">

但是我並沒有設定強制將非圖片檔儲存為圖片
雖然查看資料夾後並沒有發現bad檔

請問是顯示有問題嗎

**Comment by kanasimi** [comment]
這類型網站都設定 skip_error : true

**Comment by gfhghfghfh** [comment]
請問這類型的網站為什麼需要skip_error : true

**Comment by kanasimi** [comment]
這類型網站必須靠偵測到錯誤時，轉到下一個章節來運作；因此當圖片下載錯誤時不能直接中斷跳出。
