### ISSUE TITLE
【 小説を読もう！yomou.js 】下載後無法打開epub

### ISSUE THREAD

**Issue by su0su0** [kanasimi/work_crawler#320]
* **Version**:  2.1.0

* **網站**： 小説を読もう！ （ https://yomou.syosetu.com/ ）

* **問題**：下載後無法打開epub文件

* **例**：

《[沈黙の女神](https://mega.nz/#!0rxQGajB!gxmED8uBglSygi-sCmsLFWowJQH6dvjk7g1_Lx2Lh2k)》

《[公爵令嬢の嗜み](https://mega.nz/#!l7JW2CbS!25llNLBPgb_rnF62qEAT-GHFa6eFDzvmgmqSpjtivgU)》

https://imgur.com/a/ePd8341

**Comment by kanasimi** [comment]
感謝您的愛用
請問您是用什麼軟體來開啟epub檔呢
另外 不曉得有沒有錯誤訊息的螢幕截圖可以參考

![image](https://user-images.githubusercontent.com/186866/59982144-62225000-9640-11e9-8834-8531f6044e61.png)

**Comment by su0su0** [comment]
> 感謝您的愛用
> 請問您是用什麼軟體來開啟epub檔呢
> 另外 不曉得有沒有錯誤訊息的螢幕截圖可以參考
> 

謝謝大佬回覆這麼快😳
我先用的SumatraPDF總會遇到問題。不過我剛剛試着calibre就可以閱覽了。非常抱歉😖麻煩您了><

**Comment by kanasimi** [comment]
所以您的意思是希望 SumatraPDF 也可以使用嗎

**Comment by su0su0** [comment]
> 所以您的意思是希望 Sumatra PDF 也可以使用嗎
不是不是，我的意思是我以後用calibre就行了😅。謝謝大大🙏

> 這邊不曉得您遇到的是什麼樣的問題
> 是否有錯誤訊息的螢幕截圖可以參考呢
https://imgur.com/a/xnr9YyR
下載中沒有任何問題所以這大概是SumatraPDF的錯吧😅

**Comment by kanasimi** [comment]
好的
若是您的問題可以解決
麻煩請關掉這個議題
謝謝

![image](https://user-images.githubusercontent.com/186866/59992981-e5639600-9680-11e9-8eae-0c641dd8cd1b.png)
