### ISSUE TITLE
乙女漫畫下載問題

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#323]
﻿

* **Version**: 
* **Interface**:

**Comment by gfhghfghfh** [comment]
依循圖片網址打開圖片
圖片正常顯示
但下載不下來
<img width="941" alt="fdgdfgfgdf" src="https://user-images.githubusercontent.com/42042168/60260009-17882880-990b-11e9-99e3-72bc260692f1.PNG">

**Comment by kanasimi** [comment]
當網路連線速度太慢時
就可能超過等待時間
但是除非出現這樣的訊息我則還會重新嘗試下載
(您可以注意到您所貼出的訊息
下一行就顯示了將會重新嘗試)

您可以採用下列方法來解決
1.one_by_one
2.延長timeout
3.開啟recheck下載幾次
4.加大頻寬、確保連線通暢

**Comment by gfhghfghfh** [comment]
@kanasimi 
並不是只有今天嘗試過

以上都嘗試
但下載不下來的
依舊下載不下來

下載不下來的會顯示
 圖檔損壞：http://n.aiwenwo.net:55888/upload2/1774/2018/03-17/20180317233035_6662i630ax17u_small.jpeg

**Comment by gfhghfghfh** [comment]
關於您說的
**否則還會重新嘗試下載
(您可以注意到您所貼出的訊息
下一行就顯示了將會重新嘗試)**

這邊是了解的

**Comment by gfhghfghfh** [comment]
這邊並沒有將下載不下來的訊息全部貼出（有點多又不算太多的狀況）

**Comment by kanasimi** [comment]
> 這邊並沒有將下載不下來的訊息全部貼出（下載失敗的圖是有點多又不算太多的狀況）

麻煩您將訊息全部貼出
這邊比較曉得什麼狀況

**Comment by gfhghfghfh** [comment]
都是顯示圖檔損壞
像貼上來的圖片那樣
因為都是相同狀況、加上數量不少，所以沒有全部貼出

**Comment by gfhghfghfh** [comment]
<img width="944" alt="fgdfgdfg" src="https://user-images.githubusercontent.com/42042168/60267290-7efaa400-991c-11e9-80af-de5400cca976.PNG">

**Comment by gfhghfghfh** [comment]
從編號15開始

**Comment by kanasimi** [comment]
您必須設定 skip_error 或 allow_EOI_error 選項，才會儲存損壞的檔案。
若您需要重新下載之前下載失敗的章節，請開啟 recheck 選項。

**Comment by gfhghfghfh** [comment]
請問圖片看起來並沒有損壞，
還是是用別的方式判定的

**Comment by kanasimi** [comment]
圖片結尾非正規格式

**Comment by gfhghfghfh** [comment]
請問正規格式是？
