### ISSUE TITLE
搜尋結果的問題

### ISSUE THREAD

**Issue by su0su0** [kanasimi/work_crawler#324]
您好，我想問問：如果搜到幾個作品可不可以讓用戶自己選要下載的？現在好像它會自動選擇其中第一個結果。

例：
[ムーンライトノベルズ](https://mnlt.syosetu.com/search/search/?word=%E7%A7%98%E3%82%81%E4%BA%8B&notword=&nocgenre=&type=&mintime=&maxtime=&minlen=&maxlen=&min_globalpoint=&max_globalpoint=&minlastup=&maxlastup=&minfirstup=&maxfirstup=&order=new) （mnlt.js）
```搜尋《秘め事》找到20個作品：["先生を開発日記","秘め事","満月の秘め事","社内で秘め事はお断り!？【R18】","傷物令嬢とウェストルンド家の秘め事","異世界もふもふ食堂〜僕と爺ちゃんと仔カピバラの味噌スローライフ〜","逢瀬の場所は密室車両！？イケメンディレクターとの淫らな秘め事","異之国奇譚番外編２～女王の秘め事　一夜～","異之国奇譚番外編３～女王の秘め事　二夜～","異之国奇譚番外編５～国王の秘め事～","オフィスでの淫らな秘め事","鏡写しの君に","恋情を乞う","こたつの中での秘め事","夏霜の秘め事","異之国奇譚番外編４～侍従の秘め事～","連立スル 夕顔ノ 方程式","夫婦生活が秘め事ばっかりです！","副団長と奥方の秘め事","SECRET LOVE -秘め事-"]```

有4-5個都叫《秘め事》不過結果總會是[n6213ff](https://novel18.syosetu.com/n6213ff/)。（我也試過用ID搜尋但沒能找到什麼）

**Comment by kanasimi** [comment]
您可以試試輸入全稱

**Comment by su0su0** [comment]
> 您可以試試輸入全稱

我每次都用全稱搜但是名字短的話就...😅

**Comment by kanasimi** [comment]
常常下載的作品可以加入
最愛作品清單

**Comment by su0su0** [comment]
> 常常下載的作品可以加入
> 最愛作品清單

我想問的是如果有兩三部名字完全一樣的話有沒有辦法選擇想要下載的那一個

**Comment by kanasimi** [comment]
若是有多個名字相同的作品
將會顯示錯誤訊息不會下載作品

**Comment by kanasimi** [comment]
@su0su0 若是您沒有其他問題，麻煩請關閉此議題。
下次釋出新的安裝包時將關閉此議題。

**Comment by su0su0** [comment]
好的谢谢您🙏
