### ISSUE TITLE
可否增加設置統一下載路徑

### ISSUE THREAD

**Issue by weiling103** [kanasimi/work_crawler#326]
您好，試用了好一段時間，感覺還是挺好的，但是默認的下載路徑都是在C盤的用戶下載目錄，本人的C盤並不是很多空間，而且還是SSD，所以要更改下載路徑的話，需要一個一個的點擊下載站才能更改路徑，感覺還可以改進一下，可否增加設置統一下載路徑。 如：設置縂的下載路徑為  D:\動漫\
, 然後在 D:\動漫\ 目錄下在創建各個下載站的子文件夾。 

感謝製作出這麽傻瓜化下載的軟體，加油。

**Comment by gfhghfghfh** [comment]
您可以直接改動位置

**Comment by kanasimi** [comment]
其實這個功能已經有了，在說明之中也有特別提到。現在加強了一下，您看看是不是看得懂：
6. 您可設定 `work_crawler_loder.configuration.js` 以指定下載的作品檔案要放到哪個目錄底下。最簡便的方法是直接用文字編輯器打開 `work_crawler_loder.js`，把 `global.data_directory = '';` 這一段修改成您需要的標的資料夾；例如：
   ```
   global.data_directory = 'D:\\動漫\\';
   ```
   **請記得最後必須加上目錄分隔號 `\\’，並且在引號中，目錄分隔號必須輸入兩次！**

**Comment by kanasimi** [comment]
@weiling103 很抱歉
這邊忘記這個檔案每次更新都會被覆寫成新版本，

若欲更改設定，請編輯 `work_crawler_loder.configuration.js` 這個檔案，不要編輯 `work_crawler_loder.default_configuration.js`！

**Comment by gfhghfghfh** [comment]
@kanasimi 
第一次安裝(懶人安裝法)的情況下
將 work_crawler.default_configuration.js 改名成 work_crawler.configuration.js
所以變成只會有 work_crawler.configuration.js
一個檔

而下次更新時
會變成有
work_crawler.default_configuration.js 
work_crawler.configuration.js
這兩個檔

請問使否有work_crawler.default_configuration.js 
不影響使用嗎

**Comment by kanasimi** [comment]
只要在 `work_crawler.configuration.js` 檔案裡面，已將所有選項設定好；那麼是否有 `work_crawler.default_configuration.js` 並不影響程式運作，請勿擔心。

**Comment by weiling103** [comment]
可能因为我用的是Windows安装包的版本，我并没有找到 work_crawler.default_configuration.js 或 work_crawler.default_configuration.js 这个文件。
也許我需要更換安裝方式了。。。謝謝。

**Comment by kanasimi** [comment]
@weiling103 
抱歉沒注意到您使用的是安裝包版本
下次麻煩請依照說明填寫您的資訊
這樣能比較快速的解決您的問題

要改變安裝包版本的主要下載目錄
修改的無度比較大 
可能還需要等一下

**Comment by kanasimi** [comment]
將在下一版更新
