### ISSUE TITLE
問題

### ISSUE THREAD

**Issue by sandycheng1** [kanasimi/work_crawler#33]
請問之前我貼給您韓文的網址
您說需要翻譯支援
可以請問會需要很大量的翻譯嗎
(不能用goole查嗎)
因為我對這方面沒概念
所以問了很失禮的問題的話
先說聲抱歉

**Comment by kanasimi** [comment]
看來您似乎懂得韓語
有您的幫助當然能大大幫助我解析網站的結構
或許我們該找個大家有空討論的時候

您可以到這裡
https://zh.wikipedia.org/wiki/Wikipedia:IRC%E8%81%8A%E5%A4%A9%E9%A2%91%E9%81%93
進入IRC聊天頻道後
打下列指令進入cejs頻道來討論:
```
/join #cejs
```

**Comment by sandycheng1** [comment]
很抱歉
我的文字似乎讓您誤會了
我並沒有到擅長的地步
我是想問說程式是用英文打
為還甚麼需要了解韓文
(如果是蠢問題請多包涵)
