### ISSUE TITLE
start_chapter  失效

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#332]
﻿

* **Version**: 
* **Interface**:

**Comment by kanasimi** [comment]
請詳細描述您採用的步驟
這邊才能研究到底哪邊出問題

**Comment by gfhghfghfh** [comment]
就是改了start_chapter
但是仍從1開始下載

**Comment by kanasimi** [comment]
start_chapter (數字)
    將開始/接續下載的章節編號。對已下載過的章節，必須配合 .recheck。

**Comment by gfhghfghfh** [comment]
是的
確實 .recheck 是打勾的

**Comment by kanasimi** [comment]
麻煩貼上下載的訊息
並且加上圖片吧

**Comment by gfhghfghfh** [comment]
<img width="502" alt="擷取" src="https://user-images.githubusercontent.com/42042168/60518320-e1d0ae80-9d13-11e9-9026-f2bbedadf919.PNG">
<img width="572" alt="fgfhg" src="https://user-images.githubusercontent.com/42042168/60518327-e301db80-9d13-11e9-9d27-4b2a4d925654.PNG">
