### ISSUE TITLE
下載https://manhua.dmzj.com/zhongjirenjiajumbor/時 下載中斷

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#337]
下載https://manhua.dmzj.com/zhongjirenjiajumbor/   時

[📝]1/34 [0001 第01话] 共 59 張圖片。
[📝]2/34 [0002 第02话] 共 48 張圖片。
[📝]3/34 [0003 第03话] 共 36 張圖片。
[📝]4/34 [0004 第04话] 共 32 張圖片。
[📝]5/34 [0005 第05话] 共 36 張圖片。
[📝]6/34 [0006 第06话] 共 34 張圖片。
[📝]7/34 [0007 第07话] 共 42 張圖片。
[📝]8/34 [0008 第08话] 共 18 張圖片。
[📝]9/34 [0009 第09话] 共 28 張圖片。
[📝]10/34 [0010 第10话] 共 22 張圖片。
[☠][46.161s] dmzj: 解析章節頁面時發生錯誤，中斷跳出：https://www.dmzj.com/view/zhongjirenjiajumbor/14030.html

與下方議題情況類似
https://github.com/kanasimi/work_crawler/issues/303

**Comment by kanasimi** [comment]
您的意思是就算發現有這種章節
也想要直接跳過嗎

**Comment by gfhghfghfh** [comment]
如果可以的話希望可以像議題303一樣嘗試爬取圖片
不行的話，希望可以不中斷，但是會在進度條顯示紅色報錯訊息

**Comment by gfhghfghfh** [comment]
https://github.com/kanasimi/work_crawler/issues/303 的空白章節https://www.gufengmh8.com/manhua/wodeshashounanyou/742494.html

**Comment by gfhghfghfh** [comment]
此議題的空白章節https://www.dmzj.com/view/zhongjirenjiajumbor/14030.html#@page=1
