### ISSUE TITLE
請求增加 魔腾小说 https://www.moteng.net/

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#340]
﻿

* **Version**: 
* **Interface**:

**Comment by kanasimi** [comment]
請附個其他網站未揭載之作品。

**Comment by gfhghfghfh** [comment]
https://www.moteng.net/novel/95562/

**Comment by gfhghfghfh** [comment]
不好意思請問能更換網站嗎
因為發現下面網站的更新較早
可以的話
就不勞煩您增加原先的網站

女生文学网 http://www.nswxw.com/

其他網站未有
http://www.nswxw.com/53/53987/
http://www.nswxw.com/15/15396/

**Comment by gfhghfghfh** [comment]
https://www.moteng.net/novel/95562/
https://www.moteng.net/novel/8044/
