### ISSUE TITLE
建议命令行加入“只显示章节编号标题列表，不实际下载文件”的功能

### ISSUE THREAD

**Issue by karma-sun** [kanasimi/work_crawler#342]
如题

**Comment by kanasimi** [comment]
您需要的是從其他程式匯入作品資料 
或者純粹只要在命令列介面顯示作品資料即可呢

**Comment by karma-sun** [comment]
只要显示章节标题和编号，我想要选择从某一章开始下载，但不知道这一章对应的编号是多少

**Comment by kanasimi** [comment]
所以您想要添加一個功能: **從命令列就可以指定開始下載的章節標題**?

**Comment by karma-sun** [comment]
章节标题可能重复不唯一,还是列出标题列表,用编号指定更好
