### ISSUE TITLE
toomics 下載頻率

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#345]

**Comment by kanasimi** [comment]
這邊下載沒問題
煩請貼上錯誤訊息與畫面
謝謝

**Comment by gfhghfghfh** [comment]
應該是下載頻率的問題

**Comment by kanasimi** [comment]
這個網站好像都只能下載2話而已...
所以您只下載2話
但是也會被擋嗎

**Comment by gfhghfghfh** [comment]
測試id裡
有些有比較多話的部分(例4644,4960)

**Comment by gfhghfghfh** [comment]
測試完整一次
下載到後面
會開始無法下載
[📝]get_URL_node: Retry 1/4: Error: Parse Error
[📝]get_URL_node: Retry 2/4: Error: Parse Error
[📝]get_URL_node: Retry 3/4: Error: Parse Error
[📝]get_URL_node: Retry 4/4: Error: Parse Error

**Comment by kanasimi** [comment]
抱歉這邊嘗試不出來
您可以變更one_by_one 和 chapter_time_interval 
看會不會好一些
