### ISSUE TITLE
哔哩哔哩漫画上线PC网页版

### ISSUE THREAD

**Issue by weirdo4253** [kanasimi/work_crawler#347]
[https://manga.bilibili.com/](https://manga.bilibili.com/)
![2019-08-07_150535](https://user-images.githubusercontent.com/12150840/62602214-d3cf0880-b925-11e9-80d4-7179974a250b.jpg)
希望能更新一下

**Comment by kanasimi** [comment]
哔哩哔哩漫画 改版了...
