### ISSUE TITLE
↻ 重新下載鍵功能 以原先輸入名稱去下載

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#349]

**Comment by gfhghfghfh** [comment]
當我用id下載完
<img width="914" alt="gfghfghf" src="https://user-images.githubusercontent.com/42042168/62642441-4d8fe200-b978-11e9-8350-795f8edda42f.PNG">
因為錯誤發生
而而按下<↻>
會以搜尋作品名的方式下載
<img width="901" alt="擷取" src="https://user-images.githubusercontent.com/42042168/62642645-c2fbb280-b978-11e9-8c5c-4b8fe7376866.PNG">

**Comment by gfhghfghfh** [comment]
希望可以改成按下<↻>時
仍是以id去下載

**Comment by gfhghfghfh** [comment]
因為希望避免
搜尋不到作品名
或是同名作品的情況

**Comment by kanasimi** [comment]
這個不用擔心
按下重新下載鍵時
因為作品名稱都已經做過緩存
所以不會再重新搜尋

**Comment by gfhghfghfh** [comment]
但是按下重新下載時的確是以作品名搜尋，導致issue348的情況
