### ISSUE TITLE
压缩文件夹是否可以做成配置项

### ISSUE THREAD

**Issue by bterys** [kanasimi/work_crawler#352]
﻿

* **Version**: 
* **Interface**:

**Comment by kanasimi** [comment]
請問您指的是小說或漫畫
採用的是圖形或者命令列介面呢
或許 archive_images 這個選項就是您要的?

**Comment by bterys** [comment]
漫画系统，linux命令行界面

**Comment by bterys** [comment]
没知道archive_images的配置项

**Comment by kanasimi** [comment]
![image](https://user-images.githubusercontent.com/186866/62918537-7c6fe300-bdd2-11e9-9ccd-c847650f08d1.png)
您可以試試

**Comment by bterys** [comment]
已搞定，非常感谢！
