### ISSUE TITLE
圖形介面暫停鍵沒反應

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#354]
﻿

* **Version**: 
* **Interface**:

**Comment by gfhghfghfh** [comment]
⏸暫停

**Comment by kanasimi** [comment]
不會馬上暫停，會等到當前的章節處理完畢才會停止。

**Comment by gfhghfghfh** [comment]
這點這邊明白
就是按下去以後
沒像之前一樣顯示當這章節下載完會暫停
實際上也沒暫停

**Comment by kanasimi** [comment]
需要提供更詳細的偵錯資訊
才知道問題發生在哪...

**Comment by gfhghfghfh** [comment]
gui_electron_functions.js:2111 Uncaught ReferenceError: this_job is not defined
    at HTMLSpanElement.pause_resume_job (gui_electron_functions.js:2111)
pause_resume_job @ gui_electron_functions.js:2111
