### ISSUE TITLE
Setting the Default Download Directory

### ISSUE THREAD

**Issue by nstephenh** [kanasimi/work_crawler#357]
你好！ 我说一点中文，但是我的中文不太好。我有一个问题：

* **Version**: 2.3 appimage
* **Interface**: GUI

Is there a way to change the default download directory? I would like to change it to a different folder on my computer from /home/<user>/Downloads/

**Comment by kanasimi** [comment]
Thank you to use the tool.

We mainly have two options to change the download directory:
1. data_directory: Preset the main download directory.
2. main_directory: The download location for each tool.

I think there should a way to let the tool more friendly to use. So users will know how to change the download location. Do you have any idea?

Additionally, I wonder that when you start the tool, is the interface in English properly?

**Comment by kanasimi** [comment]
> I apparently had already changed data_directory, but was a bit confused because the log still mentions the default download location instead of the new download location. Additionally, most of the download options don't have plain text descriptions, and instead just variable names like download_options.data_directory.
May you take screenshots for these cases?

**Comment by kanasimi** [comment]
This issue will be closed before the next release.
