### ISSUE TITLE
請求增加網站《搜动漫》《漫畫狗》《爱奇艺漫画》

### ISSUE THREAD

**Issue by su0su0** [kanasimi/work_crawler#362]
求考慮 
《搜动漫》
http://www.soudongman.com
《漫畫狗》
https://dogemanga.com
《爱奇艺漫画》
https://www.iqiyi.com/manhua/ 
多謝大佬 🌹

**Comment by kanasimi** [comment]
《搜动漫》
http://www.soudongman.com
似乎許多漫畫都看不到了？
