### ISSUE TITLE
土豪漫畫的下載報錯

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#366]
﻿

* **Version**: 
* **Interface**:

**Comment by gfhghfghfh** [comment]
https://www.tohomh123.com/action/play/read?did=9481&sid=8&iid=18&tmp=0.24742774092491748
<img width="538" alt="擷取" src="https://user-images.githubusercontent.com/42042168/64414836-aca35c80-d0c6-11e9-9bb5-c3eea81acd3d.PNG">

**Comment by gfhghfghfh** [comment]
https://www.tohomh123.com/jinzhulizenmeturanzheyang/

**Comment by kanasimi** [comment]
您期待的處置方法是...?

**Comment by gfhghfghfh** [comment]
請問出現這個訊息代表?

**Comment by kanasimi** [comment]
500 表示網站自己出現程式錯誤
https://developer.mozilla.org/zh-TW/docs/Web/HTTP/Status/500
