### ISSUE TITLE
漫畫DB 出現　status 404　get_URL_node: Retry 2/2: BAD STATUS

### ISSUE THREAD

**Issue by Roger77-hw** [kanasimi/work_crawler#368]
﻿

* **Version**: work_crawler-Setup-2.３.0
* **Interface**:　ＧＵＩ 

連結漫畫ＤＢ出現異常狀況如下的訊息
[⚠][1.08s] get_URL_node: [https://www.manhuadb.com/130]: status 404
[⚠][1.424s] get_URL_node: [https://www.manhuadb.com/131]: status 404
[📝]get_URL_node: Retry 1/2: BAD STATUS

**Comment by kanasimi** [comment]
網站最近似乎怪怪的
即使用網頁介面也看不到
另外您可能要描述一下用什麼方法下載的例如是輸入作品名稱或者作品ID

**Comment by Roger77-hw** [comment]
剛剛試了一下 真的像你所說的 網頁也看不到了
前幾天是網頁還可以正常觀看 但是沒法下載

我是用 名稱 下載 但是出現
status 404 get_URL_node: Retry 2/2: BAD STATUS (#368)




Thanks
Roger

kanasimi <notifications@github.com> 於 2019年9月16日 週一 下午8:07寫道：

**Comment by kanasimi** [comment]
這邊現在測試正常
若您發現還是會出錯
麻煩請再回應一下
若是正常請將本議題關閉
謝謝

**Comment by Roger77-hw** [comment]
好 我等一下試試 謝謝

從 Roger's 的 iPhone 傳送

**Comment by kanasimi** [comment]
sorry
這邊下載黄昏流星群
發現網站確實改版了
會在下一個發行版更新

**Comment by Roger77-hw** [comment]
Hi....Kanasimi

請問一下
你最新的 "
comic.cmn-Hans-CN
<https://github.com/kanasimi/work_crawler/tree/master/comic.cmn-Hans-CN> fix
<https://github.com/kanasimi/work_crawler/commit/0caafd9dab7d2642b3f910e3fd053cb5e2bb58d7>
 #368 <https://github.com/kanasimi/work_crawler/issues/368>: 2019/9 漫画DB
網站改版
<https://github.com/kanasimi/work_crawler/commit/0caafd9dab7d2642b3f910e3fd053cb5e2bb58d7>
"
我要如何手動更新

我是使用 MacOS

昨天我把套件打開 找不到相同的 檔案
不知道該怎麼更新

可以幫助一下嗎?

Thanks

Roger







kanasimi <notifications@github.com> 於 2019年9月17日 週二 上午6:43寫道：

**Comment by kanasimi** [comment]
預計這幾天測試一下
這個週末會釋出下個發行版
到時候只要放著應該會自動更新

**Comment by Roger77-hw** [comment]
太好了 

你的作品 真的太棒了 讓我可以好好收集 喜歡的漫畫 

感恩

Thanks

Roger

從 Roger's 的 iPhone 傳送

**Comment by kanasimi** [comment]
謝謝您的愛用
