### ISSUE TITLE
漫画无法下载

### ISSUE THREAD

**Issue by CXido** [kanasimi/work_crawler#370]
![(JGCH%9I9R}X2OQCA%N2KWH](https://user-images.githubusercontent.com/55381745/66196920-ee2a2600-e6cb-11e9-976b-eaa9de1efc80.png)
![G9DR~} ~U)T9AV8G31Q7X`L](https://user-images.githubusercontent.com/55381745/66196931-f1251680-e6cb-11e9-858a-13edee91d5cc.png)

**Comment by kanasimi** [comment]
這邊測試正常
得要麻煩您提供更詳細的資訊
* **Version**:  您使用的 work_crawler 為哪個版本: 安裝包, 懶人安裝法 
* **Interface**:  您使用的 work_crawler 為哪個介面: 圖形介面, 命令列介面 
* **Arguments**:  採用命令列介面時所下的指令，或者使用圖形介面時的網站與作品名稱/作品ID

**Comment by CXido** [comment]
我这里在测试了一下，有些源可以下载，但是有一些源下载实在很慢，而且漫画BD可以进去网页看就是下载不了

**Comment by kanasimi** [comment]
可以麻煩列舉一下
* 下載快的作品
* 下載慢的作品
* 可以進去網頁看但是下載不了的作品

大概有哪些嗎

**Comment by CXido** [comment]
https://www.bilibili.com/video/av70283285

用视频吧，打字比较麻烦，视频直接一些

**Comment by kanasimi** [comment]
感謝您的用心評論與建議
這邊確認 v2.4.0 確實有這問題
預計將會在下一版釋出時修正

關於下載速度
可能得視網路狀態
所下載網站的速度與限制而定
因此網路流量無法完全滿載

此外本工具在下載完整個章節時才會更新進度
若您想要知道每張圖片的下載進度
可以試試調高 debug level

**Comment by srwgin** [comment]
这里同样出现问题 在下载 weibo漫画时候出错
TypeError: Cannot read property 'includes' of undefined
下的是64603 铁鸥
work crawler 版本  2019-10-06T04:55:40Z

**Comment by kanasimi** [comment]
@srwgin 這看起來是另一個網站的問題
可以麻煩您另外開一個議題嗎
謝謝
