### ISSUE TITLE
dm5 無法利用作品名下載

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#371]

**Comment by gfhghfghfh** [comment]
dm5的搜尋框改變了
所以測試了dm5以作品名下載的功能

然後發現利用作品名下載似乎都無法搜到作品
都顯示
下載任務初始化、讀取作品資訊中…… 未搜尋到與《绝世飞刀》相符者。

**Comment by gfhghfghfh** [comment]
dm5網站好像有點小改
搜尋框跟以前不太一樣
<img width="589" alt="3" src="https://user-images.githubusercontent.com/42042168/66252964-1bdaa200-e794-11e9-95cf-9d6bc08442f8.PNG">

所以這邊測試了dm5以作品名下載的功能

然後發現利用作品名下載似乎都無法搜到作品
如下
<img width="232" alt="擷取" src="https://user-images.githubusercontent.com/42042168/66252955-04031e00-e794-11e9-8c21-90eb34a6abd2.PNG">
<img width="662" alt="2" src="https://user-images.githubusercontent.com/42042168/66252956-049bb480-e794-11e9-9d1a-7c246ea9a1b5.PNG">

**Comment by gfhghfghfh** [comment]
fgdgdf

**Comment by gfhghfghfh** [comment]
@kanasimi 可以請問一下https://github.com/kanasimi/work_crawler/commit/e688d9b773809c9f8971ca6eb96920a13f8a5ca6

原本的base_URL : 'https://www.dm5.com/
這個網址可以使用
請問為甚麼需要改成
base_URL : 'http://cnc.dm5.com/'

**Comment by kanasimi** [comment]
沒注意到
還以為改網址了
之後再改回來吧

**Comment by gfhghfghfh** [comment]
請問可以改回https://www.dm5.com/嗎
比較習慣原本的，不好意思
感謝
