### ISSUE TITLE
請求新增comico新手村

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#373]
http://www.comico.com.tw/challenge/

**Comment by gfhghfghfh** [comment]
@kanasimi 
更新後
使用閱讀卷的機制好像沒了
這邊有打開自動適用閱讀卷

**Comment by kanasimi** [comment]
請另開一個議題
並且列舉幾個作品
謝謝

**Comment by gfhghfghfh** [comment]
好的，但是不是貌似不是特定作品
就是無法自動使用閱讀卷
這邊有開打開自動使用，也有在檔案裡輸入帳號
