### ISSUE TITLE
archive_old_works

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#379]

**Comment by gfhghfghfh** [comment]
不好意思
可以請問一下archive_old_works
此功能的用途還有發生時機嗎
這邊試不出差別
https://github.com/kanasimi/CeJS/commit/e55ceb2a86ddc178b3b53a78e2a18a2308d9910c
https://github.com/kanasimi/CeJS/commit/bfe9627975ea8225524f2a64a1e77b0d284101f4

**Comment by gfhghfghfh** [comment]
不好意思
可以請問一下archive_old_works
此功能的**用途**還有**發生時機**嗎
這邊試不出差別,有稍微看到下方的文字說明但不是很確定
https://github.com/kanasimi/CeJS/commit/e55ceb2a86ddc178b3b53a78e2a18a2308d9910c
https://github.com/kanasimi/CeJS/commit/bfe9627975ea8225524f2a64a1e77b0d284101f4

**Comment by gfhghfghfh** [comment]
不好意思
可以請問一下archive_old_works
此功能的**用途**還有**發生時機**嗎
這邊試不出差別,有稍微看到下方的文字說明但不是很確定自己理解的是否正確
https://github.com/kanasimi/CeJS/commit/e55ceb2a86ddc178b3b53a78e2a18a2308d9910c
https://github.com/kanasimi/CeJS/commit/bfe9627975ea8225524f2a64a1e77b0d284101f4

**Comment by gfhghfghfh** [comment]
Q1
這邊嘗試node dm5.js "l=dm5.txt" archive_images=false archive_old_works=true
以及查看圖形介面的選項
似乎沒有不同
請問是這邊哪裡搞錯了嗎



Q2
此功能是可以自行選擇使用或不使用嗎

**Comment by kanasimi** [comment]
當前僅對壓縮檔之漫畫有用，預設不封存舊作品。

**Comment by gfhghfghfh** [comment]
感謝您

**Comment by gfhghfghfh** [comment]
不好意思因為這邊想要了解 如果archive_old_works 被開啟時的樣子
嘗試了一些完結後很久沒更的網址
但是似乎都沒成功
cd comic.cmn-Hans-CN
node qq 528219 archive_old_works=true archive_images=true(也嘗試放入書籤"l=qq.txt"

或是
cd/d D:\work_crawler-master
cd comic.cmn-Hans-CN
node qq "l=qq.txt" archive_old_works=true archive_images=true modify_work_list_when_archive_old_works =true

**Comment by gfhghfghfh** [comment]
@kanasimi 
不好意思因為這邊想要了解 
使用archive_old_works的差別
這邊嘗試
cd comic.cmn-Hans-CN
node qq "l=qq.txt"  archive_old_works=true archive_images=true modify_work_list_when_archive_old_works =true       
 (qq.txt含2015完結作品https://ac.qq.com/Comic/ComicInfo/id/528219)
但是嘗試後看不出使用與不使用差別






請問可以請教一下使用archive_old_works和不使用archive_old_works的差異嗎


感謝閱讀

**Comment by kanasimi** [comment]
預設間隔 "0.5Y"，封存半年沒有新下載的作品。
