### ISSUE TITLE
問題: recheck

### ISSUE THREAD

**Issue by wby238525503** [kanasimi/work_crawler#38]
您說若要從特定章節開始下載
要輸入 node qq 作品名 start_chapter=20 recheck
那如果只打 node qq 作品名 start_chapter=20
會有甚麼不同嗎

還有若是在圖形介面
![default](https://user-images.githubusercontent.com/41182677/43321257-d3e56c94-91dd-11e8-971a-52fd8cde91c1.PNG)
必須要配合 .recheck。 是只要把前面的叉變成勾嗎

**Comment by kanasimi** [comment]
沒有配合 recheck 就不會有效果了
把前面的 recheck 變成勾應該就行了

**Comment by wby238525503** [comment]
但我之前都好像只打node qq 作品名 start_chapter=20
但都會接續下載
那這樣應該部會影響檔案吧?

**Comment by kanasimi** [comment]
已經下載成功的圖片不會再下載

**Comment by wby238525503** [comment]
所以您指的不會有效果
是指
當選定特定章節開始下載(之前未載過)
只打node qq 作品名 start_chapter=20
程式還是會重第一章開始下載的意思嗎

**Comment by kanasimi** [comment]
舉例來說
若是作品最新的章節是22章
並且之前已經下載到22章了
那就不會有效果

**Comment by wby238525503** [comment]
不好意思我還是不太明白
![default](https://user-images.githubusercontent.com/41182677/43322278-a572eb18-91e0-11e8-9510-f92e93ddb4cd.PNG)
我沒打 recheck 
但還是可以從29開始

**Comment by wby238525503** [comment]
所以我想知道有沒有打recheck的差別

**Comment by wby238525503** [comment]
有下載過
但我只打只打node qq 作品名 start_chapter=20
好像也是會執行

**Comment by wby238525503** [comment]
我是想知道有沒有打recheck的差別

**Comment by kanasimi** [comment]
若是 start_chapter 在之前下載過的最後一個章節之前的話，那麼就必須要設定 recheck 才會有效。
之前下載到20章，設定 start_chapter=19 無效。
之前下載到20章，設定 start_chapter=21 有效。

**Comment by wby238525503** [comment]
謝謝
您說明得很清楚
