### ISSUE TITLE
Error: Failed to open

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#381]
﻿

* **Version**: 
* **Interface**: 
* **Arguments**:

**Comment by gfhghfghfh** [comment]
<img width="954" alt="1" src="https://user-images.githubusercontent.com/42042168/67944382-527ecd80-fc17-11e9-8966-93aff26556ff.png">

**Comment by gfhghfghfh** [comment]
確定放檔案位置存在
也有在下載
但按下圈紅色的按鈕
顯示Error: Failed to open

**Comment by kanasimi** [comment]
您可能需要更新 electron 之後
再重新執行
看看會不會不斷出現
前一陣子 electron 更新過

**Comment by gfhghfghfh** [comment]
這邊開啟程式的步驟是
先
node work_crawler.updater.js
再
start_gui_electron.bat


但是還是出現Error: Failed to open

請問是需要另外去哪更新electron嗎

**Comment by kanasimi** [comment]
刪掉整個 node_modules 試試?

**Comment by gfhghfghfh** [comment]
還是無法

**Comment by gfhghfghfh** [comment]
這邊刪掉重裝了一次
下面顯示的訊息


下載並更新圖形介面需要用到的組件 electron...
update_using_npm: Running command at D:\work_crawler-master: npm install --save-dev electron@latest

> core-js@3.3.6 postinstall D:\work_crawler-master\node_modules\core-js
> node postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> electron@7.0.0 postinstall D:\work_crawler-master\node_modules\electron
> node install.js

npm notice created a lockfile as package-lock.json. You should commit this file.
+ electron@7.0.0
added 86 packages from 90 contributors and audited 104 packages in 17.779s
found 0 vulnerabilities

**Comment by gfhghfghfh** [comment]
安裝執行時需要用到的組件 [electron-updater]...
update_using_npm: Running command at D:\work_crawler-master: npm install electron-updater@latest
+ electron-updater@4.2.0
added 11 packages from 23 contributors and audited 123 packages in 3.198s
found 0 vulnerabilities

**Comment by gfhghfghfh** [comment]
@kanasimi 
按下開啟下載目錄會跳出
<img width="287" alt="擷取" src="https://user-images.githubusercontent.com/42042168/68065399-cc23d200-fd63-11e9-86d8-24579a274a76.PNG">
請問是正常的嗎

**Comment by gfhghfghfh** [comment]
@kanasimi 


<img width="630" alt="2222" src="https://user-images.githubusercontent.com/42042168/68066676-af44ca00-fd76-11e9-8cf3-86c14550aafb.png">
在上方的頁面中
按下開啟下載目錄
會得到下面的結果
<img width="517" alt="1" src="https://user-images.githubusercontent.com/42042168/68066682-c97ea800-fd76-11e9-81ec-945bb05fdd92.png">


請問現在改成此種方式
是正常的嗎

**Comment by gfhghfghfh** [comment]
@kanasimi 
現在使用開啟資料夾
<img width="484" alt="2" src="https://user-images.githubusercontent.com/42042168/68273644-0c57bd00-00a2-11ea-8e55-06c8576c8b1c.png">
左側的那一列會被展開
請問可以改成像以前依樣不被展開嗎
因為資料夾多的時候會有點凌亂

感謝

**Comment by kanasimi** [comment]
抱歉
electron改版後似乎只有現在這個功能

**Comment by gfhghfghfh** [comment]
好的
謝謝您
