### ISSUE TITLE
請求支援comico.jp閱讀卷

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#383]
﻿

* **Version**: 
* **Interface**: 
* **Arguments**:

**Comment by gfhghfghfh** [comment]
https://www.comico.jp/articleList.nhn?titleNo=29094

**Comment by gfhghfghfh** [comment]
會顯示
[📝]comico_jp: 登入為
但無法使用閱讀卷

**Comment by gfhghfghfh** [comment]
有閱讀卷https://www.comico.jp/articleList.nhn?titleNo=29094
無閱讀卷https://www.comico.jp/articleList.nhn?titleNo=27481(可使用point

**Comment by kanasimi** [comment]
這邊可用閱讀卷下載
需要提供更詳細的錯誤樣態

**Comment by gfhghfghfh** [comment]
這邊在
work_crawler.configuration.js中開啟 auto_use_ticket : true,
因為從下方看台版日版帳密是輸入在相同地方
所以這邊帳密台版日版一樣


site_configuration.comico = site_configuration.comico_jp = site_configuration.comico_jp_plus = {
	// 讓本工具自動使用閱讀卷。警告:閱讀券使用完就沒了。不可回復。
	 auto_use_ticket : true,
	// 警告:帳號資訊是用明碼存放在檔案中。
	loginid : 'xxxxxx',
	password : 'xxxxxxx'


開始下載
https://www.comico.jp/articleList.nhn?titleNo=29094
仍到五話就停止了

**Comment by gfhghfghfh** [comment]
這邊是台版的可以使用
但日版的無法使用

**Comment by gfhghfghfh** [comment]
這邊理解了
要第二次下載才會使用閱讀卷
打擾了

**Comment by gfhghfghfh** [comment]
這邊理解了
要第二次下載才會使用閱讀卷
不勞煩您了
