### ISSUE TITLE
訊息顯示疑問

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#387]
﻿

* **Version**: 
* **Interface**: 
* **Arguments**:

**Comment by gfhghfghfh** [comment]
打開命令行介面
輸入
cd/d "本工具安裝檔所在的目錄"
start_gui_electron.bat
後


先前的訊息會被清除
(先前的訊息指的是cd/d "本工具安裝檔所在的目錄"  和  start_gui_electron.bat)

只剩下
Active code page: 65001
Loading work_crawler GUI...

**Comment by gfhghfghfh** [comment]
Q1請問這樣是正常的嗎
Q2此外顯示Active code page: 65001
是正常的嗎

感謝

**Comment by kanasimi** [comment]
是正常的
這是為了解決亂碼問題

**Comment by gfhghfghfh** [comment]
謝謝您
那請問Q1也是正常的嗎
就是輸入start_gui_electron.bat後
命令行介面會只剩下
<img width="266" alt="1" src="https://user-images.githubusercontent.com/42042168/68212375-5eea9800-0014-11ea-954a-ee0d839c1000.png">

**Comment by kanasimi** [comment]
是正常的
這是CHCP本來的效果
