### ISSUE TITLE
Option for right to left and vertical text (and maybe .mobi)

### ISSUE THREAD

**Issue by Grinchii** [kanasimi/work_crawler#389]
Hey,

I hope it's fine writing the question in English. 

Would it be possible to add an Option for right to left (rtl) and vertical text? This would be great for reading Japanese Novels. 

This shouldn't be so hard to integrate, cause it seems like you only need to put some css flags in the epub file.

Also it would be great, if it could formate the epub into .mobi files for Kindle Readers (kindlegen).

**Comment by kanasimi** [comment]
日本語で伝わっても大丈夫です。
Calibreを使えますか？

**Comment by Grinchii** [comment]
はい、インストールしています。

Calibreでも色々試してみたがepubを縦書きにするのは以外と難しいみたいです。

今までは本を縦書きのmobiに作り変えるためにはほとんどAozoraEpub３を使っていたんですが、少なくともwork_crawlerが作っていたEpubでは縦書きのmobiを作ることはできませんでした。

**Comment by kanasimi** [comment]
試しに縦書きの機能を追加したんだが、Calibreで読むのがまだ問題がありそう…

**Comment by Grinchii** [comment]
追加してくれて本当にありがとうございました！

縦書きは問題なく使えるようになりました。

今は左->右の読み方なんだが、普通の日本語の本のような右->左の読み方の機能も追加が可能なのでしょうか？

**Comment by kanasimi** [comment]
こちらではこのように見えます。
![image](https://user-images.githubusercontent.com/186866/70365267-97a7b680-18cb-11ea-8ac7-7625ffc8fb50.png)
そちらではどんな状況でしょうか？

**Comment by Grinchii** [comment]
返事が遅くなってすみません。

一応聞くけど縦書きとｒｔｌを使うためにはvertical_writingとconvert_to_TWが同時に必要があるんですね？

少なくともconvert_to_TWなしでは縦書きは出来たがｒｔｌは出来ませんでした。

そのまま
`node AlphaPolis "月が導く異世界道中" vertical_writing convert_to_TW`

を使うとのerrorが出ます

`root@crawler:/crawler/work_crawler-master/novel.ja-JP # node AlphaPolis.js "月が導く異世界道中" chapter_time_interval=1 vertical_writing=true convert_to_TW=true
chapter_time_interval: 15s
  From Command-Line → 1
   vertical_writing: undefined
From Command-Line → true
      convert_to_TW: undefined
From Command-Line → true
AlphaPolis: 2019/12/7 13:34:32 開始處理《月が導く異世界道中》，儲存至 AlphaPolis/
AlphaPolis: Cached work id, will no longer search again: 月が導く異世界道中→"901123427-931067230"
24h.ポイント:12,366 pt  (136位)→11,381 pt  (146位)
undefined:593
                                        ? library_namespace.CN_to_TW(work_data.title)
                                                            ^

TypeError: library_namespace.CN_to_TW is not a function
    at Work_crawler.ebook_path (eval at load_named (eval at <anonymous> (/crawler/work_crawler-master/CeJS-master/_for include/node.loader.js:78:2)), <anonymous>:593:26)
    at Work_crawler.create_ebook (eval at load_named (eval at <anonymous> (/crawler/work_crawler-master/CeJS-master/_for include/node.loader.js:78:2)), <anonymous>:179:32)
    at process_chapter_list_data (eval at load_named (eval at <anonymous> (/crawler/work_crawler-master/CeJS-master/_for include/node.loader.js:78:2)), <anonymous>:1495:36)
    at pre_process_chapter_list_data (eval at load_named (eval at <anonymous> (/crawler/work_crawler-master/CeJS-master/_for include/node.loader.js:78:2)), <anonymous>:1059:5)
    at Work_crawler.process_work_data (eval at load_named (eval at <anonymous> (/crawler/work_crawler-master/CeJS-master/_for include/node.loader.js:78:2)), <anonymous>:949:5)
    at IncomingMessage.eval (eval at load_named (eval at <anonymous> (/crawler/work_crawler-master/CeJS-master/_for include/node.loader.js:78:2)), <anonymous>:2271:6)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)`


そのせいで今まではそのま使っていました

`node AlphaPolis "月が導く異世界道中" vertical_writing`



Kindle Previewerでもｒｔｌじゃなくてｌｔｒでした。

(https://user-images.githubusercontent.com/58256161/70537255-701d4c00-1b60-11ea-85d5-1c2e2d468b44.jpg)

**Comment by kanasimi** [comment]
これならお望みの結果になれるのでしょうか？
`node AlphaPolis "月が導く異世界道中" vertical_writing=lr`

**Comment by Grinchii** [comment]
残念ながらｒｔｌ敵に`node AlphaPolis "月が導く異世界道中" vertical_writing`と同じ結果になります。

だが`node AlphaPolis "月が導く異世界道中" vertical_writing=lr`ではほとんどの内容がなくなっているみたいです。そのものとそのchapterの初ページ以外はすべてが消えています。

**Comment by kanasimi** [comment]
できれば、正常のebookを一本参考させていただければ幸いですが...

**Comment by Grinchii** [comment]
例を追加しました。

[[蒼乃暁] 異世界国家アルキマイラ　―最弱の王と無双の軍勢―.epub.zip](https://github.com/kanasimi/work_crawler/files/3952904/epub.zip)

**Comment by kanasimi** [comment]
ありがとうございます。試しに -webkit-writing-mode を追加したが、今はいかがでしょうか。

**Comment by Grinchii** [comment]
webkit-writing-modeはどうやって使うのでしょか？

`node AlphaPolis "月が導く異世界道中" vertical_writing=lr`と`node AlphaPolis "月が導く異世界道中" vertical_writing`は残念ながら前と変わりません。

一応両方のepubを追加しました。試す為に "月が導く異世界道中" と違って短い本を選びました。

[vertical_writing=true.epub.zip](https://github.com/kanasimi/work_crawler/files/3962916/vertical_writing.true.epub.zip)
[vertical_writing=lr.epub.zip](https://github.com/kanasimi/work_crawler/files/3962917/vertical_writing.lr.epub.zip)

**Comment by kanasimi** [comment]
お望みの画面を示していただけませんか？それで問題を分かるかもしれませんので…

**Comment by kanasimi** [comment]
もし新しい情報がなかったら、この論議はもうすぐ終了します。

**Comment by Grinchii** [comment]
遅くなってしまい申し訳ございません。

論議は終了してしまった以上もう意味がないかも知れないが、色々試してみてｒｔｌに成功しました。

`node AlphaPolis "月が導く異世界道中" vertical_writing`で作り出したEpubをunzipして、EPUBのフォルダの中のcontent.opfを開いて、`<spine>`の所を`<spine page-progression-direction="rtl">`に書き変えることで問題なくｒｔｌになりました。

**Comment by kanasimi** [comment]
ありがとうございました。もう一度お試しください。

**Comment by Grinchii** [comment]
ありがとうございます！

これで完璧になりました。
