### ISSUE TITLE
能否允许设置点击一次开始下载后下载的次数

### ISSUE THREAD

**Issue by lifansama** [kanasimi/work_crawler#39]
开发者辛苦了，
有时候我只想下载单行本，也就是下载完几本后能暂停。能否添加一个这种功能呢？

**Comment by kanasimi** [comment]
請問您使用的 work_crawler 為哪個介面? 圖形介面, 命令行介面

**Comment by lifansama** [comment]
图形界面

**Comment by kanasimi** [comment]
作品欄的後面有一項是暫停下載
不曉得您那邊可以使用嗎

**Comment by lifansama** [comment]
有在用暂停按钮，但是能不能设置让它下载几册后自动暂停？

**Comment by kanasimi** [comment]
看起來加一個 篩選章節標題關鍵字 的功能會更好
