### ISSUE TITLE
7z 執行出錯

### ISSUE THREAD

**Issue by Yucie** [kanasimi/work_crawler#390]
[☠][620.09] archive_file_execute: 7z 執行出錯！
[☠][.335] Error @CeL: 0 [Error] (facility code 0): Command failed: ".\7z" a -sccUTF-8 -scsUTF-8 -tzip -mx=9 -r -sdel -- "d:/Downloads/AlphaPolis_manga/127000286 悪役令嬢になりました。/0003 第3回.zip" "d:/Downloads/AlphaPolis_manga/127000286 悪役令嬢になりました。/0003 第3回/"

程序呼叫7Z時是發生錯誤, 估計是下面情況出現
1.文件夾名稱過長
2.本人用的是日區

另外, 這軟件先會找尋最初出現7Z 的路徑
剛好我有一個軟件有7ZA 這東西, 然後WORK CRAWLER 會誤判
判斷EASE_TODO 內的7ZA 為7Z 軟件(剛好那7ZA 是不能用的, 我只好把檔案改別名)

**Comment by kanasimi** [comment]
請問您是否有安裝7z
若有安裝，安裝路徑是?

**Comment by Yucie** [comment]
有空裝7Z, 路徑為
C:\Program Files\7-Zip

**Comment by kanasimi** [comment]
增加設定壓縮執行檔路徑的功能
煩請試試看

**Comment by Yucie** [comment]
對不起, 我是由安裝包安裝的.
雖然代碼更新了, 但安裝版還沒更新, 不能幫你測試了.

**Comment by kanasimi** [comment]
好的
會在下次更新時加上本功能
