### ISSUE TITLE
7Z问题

### ISSUE THREAD

**Issue by firstuanl** [kanasimi/work_crawler#391]
`daocaoren: tianmuhongchen 天幕红尘: 51 章（本次下载共处理278349个字）于 2019/12/11 12:37:32 下载完毕。
[☠][4:21.488] archive_file_execute: 7z 执行出错！
[☠][7.845] Error @CeL: 0 [Error] (facility code 0): Command failed: "/usr/bin/7z" a -sccUTF-8 -scsUTF-8 -tzip -mx=0 -- "/home/***/Downloads/work_crawler/daocaoren/(一般小説) [豆豆] 天幕红尘 [稻草人书屋 20180919 51章].tianmuhongchen.epub" "mimetype"
[☠][15.44] archive_file_execute: 7z 执行出错！
[☠][.085] Error @CeL: 0 [Error] (facility code 0): Command failed: "/usr/bin/7z" rn -- "/home/***/Downloads/work_crawler/daocaoren/(一般小説) [豆豆] 天幕红尘 [稻草人书屋 20180919 51章].tianmuhongchen.epub" "mimetype" "!imetype"
[☠][14.955] archive_file_execute: 7z 执行出错！
[☠][.085] Error @CeL: 0 [Error] (facility code 0): Command failed: "/usr/bin/7z" a -sccUTF-8 -scsUTF-8 -tzip -mx=9 -r -sdel -- "/home/***/Downloads/work_crawler/daocaoren/(一般小説) [豆豆] 天幕红尘 [稻草人书屋 20180919 51章].tianmuhongchen.epub" "META-INF" "EPUB"
[☠][14.42] archive_file_execute: 7z 执行出错！
[☠][.07] Error @CeL: 0 [Error] (facility code 0): Command failed: "/usr/bin/7z" rn -- "/home/***/Downloads/work_crawler/daocaoren/(一般小説) [豆豆] 天幕红尘 [稻草人书屋 20180919 51章].tianmuhongchen.epub" "!imetype" "mimetype"
`

ubuntu 16.04，7z系统 Lazy installation 懒人包

**Comment by firstuanl** [comment]
> ~$ 7z
7z    7za   7zip  7zr   

系统有这几个

**Comment by firstuanl** [comment]
终端同样问题

**Comment by kanasimi** [comment]
請問 `which 7zr` 的輸出為？

**Comment by firstuanl** [comment]
> which 7z
/usr/bin/7z

> which 7za
/usr/bin/7za

> 7z --help

7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
p7zip Version 9.20 (locale=zh_CN.UTF-8,Utf16=on,HugeFiles=on,4 CPUs)



你好，linux下7z没有这么高，小说电子书没看到不压选项。出现错误，下载的html也全清空了。

**Comment by kanasimi** [comment]
@firstuanl 添加了在Linux下壓縮檔案的功能
煩請您測試一下
謝謝

**Comment by firstuanl** [comment]
OK了
