### ISSUE TITLE
如果我购买哔哩哔哩的付费章节 怎么下载

### ISSUE THREAD

**Issue by coremaya** [kanasimi/work_crawler#396]
﻿

* **Version**: 
* **Interface**: 
* **Arguments**:

**Comment by kanasimi** [comment]
您可以把付費章節存起來
給這邊來分析一下

**Comment by coremaya** [comment]
要保存成哪种格式

**Comment by kanasimi** [comment]
壓縮一下就給壓縮檔吧
多來個幾頁
詳細一點會比較好

**Comment by goldstream** [comment]
如果添加账号登录，这样可不可行？

**Comment by kanasimi** [comment]
> 如果添加账号登录，这样可不可行？

這肯定是要附上去的...
就不曉得登入後網頁長什麼樣子
所以才需要來個參考

**Comment by coremaya** [comment]
传过去

**Comment by coremaya** [comment]
怎么发压缩包

**Comment by kanasimi** [comment]
應該直接拖到發言框就行了

**Comment by coremaya** [comment]
[bilibili.zip](https://github.com/kanasimi/work_crawler/files/4133881/bilibili.zip)

**Comment by kanasimi** [comment]
@coremaya 抱歉 這邊嘗試的結果
沒有辦法直接由程式登入
最多恐怕只能採用輸入cookie的方式繞過

依照您提供的檔案
假如cookie輸入對的話
看起來似乎能正常下載圖片?

**Comment by coremaya** [comment]
> @coremaya 抱歉 這邊嘗試的結果
> 沒有辦法直接由程式登入
> 最多恐怕只能採用輸入cookie的方式繞過
> 
> 依照您提供的檔案
> 假如cookie輸入對的話
> 看起來似乎能正常下載圖片?
找到一个用cookie登录能下载的，解决了，另外想请求看看https://bookwalker.jp/这个网站能不能提取图片 因为想在这上边买书 听说图片很清晰 ，感谢

**Comment by kanasimi** [comment]
request BOOK☆WALKER https://bookwalker.jp/
