### ISSUE TITLE
start_gui_electron.bat 无法启动GUI界面

### ISSUE THREAD

**Issue by stevenfu1990** [kanasimi/work_crawler#397]
win7x64系统
使用Lazy installation 懶人安裝法，执行start_gui_electron.bat
提示:  Active code page:65001
          Loading word_crawler GUI...

但是GUI界面并没有弹出启动
![1](https://user-images.githubusercontent.com/8341454/74229484-6c8f7800-4cfd-11ea-9618-8f5430633e1b.png)

**Comment by kanasimi** [comment]
請問在命令列介面下執行，顯示什麼呢？

**Comment by stevenfu1990** [comment]
以上图片就是执行结果：Active code page:65001
                                       Loading word_crawler GUI...

**Comment by kanasimi** [comment]
可以貼上像是執行
`node qq.js "作品名稱"`
的結果嗎

**Comment by stevenfu1990** [comment]
![1](https://user-images.githubusercontent.com/8341454/74293981-75bd2b00-4d77-11ea-918f-3c87dd4cd8d3.png)

**Comment by stevenfu1990** [comment]
![1](https://user-images.githubusercontent.com/8341454/74294019-98e7da80-4d77-11ea-8d78-c2cd6748a853.png)

**Comment by stevenfu1990** [comment]
经测试，图形界面无法启动，执行start_gui_electron.bat后再执行cd comic.cmn-Hans-CN && node qq.js "狐妖小红娘" skip_error=true会报错。不执行start_gui_electron.bat，直接在程序目录下执行cd comic.cmn-Hans-CN && node qq.js "狐妖小红娘" skip_error=true正常。

**Comment by kanasimi** [comment]
1. 請問一下您曾經成功執行過嗎? 大概是什麼時候 做了什麼動作之後 開始出問題的?

照理來說
`Loading work_crawler GUI...`
之後不會跳出來
或許是因為 electron 的問題

2. 您可以把程式目錄全部刪除
重新裝一次看看是否正常嗎

**Comment by stevenfu1990** [comment]
试过多次了，用懒人安装法安装无效，手动安装electron也不行

**Comment by kanasimi** [comment]
所以您其實沒有成功執行過嗎?
那麼您或許可以先試試看
https://github.com/kanasimi/work_crawler/releases/latest/

**Comment by stevenfu1990** [comment]
执行node qq.js。。。成功了，但是如果执行start_gui_electron.bat还是不成功。
另外，报告下youma.js和mymhh.js这两个，因为目标网站仅为手机网页，所以执行后获取图片失败，是否可以加入uesr-agent

**Comment by kanasimi** [comment]
> 执行node qq.js。。。成功了，但是如果执行start_gui_electron.bat还是不成功。
或許是因為 electron 的問題
您可以把程式目錄全部刪除
重新裝一次看看是否正常嗎

> 另外，报告下youma.js和mymhh.js这两个，因为目标网站仅为手机网页，所以执行后获取图片失败，是否可以加入uesr-agent
這是另外一個問題
可以麻煩您另外開個議題嗎 謝謝
