### ISSUE TITLE
2.70版本failed to load cjes libiary

### ISSUE THREAD

**Issue by ChristopherSung** [kanasimi/work_crawler#407]
﻿

* **Version**: 安裝包
* **Interface**: 圖形介面
* **Arguments**: 

v2.6可以正常打开
v2.7![2 70](https://user-images.githubusercontent.com/49830879/76298754-e9aa0f00-62f4-11ea-8339-4683a5dfcf02.png)

**Comment by kanasimi** [comment]
上傳了新的版本
麻煩請試試看
