### ISSUE TITLE
乙女漫畫無法搜索 原網址更換？

### ISSUE THREAD

**Issue by JKetc** [kanasimi/work_crawler#408]
﻿
* **Version**: <!-- 您使用的 work_crawler 為哪個版本: 安裝包2.7.0 懶人安裝法
* **Interface**: <!-- 您使用的 work_crawler 為哪個介面: 圖形使用者介面
* **Arguments**: <!-- 使用圖形介面時的網站  乙女漫畫

安裝包匹配網址失效，無法搜索下載，疑似更新網址，新網址   https://www.yinvmh.com/

希望更新安裝包和系統！！！

**Comment by kanasimi** [comment]
這邊試過安裝包2.7.0
仍然可下載乙女漫画 nokiacn
不曉得您遇到的錯誤訊息是什麼?

**Comment by JKetc** [comment]
十分抱歉！之前可能是原網站問題，現已可以登入！

現更改問題標籤，希望新增新網址 https://www.yinvmh.com/

謝謝！

**Comment by JKetc** [comment]
安裝包2.7.0搜索時，在本人打開網頁確認搜索文件名確實存在後，錯誤訊息為

[☠][174.74] get_URL_node: 获取 [http://www.nokiacn.net/statics/qingtiancms.ashx] 出错：服务器重置连接
[☠][.325] get_work: 没有《沉默绷带男是我的对象》的搜索结果（网站暂时不可用或改版？）



謝謝！

**Comment by kanasimi** [comment]
這邊測試的結果
可以成功下載完畢

有時網站維護
或者下載太頻繁
也可能出問題
或許您可以等待一會兒再試試?
