### ISSUE TITLE
ComicWalker特定作品下載出錯

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#411]
﻿

* **Version**: 
* **Interface**: 
* **Arguments**:

**Comment by gfhghfghfh** [comment]
https://comic-walker.com/contents/detail/KDCW_AM06201502010000_68/
[☠][1.153s] ComicWalker: 《"かわいい"はキミのもの》：執行 .get_chapter_list() 時發生嚴重錯誤，異常中斷。

**Comment by gfhghfghfh** [comment]
<img width="437" alt="2" src="https://user-images.githubusercontent.com/42042168/77219706-1e2e8e00-6b73-11ea-8bbf-26d02d3d1eb9.png">
<img width="638" alt="1" src="https://user-images.githubusercontent.com/42042168/77219707-1f5fbb00-6b73-11ea-979d-4d5ff2a540fe.png">

**Comment by gfhghfghfh** [comment]
@kanasimi 
上述的KDCW_AM06201502010000_68可正常執行


但換部分的id卻發生執行 .get_chapter_list() 時發生嚴重錯誤，異常中斷。
KDCW_AM00000017010000_68
KDCW_TL01201446010000_68
KDCW_AM01200855010000_68
KDCW_AM00000015010000_68
KDCW_AM00000016010000_68

**Comment by kanasimi** [comment]
麻煩請在出現新問題時列個新議題
這樣比較方便追蹤
謝謝
