### ISSUE TITLE
https://comic.pixiv.net/圖檔類型

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#413]
﻿

* **Version**: 
* **Interface**: 
* **Arguments**:

**Comment by gfhghfghfh** [comment]
問題1
請問一下,現在從https://comic.pixiv.net/下載的圖似乎都變成webp
是因為改版所以無法取得jpg嗎


問題2
此外如果是因為網站改版無法取得jpg的話
能否讓https://comic.pixiv.net/設定acceptable_type

**Comment by kanasimi** [comment]
現在這個網站給地圖全都是 content-type: image/webp
就算設定 acceptable_type 也無法獲得 jpg

**Comment by gfhghfghfh** [comment]
這邊大致理解 acceptable_type這個功能

希望讓 https://comic.pixiv.net/ 設定acceptable_types : 'webp'
是因為若沒設定的話以後網站如果更改原先的 webp的圖檔
而更改後的圖檔的位元組又比原先的圖檔大
會覆蓋到舊有的圖檔


ex:
如果原先的 85-90-011.webp (112kb) 因網站更改圖片變成85-90-011.webp (169kb) 
重新下載該章節時
85-90-011.webp (169kb) 會覆蓋掉 原先的85-90-011.webp (112kb)



是希望避免有覆蓋舊有圖片的問題
不是希望讓webp變成jpg



感謝您耐心的閱讀

**Comment by kanasimi** [comment]
下次麻煩請新開一個議題...

**Comment by gfhghfghfh** [comment]
好的感謝您
下次會注意的



Q1
可以請問一下這兩行的差異嗎
// acceptable_types : 'webp|png',
// acceptable_types : ['webp', 'png'],


Q2
因為想要確定使用方法
以下這些輸入方法都是正確的嗎
<img width="257" alt="1" src="https://user-images.githubusercontent.com/42042168/79634247-da439e80-819b-11ea-8a9c-cb77d6bc3efc.png">
<img width="247" alt="2" src="https://user-images.githubusercontent.com/42042168/79634249-dadc3500-819b-11ea-9901-d8b6e526780f.png">
<img width="260" alt="3" src="https://user-images.githubusercontent.com/42042168/79634250-db74cb80-819b-11ea-8079-39a94951e410.png">

**Comment by kanasimi** [comment]
上面的用法皆可

**Comment by gfhghfghfh** [comment]
Q3
// 可接受的圖片類別（延伸檔名），以"|"字元作分隔。未設定將不作檢查。輸入"image"表示接受所有圖片。若下載的圖片不包含在指定類型中，則會視為錯誤。

// acceptable_types : 'images',

請問輸入images或image 都是得到相同結果嗎

**Comment by kanasimi** [comment]
應為 images

**Comment by gfhghfghfh** [comment]
請問網站都是預設 JPG 

// 可接受的圖片類別（延伸檔名）。以 "|" 字元作分隔，如 "webp|jpg|png"。未設定將不作檢查。輸入 "images" 表示接受所有圖片。

在acceptable_types 上輸入jpg會不一樣嗎

**Comment by gfhghfghfh** [comment]
@kanasimi 
因為是同類型的問題所以就在這裡問了不好意思

**Comment by kanasimi** [comment]
輸入jpg
表示只接受jpg
> 若下載的圖片不包含在指定類型中，則會視為錯誤。

**Comment by gfhghfghfh** [comment]
@kanasimi 
抱歉我可能沒描述好
我想問的是
請問我記得網站都是預設jpg


那麼輸入webp|jpg|png和webp|png
得到的結果會有不同嗎？

**Comment by kanasimi** [comment]
預設不檢查

輸入webp|jpg|png和webp|png
假如獲得JPG以外的其他圖片
也會當正常接受

**Comment by gfhghfghfh** [comment]
@kanasimi 

未設定acceptable_types ：只將jpg當正常接受
設定acceptable_types：webp|jpg|png：將webp,jpg,png當正常接受

設定acceptable_types：webp|png：將webp,jpg,png當正常接受


請問是這樣嗎？

**Comment by kanasimi** [comment]
未設定acceptable_types ：不限制圖片類型

設定acceptable_types：webp|jpg|png：將webp,jpg,png當正常接受

設定acceptable_types：webp|png：將webp,png當正常接受

**Comment by gfhghfghfh** [comment]
@kanasimi 
未設定acceptable_types 時
重新下載時
只有jpg不會有發生覆蓋舊有圖片的可能性(圖檔非bad的情況下)


而jpg以外的圖檔在下面的情況會發生覆蓋
85-90-011.webp (169kb) 覆蓋掉 原先的85-90-011.webp (112kb)



這樣應該是  未設定acceptable_types ：只將jpg當正常接受


請問是我哪裡理解錯誤嗎

不好意思

**Comment by kanasimi** [comment]
您可以設定
acceptable_types : webp|jpg
這樣無論是webp或是jpg都不會被覆蓋

**Comment by gfhghfghfh** [comment]
@kanasimi 
很感謝您耐心的回覆


但是如果只設定acceptable_types : webp
webp或是jpg也都不會被覆蓋

所以再多設定jpg是多餘的吧？

因為您的程式是預設jpg為default_image_extension

**Comment by kanasimi** [comment]
由圖片的網址URL來判別可能的延伸檔名。猜不出的會採用預設的圖片延伸檔名/副檔名.default_image_extension。
因此還是設定齊全比較保險

**Comment by gfhghfghfh** [comment]
Q4
所以假設使用程式下載某個網站得到的檔案都是jpg
然後我想要完全避免掉覆蓋舊檔的問題
我還是應該設定acceptable_types :jpg嗎


Q5
即使設定 acceptable_types :jpg 
好檔覆蓋壞檔的功能依舊會執行是嗎？
85-90-011.jpg覆蓋85-90-011 bad.jpg

這應該是最後的問題了感謝您耐心的解惑

**Comment by kanasimi** [comment]
Q4 yes
Q5 yes
