### ISSUE TITLE
請問可以增加“登陸賬戶下載已購入的付費章節”的功能嗎？

### ISSUE THREAD

**Issue by weekqin** [kanasimi/work_crawler#419]
﻿

* **Version**: 
* **Interface**: 
* **Arguments**: 

有些付費章節已經購買，但還是希望能通過本軟件下載并保存到硬體，不知道有無考慮過增加登陸功能呢？謝謝

**Comment by kanasimi** [comment]
由於這邊沒有帳號因此不能做測試。
您可以提交可用的pull。
