### ISSUE TITLE
bilibili漫画无法下载

### ISSUE THREAD

**Issue by niuqudechongdong** [kanasimi/work_crawler#421]
﻿请问，我把自己bilibili漫画账号的cookie复制到这个软件的cookie框里，还是无法下载付费章节（我已经购买了），请问这是什么原因，还是说bilibili漫画有无cookie都无法下载付费章节

**Comment by niuqudechongdong** [comment]
顺便问个弱鸡的问题，我是安装包直接下载的，请问以后该怎么更新这个软件？

**Comment by kanasimi** [comment]
正常狀況本工具應該會自動更新。不過近來electron-builder不太穩定，所以恐怕得回到本網站下載更新。

**Comment by niuqudechongdong** [comment]
我也不太清楚是什么原因，我把电脑上所有浏览器的cookie都试了一遍，发现还是不能下载付费章节。但用别的程序的代码输入cookie就能下载付费章节。

**Comment by kanasimi** [comment]
您能把您的輸入方式去掉私密部分
貼上來看看嗎

**Comment by niuqudechongdong** [comment]
我不知道哪些是私密部分，我们可以私密聊天吗，不是在评论区的这种。

**Comment by kanasimi** [comment]
舉例來說 這邊會用
key=value
來設定key
不曉得您那邊是怎麼輸入的呢

**Comment by niuqudechongdong** [comment]
我是这样弄得：在biliibli漫画主页登录好账号，按F12，切换到network选项卡，刷新页面。然后选择第一行（manga.bilibili.com），在右侧找到cookies这一项，复制其中全部内容（不包括“cookie:”）,然后把它复制到这个软件的cookie框里。

**Comment by niuqudechongdong** [comment]
是右侧Headers下的cookie

**Comment by kanasimi** [comment]
麻煩您再試試看

**Comment by niuqudechongdong** [comment]
是不是因为我没有填user_agent和proxy这两个选项，填了这两个才能下载付费的章节

**Comment by kanasimi** [comment]
proxy應該不用
user_agent照您的瀏覽器填好了
另外本次更改應該只能在懶人安裝法實現

**Comment by niuqudechongdong** [comment]
好的，谢谢大佬。不管cookie了，不能下载付费章节便不能下吧。

**Comment by kanasimi** [comment]
下次更新安裝包時會加入這個功能

**Comment by niuqudechongdong** [comment]
好的，谢谢大佬
