### ISSUE TITLE
不太會用id搜索！可以在介紹頁面加上這個嗎？

### ISSUE THREAD

**Issue by ALISI0** [kanasimi/work_crawler#423]
﻿有時候在同一個網站，用名字搜索有很多個結果，比如漫畫狗，我也知道id，但是不知道怎麽用id搜索！

**Comment by kanasimi** [comment]
僅能搜尋作品名稱，無法搜尋作品ID...

**Comment by ALISI0** [comment]
哦~~知道用最愛作品了，，剛才試了一下用id收藏最愛，可以下載了！！
還有我詳細説下吧！！
例如，我在漫畫狗網站，搜索源君物語，然後網站顯示有2個符合結果。
然後我用軟件搜索源君物語，搜索結果裏面顯示，漫畫狗這一欄只有一個結果，能不能改成多個結果都顯示！畢竟漫畫狗網站同一個名字的搜索結果有多個，但是軟件只顯示一個。
不過，我已經通過最愛收藏id解決了！
