### ISSUE TITLE
開啟作品下載目錄出錯

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#426]
﻿

* **Version**: 
* **Interface**: 
* **Arguments**:

**Comment by gfhghfghfh** [comment]
顯示TypeError: node_electron.shell.openItem is not a function:

**Comment by gfhghfghfh** [comment]
點擊資料夾圖示後
<img width="500
"1" src="https://user-images.githubusercontent.com/42042168/82665334-33549580-9c66-11ea-8330-7e89323f052e.png">


在訊息欄顯示顯示TypeError: node_electron.shell.openItem is not a function:

**Comment by gfhghfghfh** [comment]
點擊資料夾圖示後

<img width="500" alt="1" src="https://user-images.githubusercontent.com/42042168/82665488-7adb2180-9c66-11ea-85eb-d9fd00f515ea.png">


在訊息欄顯示顯示TypeError: node_electron.shell.openItem is not a function:

**Comment by kanasimi** [comment]
看起來是 Electron 的版本不夠新...
https://www.electronjs.org/docs/api/shell

**Comment by gfhghfghfh** [comment]
那可以請問我應該去哪裡另外更新嗎?

**Comment by kanasimi** [comment]
進入命令列介面下
執行 `npm update`

**Comment by gfhghfghfh** [comment]
這邊是先輸入
D:\work_crawler-master
後輸入
npm update

但似乎沒有用
請問是這邊哪裡操作不對嗎

**Comment by kanasimi** [comment]
請貼上 `npm i electron`,  `npm update` 的執行結果

**Comment by gfhghfghfh** [comment]
這邊是在整個重裝狀況下進行


+ cejs@3.6.0
added 1 package from 2 contributors and audited 103 packages in 2.182s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by gfhghfghfh** [comment]
npm i electron

> electron@9.0.0 postinstall D:\work_crawler-master\node_modules\electron
> node install.js

+ electron@9.0.0
removed 1 package, updated 1 package and audited 102 packages in 7.299s
found 0 vulnerabilities

**Comment by gfhghfghfh** [comment]
都執行後開啟情況還是一樣
