### ISSUE TITLE
最愛作品列表問題

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#429]
﻿

* **Version**: 
* **Interface**: 
* **Arguments**:

**Comment by gfhghfghfh** [comment]
如果先更改😘最愛作品清單
再更改⚙️下載選項
😘最愛作品清單的內容就會一併保存到preference 
請問能不能改成不再紀錄到preference
也就是不再儲存到 舊有的最愛作品列表

**Comment by kanasimi** [comment]
最愛作品清單 應該都是存在 preference.json
不曉得您的意思是?

**Comment by gfhghfghfh** [comment]
請問新的設定不是應該都存在favorite.txt嗎

**Comment by kanasimi** [comment]
請問您之前的最愛作品列表
都是另外存在 favorite.txt 裡面嗎?

**Comment by gfhghfghfh** [comment]
有了favorite.txt 之後都是

**Comment by kanasimi** [comment]
照理來說
假如沒有手動設定的話
應該不會讀取 favorite.txt
請問您有另外手動設定嗎

**Comment by gfhghfghfh** [comment]
就是如果先在程式裡更改favorite.txt
再更改⚙️下載選項
favorite.txt的內容就會一併保存到preference.json
