### ISSUE TITLE
懒人安装出了问题

### ISSUE THREAD

**Issue by ALISI0** [kanasimi/work_crawler#434]
我按照步骤进行。
然后安装。
work_crawler.updater.js放在F盘下。
![image](https://user-images.githubusercontent.com/47098587/87786534-a5171d00-c86c-11ea-8edf-29c2d3b73bff.png)
但是跳出这个错误了！
请问这个错误怎么解决？

**Comment by kanasimi** [comment]
下載出錯了
您能重新下載並執行嗎

**Comment by ALISI0** [comment]
我重新把那个work_crawler.updater.js下了一遍，然后
![image](https://user-images.githubusercontent.com/47098587/87840569-ecd08f80-c8d2-11ea-9509-0162811c8bbd.png)
跳出了这个问题。

**Comment by ALISI0** [comment]
我大概知道原因了，被墙了，无法从github上获取你的程序包！

**Comment by kanasimi** [comment]
related issue for proxy: #74, #107

**Comment by ALISI0** [comment]
可以访问github了，但是安装
![image](https://user-images.githubusercontent.com/47098587/87844950-d0dde580-c8f4-11ea-9287-49d0a484c0e4.png)
看起来好像是函数调用出问题了！
node我安装的是最新版本
![image](https://user-images.githubusercontent.com/47098587/87844994-5f526700-c8f5-11ea-886b-88ade946a0c9.png)
work_crawler.updater.js也是在github下载的！

**Comment by ALISI0** [comment]
顺带一提，安装包2.8.0几天前就无法使用了，不知道怎么回事！
![image](https://user-images.githubusercontent.com/47098587/87846424-47cdab00-c902-11ea-9b63-3d6b9f146823.png)
所以我才打算直接用命令行下载，可惜一直安装不成功！
假如我是直接下载的程序ZIP，
![image](https://user-images.githubusercontent.com/47098587/87846475-bad72180-c902-11ea-98ce-056fd0cf9a0a.png)
是不是就可以直接node里面的js文件，然后进行下载了！

**Comment by kanasimi** [comment]
依您的情況看起來DNS被擋掉了
使用命令列的話需要翻牆
用hosts的方法沒有用
麻煩您將hosts修改的地方復原
另外對您來說比較方便的方法恐怕還是安裝包
所以先嘗試安裝包看看好了

能麻煩您移除之後
重新下載
重新安裝嗎?
是否依然會出現相同的問題呢?

另外
看起來您瀏覽器似乎有翻牆?

**Comment by ALISI0** [comment]
node,js是我在无法使用安装包后才开始使用尝试懒人方法的。
大概是5、6天前吧！那个时候之前我还在下载，突然就不能读取package,json了！之后我试着卸载，重新下载安装包安装，试了很多次，才去尝试的懒人方法！
如果要说那些天左右我安装的软件，也就是PotPlayer 64 bit——一个视频播放软件！

**Comment by ALISI0** [comment]
已经恢复了host，卸掉了node和这几天安装的软件，还是出现了一样的错误。
![image](https://user-images.githubusercontent.com/47098587/87849143-cc2b2880-c918-11ea-862c-fdd99b12cd9e.png)

**Comment by ALISI0** [comment]
我换了台电脑没问题了，只是现在这台电脑出问题了！我到时候想想办法

**Comment by kanasimi** [comment]
您或許可以嘗試刪除下載目錄中的設定檔
與使用者目錄中的 node_modules 目錄試試看
但這邊不確定是不是這個問題

假如清空下載目錄 刪除設定檔 之後就正常的話
那是本程式的問題
麻煩請回報一下
謝謝

**Comment by ALISI0** [comment]
我都已经卸完了，然后重新安装了一下安装包
还是一样的错误！
![image](https://user-images.githubusercontent.com/47098587/87849950-14e5e000-c91f-11ea-852e-4abe4c62183d.png)
这个是安装后的目录
![image](https://user-images.githubusercontent.com/47098587/87849956-24652900-c91f-11ea-8de8-60c75ab20526.png)
我现在也记不清当初做了什么了？

**Comment by kanasimi** [comment]
您是否能卸載並且重新安裝7zip試試看呢？

**Comment by ALISI0** [comment]
还是不行，各种卸载都试过了！

**Comment by kanasimi** [comment]
或者過幾天這邊做一個 2.9.0
再讓您試試看...

**Comment by ALISI0** [comment]
好吧！到时候我再安装试试，如果还是不行，我就在虚拟机里面运行程序！
至少安装包+程序是没问题的！
非常感谢你能抽空帮忙！

**Comment by ALISI0** [comment]
还是一样的问题。
![image](https://user-images.githubusercontent.com/47098587/87865410-89646180-c9a7-11ea-9462-ba4d491c1fe3.png)
我找了一下类似的问题。
https://github.com/kanasimi/work_crawler/issues/290
不知道从这里能不能解决！

**Comment by kanasimi** [comment]
之前的問題和這次不一樣
請問您可以使用 2.9.0 嗎?

**Comment by ALISI0** [comment]
2.9用不了，一样的问题。

**Comment by kanasimi** [comment]
請問您在命令列底下
可以正常執行下列幾個指令嗎？
``` sh
npm i cejs
npm i gh-updater
npm i electron
npm i electron-updater
```

**Comment by ALISI0** [comment]
呃~~我刚才又重新试了一下，那个可以使用了！
早上还不行，刚才重新安装就可以了！
我也不知道怎么了？
中间就是去安装虚拟机去了，然后安装完虚拟系统，想着最后尝试一下，然后重新下载了2.9的安装包，接着就可以正常使用！然后又卸载了虚拟机！
现在2.9可以完全正常使用了！
非常感谢你能帮助解决！
还抽空更新了2.9！
谢谢！

**Comment by ALISI0** [comment]
还有就是我在安装2.8的时候，那个时候下载的7z目录是F盘下面的。
刚才我重新将7z安装在了C盘默认。
不知道是不是这个影响了运行！
总之现在我7z默认路径，然后运行了2.9就没问题了！

**Comment by ALISI0** [comment]
我刚才验证了一下，如果7z的路径不是默认的，就会出现这个问题！
![image](https://user-images.githubusercontent.com/47098587/87867581-0a7c2280-c9c1-11ea-9d3e-1aa4f937e8b9.png)
所以这个地方希望可以改进一下！
还有如果没有安装7z也会出现，这个问题。

**Comment by kanasimi** [comment]
謝謝您的測試
不過假如沒安裝在默認的路徑
程式本身也不太可能自動找到啊...

**Comment by ALISI0** [comment]
我平常安装软件基本不放在C盘，可能很多人都一样的想法吧！然后把7Z安装在别的盘！然后就会出错！
辛苦你了！
