### ISSUE TITLE
请问能不能新增一个功能？

### ISSUE THREAD

**Issue by ALISI0** [kanasimi/work_crawler#438]
在下载图片的时候，有时候遇到网络不好的情况，多进程下载复数图片会导致全部图片都是bad，然后重新检查的时候，在同样的章节，复数图片下载都是bad！
有些漫画一卷有200多张图片，多进程一次加载10多张，可能全部都出错。
所以能不能补充一个功能，就是可以设置线程池的上限，比如设置2张，每次都是加载2张图片，这样下载效率高些，而且出错也少些，当然这都是网延迟的情况。
使用者可以根据自己的网络情况调整进程下载的图片数量。

**Comment by kanasimi** [comment]
請啟用 one_by_one 這個選項
