### ISSUE TITLE
epub小说档使用sumatraPDF无法打开

### ISSUE THREAD

**Issue by mikulolicon** [kanasimi/work_crawler#441]
小说epub档案使用sumatraPDF提示载入错误，使用手机端阅读器是没问题的，但是我使用easysub提取utf-8编码的txt后重新打包为epub就可以用sumatraPDF打开了:
检查了了log有一行警告可能相关：
[8.827s] 作品名称之语言似乎为cmn-Hant-TW，但指定了novel.cmn-Hans-CN。
小说档案提供下
链接：https://pan.baidu.com/s/1VgFkss3GvEE_NYUm10aJNg 
提取码：055v
个人系统为win10,使用的是懶人安裝法安装的版本。

还有一个小问题也反馈下，一开始使用的时候是使用的exe版本，但是在gui界面设置过自定下载路径后，第二天重新开机再使用的时候就又变成了默认下载路径，而且gui界面的设定下载路径的菜单就再也没出现，重新安装也无解，懒人安装版就没有这样的问题，使用.js文件设置也非常方便。

wiki里的懒人安装教程很详细但大陆要使用npm命令安装无解【强制调用国内源似乎也有问题】，爬了若干贴发现可以使用cnpm规避网络问题，我总结了个MD安装文档【可能有重复操作，但至少安装能用了】，也一并附在上述链接里。

**Comment by kanasimi** [comment]
感謝您的試用與經驗分享。這邊沒辦法使用百度網盤，不曉得若直接將檔案拖曳到輸入區，是否有效呢？

**Comment by mikulolicon** [comment]
https://mega.nz/folder/07oxHaSR#fh0d889nlNMSjIY9yIA7Pw

**Comment by kanasimi** [comment]
能麻煩您試試看，更改預設 registry 之後用一般的方法可否正常安裝嗎？
`npm config set registry https://registry.npm.taobao.org`
若您嘗試後無法安裝，麻煩請描述一下問題。

附註：恢復原先設定
`npm config set registry https://registry.npmjs.org`

**Comment by mikulolicon** [comment]
我尝试了下 npm install cejs，下载成功，但是尝试npm i -D electron@latest报错如下：
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@9.2.0 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@9.2.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\LXY\AppData\Roaming\npm-cache\_logs\2020-08-12T01_38_32_765Z-debug.log

**Comment by kanasimi** [comment]
這邊嘗試改改安裝腳本檔案好了。不曉得您能提供您的環境變數嗎？

另外，請問上面檔案重複的epub檔是修正過或修正前的呢？

**Comment by mikulolicon** [comment]
epub档案是修正前的，我改了名字。
环境变数我不明白是什么。

**Comment by kanasimi** [comment]
> 环境变数我不明白是什么，是指环境变量吗？

yes

另外，找到這個，您試試看是否有效呢？
https://www.jianshu.com/p/f1e3f07ff3a9

簡單的說先執行:
`set ELECTRON_MIRROR=http://npm.taobao.org/mirrors/electron/`

**Comment by mikulolicon** [comment]
PATH=C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) SSD Data Center Tool;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Software\python\python37\Scripts\;C:\Software\python\python37\;C:\Users\LXY\AppData\Local\Microsoft\WindowsApps;C:\Users\LXY\Desktop\Youtube;C:\Software\wqxt_pdf;C:\Users\LXY\AppData\Roaming\npm

**Comment by mikulolicon** [comment]
我尝试先set ELECTRON_MIRROR=http://npm.taobao.org/mirrors/electron/，再npm i -D electron@latest，这次可以下载了。想问下set ELECTRON_MIRROR=http://npm.taobao.org/mirrors/electron/是永久的变更下载源命令还是下次使用的时候还要再键入一次？

**Comment by kanasimi** [comment]
上面的是暫時性的設定。這邊需要比較完整的 environment variable 來區別牆內的機器。不曉得您能提供比較完整的 environment variable 嗎？

另外這邊看不到 "作品名称之语言似乎为cmn-Hant-TW，但指定了novel.cmn-Hans-CN。" 這個錯誤訊息。不曉得您從哪邊發現的呢?

**Comment by mikulolicon** [comment]
就是start_gui_electron.bat启动的gui界面下方信息栏那里，我截了图片放入了上面的mega链接里。

**Comment by mikulolicon** [comment]
work_work_crawler下CMD set命令获取，不知道是不是：

ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\LXY\AppData\Roaming
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=DESKTOP-JIR4USM
ComSpec=C:\WINDOWS\system32\cmd.exe
DriverData=C:\Windows\System32\Drivers\DriverData
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING=Default
HOMEDRIVE=C:
HOMEPATH=\Users\LXY
LOCALAPPDATA=C:\Users\LXY\AppData\Local
LOGONSERVER=\\DESKTOP-JIR4USM
NUMBER_OF_PROCESSORS=6
OneDrive=C:\Users\LXY\OneDrive
OS=Windows_NT
Path=C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) SSD Data Center Tool;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Software\python\python37\Scripts\;C:\Software\python\python37\;C:\Users\LXY\AppData\Local\Microsoft\WindowsApps;C:\Users\LXY\Desktop\Youtube;C:\Software\wqxt_pdf;C:\Users\LXY\AppData\Roaming\npm
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=9e0a
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files\Intel\Wired Networking\
PUBLIC=C:\Users\Public
QT_DEVICE_PIXEL_RATIO=auto
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\WINDOWS
TEMP=C:\Users\LXY\AppData\Local\Temp
TMP=C:\Users\LXY\AppData\Local\Temp
USERDOMAIN=DESKTOP-JIR4USM
USERDOMAIN_ROAMINGPROFILE=DESKTOP-JIR4USM
USERNAME=LXY
USERPROFILE=C:\Users\LXY
windir=C:\WINDOWS

**Comment by kanasimi** [comment]
這邊更改了安裝說明。麻煩您看看依照[新的安裝說明](https://github.com/kanasimi/work_crawler/blob/master/document/README.cmn-Hans-CN.md#%E6%87%92%E4%BA%BA%E5%AE%89%E8%A3%85%E6%B3%95)是否能成功安裝呢？

**Comment by kanasimi** [comment]
經過修改後可通過 epubcheck-4.2.4 檢核。Calibre2 也能打開。sumatraPDF 並未說明問題出在哪，因此這個問題比較難分析。

**Comment by mikulolicon** [comment]
试了下，无论是修改.npmrc的方式还是临时修改都可以使用npm命令安装了，谢谢！

**Comment by mikulolicon** [comment]
“不曉得您可否更詳細的解釋一下，加上個圖片，這邊比較知道哪裡出問題。“
exe版本的main_diractory选项，也就是下载目录设置在我的系统中无法固定【第一次设置有效，会在我设置的下载生成各网站的搜索和下载文件夹，后来电脑重启再打开就又变成在软件默认设置的下载目录重新生成下载文件夹】，而且下载选项菜单（截图上传了）只在第一次下载exe版使用的时候出现了一次，后续就再也没在gui界面出现过（没有找到可以开启下载选项菜单的按钮），我的电脑上重新下载exe版也无法复现有下载选项菜单的gui界面，无法复现问题。我还尝试过将work_crawler.configuration.js 和work_crawler.default_configuration.js设置好下载目录放入exe版的文件夹，但无法生效。

**Comment by kanasimi** [comment]
請問您使用的是 v2.9.0 嗎?
圖片中看起來似乎是舊版的...
![下载选项菜单只有第一次打开时有效，后续打开包括重新下载覆盖都不会出现](https://user-images.githubusercontent.com/186866/89983735-b8ba7580-dcaa-11ea-9a66-1a6a3d4040d3.png)
![electron_x0rWu8BU9J](https://user-images.githubusercontent.com/186866/89983733-b821df00-dcaa-11ea-913a-b4b3d95ec11a.png)

**Comment by mikulolicon** [comment]
我的系统里exe版本无法再打开这个下载选项菜单，重下载覆盖也不起作用，这个是截图的wiki里的安装说明里的图片

**Comment by kanasimi** [comment]
那麼您可以安裝最新的 v2.9.0，然後截取一張 v2.9.0 版的圖片嗎?
您可以 `🐞 启用开发工具` 看看是不是有什麼錯誤訊息

**Comment by mikulolicon** [comment]
我重新安装了一次 v2.9.0的exe版，没有报错，下载选项菜单依然不显示，无法设置main_diractory。我截图上传了【v2.90.jpg】。
尝试将可以生效的懒人安装版中的work_crawler.configuration.js 和work_crawler.default_configuration.js放入安装位置，无法作用于exe版。

**Comment by kanasimi** [comment]
是的 安裝包只會讀取預設下載目錄中的 work_crawler.configuration.js，`%USERPROFILE%\Downloads\work_crawler.configuration.js`
不會讀取安裝包 .exe 同目錄下的 work_crawler.configuration.js

下载选项菜单 應該會在選擇下載網站之後才出現
不曉得您選擇網站之後是否有出現下載選項呢?
假如依然沒出現，恐怕就得麻煩看看 开发工具 的 `Console` panel
![v2 90](https://user-images.githubusercontent.com/186866/89987773-27023680-dcb1-11ea-8072-1e89c3c67ee9.jpg)

**Comment by mikulolicon** [comment]
勾选一个网站后就可以显示下载选项菜单了，之前使用的时候点击了下中国内地漫画/中国内地小说后就可以搜索和下载了，所以没办法显示下载选项菜单。下载目录也可以固定了，我重启电脑后点开搜索也没有再出现重置的现象（之前遇到的重启后重置的问题不知道是什么情况了），应该是没问题了（我用几天看看）。
有个小小的建议：增加下载选项菜单的开启/关闭按钮或者增加一个开启/关闭的快捷键，无论是否选定网站都可以开启和关闭下载选项菜单？

**Comment by kanasimi** [comment]
> 加下载选项菜单的开启/关闭按钮或者增加一个开启/关闭的快捷键，无论是否选定网站都可以开启和关闭下载选项菜单？

點擊標題列就能縮放了
您可試試

**Comment by mikulolicon** [comment]
好的，试了下非常方便，谢谢您的跟进和帮助！
