### ISSUE TITLE
アルファポリス 投稿 少數作品下載倒序

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#447]
﻿

* **Version**: 
* **Interface**: 
* **Arguments**:

**Comment by gfhghfghfh** [comment]
其他應該都為正序
只有這部下載倒序
https://www.alphapolis.co.jp/manga/751820934/836391263

**Comment by gfhghfghfh** [comment]
<img width="86" alt="gfdf" src="https://user-images.githubusercontent.com/42042168/90799496-e3a96700-e345-11ea-9f63-f4bb61a74ef0.png">

**Comment by kanasimi** [comment]
似乎只有這個作品有這樣的問題，也沒看到什麼可調控的標記。因此這個問題將在網站本身明確標示章節列表為正序和反序之後才處理。

**Comment by gfhghfghfh** [comment]
原來是這樣好的謝謝您
