### ISSUE TITLE
小说下载后打包的epub无法读取问题

### ISSUE THREAD

**Issue by ha7rock** [kanasimi/work_crawler#45]
﻿

* **Version**: 最新版本，安装包方法
* **Interface**: 图形界面

下载源：起点小说
现象：完成后自动打包成了*.epub文件，可是该文件放入ibooks (ipad版本)提示无法打开。

PS: 再次感谢大大添加了manhuadb。另外，可否自行在图形界面中添加新的下载源，我看好像并未同步？谢谢

**Comment by kanasimi** [comment]
不曉得您下載的是哪一本小說呢

**Comment by ha7rock** [comment]
我有试过不同的小说，问题一致。

将epub unpack的话，那些xhtml文件可以正确显示，封面也无法显示

**Comment by ha7rock** [comment]
我尝试了下载calibre，发现epub是可以正常读取和显示的。

用share的功能通过ipad的浏览器打开了，下载后依然显示“格式不正确，无法开启”的错误讯息。

同时也实验了kindle app，发现错误信息是一样的。

**Comment by kanasimi** [comment]
修正了一個 bug:
https://github.com/kanasimi/CeJS/commit/6b329cbee01a3228dbc0769d6ba51900564c1555

不曉得您是不是能再試一下
看看現在同樣的小說
是不是還有問題呢

**Comment by kanasimi** [comment]
若是您還發現什麼錯誤
或者對於所展現的電子書格式有什麼建議的話
歡迎再提出

若是您的問題已經解決
就可以把這個議題關掉了
