### ISSUE TITLE
add dmzj分部

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#451]
﻿

* **Version**: 
* **Interface**: 
* **Arguments**:

**Comment by gfhghfghfh** [comment]
https://manhua.dmzj.com/wojiadenvpuxiaojie/

**Comment by gfhghfghfh** [comment]
順帶一提
目前下載https://manhua.dmzj.com/wojiadenvpuxiaojie/
章節是亂序

<img width="116" alt="tyrytrt" src="https://user-images.githubusercontent.com/42042168/91187737-13c87f80-e723-11ea-970a-48104f2778a0.png">

**Comment by kanasimi** [comment]
因為實際上獲取的是 https://www.dmzj.com/info/wojiadenvpuxiaojie.html

**Comment by gfhghfghfh** [comment]
好的感謝說明
