### ISSUE TITLE
youngaceup和tmca下載失敗

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#452]
﻿

* **Version**: 
* **Interface**: 
* **Arguments**:

**Comment by gfhghfghfh** [comment]
youngaceup下載id  1000143
https://web-ace.jp/youngaceup/contents/1000143/


tmca下載id 2000001
https://web-ace.jp/tmca/contents/2000001/

**Comment by gfhghfghfh** [comment]
都顯示像下方的訊息
gui_electron_functions.js:2639 
process_work_data: 1000143: SyntaxError: Unexpected token b in JSON at position 1
onerror @ gui_electron_functions.js:2639

**Comment by gfhghfghfh** [comment]
都顯示相同的錯誤
gui_electron_functions.js:2639
process_work_data: 1000143: SyntaxError: Unexpected token b in JSON at position 1
onerror @ gui_electron_functions.js:2639

**Comment by kanasimi** [comment]
這邊可正常下載
煩請提供更詳盡的資訊

**Comment by gfhghfghfh** [comment]
很抱歉可能是遇到暫時性的情況
因為當時有在另外用瀏覽器看網站
因為網站有正常顯示誤以為是改版了
