### ISSUE TITLE
下載comic-walker.com報錯

### ISSUE THREAD

**Issue by weekqin** [kanasimi/work_crawler#453]
![image](https://user-images.githubusercontent.com/18532819/92563760-a8e28100-f2aa-11ea-9c59-531a37d9f3c4.png)
在下載https://comic-walker.com/contents/detail/KDCW_CW01000002030000_68/
出現圖中報錯，請問如何處理？謝謝

﻿

* **Version**: 
* **Interface**: 
* **Arguments**:

**Comment by kanasimi** [comment]
請問您說指的是上方編號錯置
或者下方圖片擷取的問題呢

編號的部分屬於警告訊息

圖片擷取的部分
看來重新嘗試4次後仍未能取得圖片
建議從頭重新擷取
應該能補取得圖片

**Comment by weekqin** [comment]
謝謝您的回復！
我在確定了漫畫的地址後，通過軟件的搜索功能能夠找到該漫畫，但卻出現無法提取的情況。
請問您說的從頭提取應該怎麼做呢？上方的預置設定應該如何更改呢？

**Comment by kanasimi** [comment]
> 通過軟件的搜索功能能夠找到該漫畫，但卻出現無法提取的情況。
請問大概是什麼狀況呢
不曉得有沒有出問題時的圖片?

**Comment by weekqin** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "kanasimi"<notifications@github.com&gt;; 
发送时间: 2020年9月9日(星期三) 下午5:02
收件人: "kanasimi/work_crawler"<work_crawler@noreply.github.com&gt;; 
抄送: "Week"<weekqin@foxmail.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [kanasimi/work_crawler] 下載comic-walker.com報錯 (#453)





  
通過軟件的搜索功能能夠找到該漫畫，但卻出現無法提取的情況。
 請問大概是什麼狀況呢
 不曉得有沒有出問題時的圖片?
  
&mdash;

**Comment by kanasimi** [comment]
> 出現無法提取的情況。

請問大概是什麼狀況呢
不曉得有沒有出問題時的圖片與錯誤訊息?

**Comment by weekqin** [comment]
[8:41:10.210]&nbsp;默认下载位置：C:\Users\QK\Downloads\
[.065]&nbsp;欢迎与我们一同翻译界面文字！
[.065]&nbsp;现有1条简体中文讯息尚未翻译，欢迎您一同参与翻译讯息！
開始檢測安裝包更新……{"autoDownload":true,"autoInstallOnAppQuit":true,"currentVersion":{"options":{"loose":false,"includePrerelease":false},"loose":false,"includePrerelease":false,"raw":"v2.9.0","major":2,"minor":9,"patch":0,"prerelease":[],"build":[],"version":"2.9.0"},"channel":null}
[3.68s]&nbsp;import preference of comic.ja-JP/ComicWalker: search_again=false←undefined
[.065]&nbsp;import preference of comic.ja-JP/ComicWalker: acceptable_types=←undefined
[.045]&nbsp;import preference of comic.ja-JP/ComicWalker: archive_images=true←true
[.02]&nbsp;import preference of comic.ja-JP/ComicWalker: timeout=15000←30000
[.02]&nbsp;import preference of comic.ja-JP/ComicWalker: one_by_one=true←undefined
[.04]&nbsp;import preference of comic.ja-JP/ComicWalker: user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) v2.9.0 Chrome/83.0.4103.122 Safari/537.36←Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) v2.9.0 Chrome/83.0.4103.122 Safari/537.36
[.02]&nbsp;import preference of comic.ja-JP/ComicWalker: proxy=127.0.0.1:1080←undefined
ComicWalker:&nbsp;2020/9/10 8:41:15&nbsp;开始处理《機動戰士GUNDAM THE ORIGIN》，储存到 C:\Users\QK\Downloads\ComicWalker\
ComicWalker:&nbsp;已缓存作品 id，不再重新搜寻：機動戰士GUNDAM THE ORIGIN→"KDCW_CW01000002030000_68"
[2.039s]&nbsp;《―激闘篇― SECTION 1》出現章節編號倒置的情況：5 → 1
[.175]&nbsp;《―卡爾馬篇― SECTION 1》出現章節編號倒置的情況：5 → 1
[.185]&nbsp;《―蘭巴・拉爾篇― SECTION 1》出現章節編號倒置的情況：9 → 1
[.12]&nbsp;无法从章节标题《―蘭巴・拉爾篇― SECTION ＥＸ》判断章节序号。依序将章节序号设定为 3。
[.185]&nbsp;《―賈布羅篇― SECTION 1》出現章節編號倒置的情況：9 → 1
[.19]&nbsp;《―夏亞・雪拉篇・上― SECTION 1》出現章節編號倒置的情況：10 → 1
[.19]&nbsp;《―開戰篇・上― SECTION 1》出現章節編號倒置的情況：10 → 1
[.175]&nbsp;《―魯姆篇・上― SECTION 1》出現章節編號倒置的情況：9 → 1
[.17]&nbsp;《―敖得薩篇・上― SECTION 1》出現章節編號倒置的情況：9 → 1
[.255]&nbsp;《―拉拉篇・上― SECTION 1》出現章節編號倒置的情況：12 → 1
KDCW_CW01000002030000_68 [安彥良和,矢立肇,富野由悠季] 機動戰士GUNDAM THE ORIGIN: 77 話.
没有更新。当前程序版本："2.9.0"
get_URL_node:&nbsp;重试 1/4：与 108.160.169.179:443 的连接逾时
get_URL_node:&nbsp;重试 2/4：与 108.160.169.179:443 的连接逾时
[50.972s]&nbsp;使用代理服务器：@127.0.0.1:1080
get_URL_node:&nbsp;重试 3/4：与 108.160.169.179:443 的连接逾时
get_URL_node:&nbsp;重试 4/4：与 108.160.169.179:443 的连接逾时
[54.226s]&nbsp;get_URL_node:&nbsp;获取 [https://ssl.seiga.nicovideo.jp/api/v1/comicwalker/episodes/KDCW_CW01000002030001_68/frames] 出错：与 108.160.169.179:443 的连接逾时
[.63]&nbsp;機動戰士GUNDAM THE ORIGIN: 无法获取第 1 章的内容。
process_chapter_data:&nbsp;重试 1/4...
get_URL_node:&nbsp;重试 1/4：与 108.160.170.26:443 的连接逾时
[27.634s]&nbsp;使用代理服务器：socks5://127.0.0.1:1080
get_URL_node:&nbsp;重试 2/4：与 108.160.170.26:443 的连接逾时
get_URL_node:&nbsp;重试 3/4：与 108.160.170.26:443 的连接逾时
get_URL_node:&nbsp;重试 4/4：与 108.160.170.26:443 的连接逾时
[1:17.569]&nbsp;get_URL_node:&nbsp;获取 [https://ssl.seiga.nicovideo.jp/api/v1/comicwalker/episodes/KDCW_CW01000002030001_68/frames] 出错：与 108.160.170.26:443 的连接逾时
[.13]&nbsp;機動戰士GUNDAM THE ORIGIN: 无法获取第 1 章的内容。
process_chapter_data:&nbsp;重试 2/4...
get_URL_node:&nbsp;重试 1/4：与 108.160.170.26:443 的连接逾时
get_URL_node:&nbsp;重试 2/4：与 108.160.170.26:443 的连接逾时
[45.488s]&nbsp;使用代理服务器：socks5://127.0.0.1:1080/
get_URL_node:&nbsp;重试 3/4：与 108.160.170.26:443 的连接逾时
[32.26s]&nbsp;使用代理服务器：http://127.0.0.1:1080/
get_URL_node:&nbsp;重试 4/4：与 108.160.170.26:443 的连接逾时
[27.419s]&nbsp;get_URL_node:&nbsp;获取 [https://ssl.seiga.nicovideo.jp/api/v1/comicwalker/episodes/KDCW_CW01000002030001_68/frames] 出错：与 108.160.170.26:443 的连接逾时
[.175]&nbsp;機動戰士GUNDAM THE ORIGIN: 无法获取第 1 章的内容。
process_chapter_data:&nbsp;重试 3/4...
[6.271s]&nbsp;使用代理服务器：
get_URL_node:&nbsp;重试 1/4：与 108.160.170.26:443 的连接逾时
get_URL_node:&nbsp;重试 2/4：与 108.160.170.26:443 的连接逾时
get_URL_node:&nbsp;重试 3/4：与 108.160.170.26:443 的连接逾时
get_URL_node:&nbsp;重试 4/4：与 108.160.170.26:443 的连接逾时
[1:38.992]&nbsp;get_URL_node:&nbsp;获取 [https://ssl.seiga.nicovideo.jp/api/v1/comicwalker/episodes/KDCW_CW01000002030001_68/frames] 出错：与 108.160.169.46:443 的连接逾时
[.155]&nbsp;機動戰士GUNDAM THE ORIGIN: 无法获取第 1 章的内容。
process_chapter_data:&nbsp;重试 4/4...
get_URL_node:&nbsp;重试 1/4：与 108.160.169.46:443 的连接逾时
get_URL_node:&nbsp;重试 2/4：与 108.160.169.46:443 的连接逾时
get_URL_node:&nbsp;重试 3/4：与 108.160.169.46:443 的连接逾时
get_URL_node:&nbsp;重试 4/4：与 69.171.234.29:443 的连接逾时
[1:45.146]&nbsp;get_URL_node:&nbsp;获取 [https://ssl.seiga.nicovideo.jp/api/v1/comicwalker/episodes/KDCW_CW01000002030001_68/frames] 出错：与 69.171.234.29:443 的连接逾时
[.135]&nbsp;機動戰士GUNDAM THE ORIGIN: 无法获取第 1 章的内容。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "kanasimi"<notifications@github.com&gt;; 
发送时间: 2020年9月10日(星期四) 凌晨5:41
收件人: "kanasimi/work_crawler"<work_crawler@noreply.github.com&gt;; 
抄送: "Week"<weekqin@foxmail.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [kanasimi/work_crawler] 下載comic-walker.com報錯 (#453)





  
出現無法提取的情況。
  
請問大概是什麼狀況呢
 不曉得有沒有出問題時的圖片與錯誤訊息?
 
&mdash;

**Comment by weekqin** [comment]
[3.68s]&nbsp;import preference of comic.ja-JP/ComicWalker: search_again=false←undefined
[.065]&nbsp;import preference of comic.ja-JP/ComicWalker: acceptable_types=←undefined
[.045]&nbsp;import preference of comic.ja-JP/ComicWalker: archive_images=true←true
[.02]&nbsp;import preference of comic.ja-JP/ComicWalker: timeout=15000←30000
[.02]&nbsp;import preference of comic.ja-JP/ComicWalker: one_by_one=true←undefined
[.04]&nbsp;import preference of comic.ja-JP/ComicWalker: user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) v2.9.0 Chrome/83.0.4103.122 Safari/537.36←Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) v2.9.0 Chrome/83.0.4103.122 Safari/537.36
[.02]&nbsp;import preference of comic.ja-JP/ComicWalker: proxy=127.0.0.1:1080←undefined
ComicWalker:&nbsp;2020/9/10 8:41:15&nbsp;開始處理《機動戰士GUNDAM THE ORIGIN》，儲存到 ***
ComicWalker:&nbsp;已緩存作品 id，不再重新搜尋：機動戰士GUNDAM THE ORIGIN→"KDCW_CW01000002030000_68"
[2.039s]&nbsp;《―激闘篇― SECTION 1》出現章節編號倒置的情況：5 → 1
[.175]&nbsp;《―卡爾馬篇― SECTION 1》出現章節編號倒置的情況：5 → 1
[.185]&nbsp;《―蘭巴・拉爾篇― SECTION 1》出現章節編號倒置的情況：9 → 1
[.12]&nbsp;無法從章節標題《―蘭巴・拉爾篇― SECTION ＥＸ》判斷章節序號。依序將章節序號設定為 3。
[.185]&nbsp;《―賈布羅篇― SECTION 1》出現章節編號倒置的情況：9 → 1
[.19]&nbsp;《―夏亞・雪拉篇・上― SECTION 1》出現章節編號倒置的情況：10 → 1
[.19]&nbsp;《―開戰篇・上― SECTION 1》出現章節編號倒置的情況：10 → 1
[.175]&nbsp;《―魯姆篇・上― SECTION 1》出現章節編號倒置的情況：9 → 1
[.17]&nbsp;《―敖得薩篇・上― SECTION 1》出現章節編號倒置的情況：9 → 1
[.255]&nbsp;《―拉拉篇・上― SECTION 1》出現章節編號倒置的情況：12 → 1
KDCW_CW01000002030000_68 [安彥良和,矢立肇,富野由悠季] 機動戰士GUNDAM THE ORIGIN: 77 話.
沒有更新。當前程式版本："2.9.0"
get_URL_node:&nbsp;重試 1/4：與 108.160.169.179:443 的連接逾時
get_URL_node:&nbsp;重試 2/4：與 108.160.169.179:443 的連接逾時
[50.972s]&nbsp;使用代理伺服器：@127.0.0.1:1080
get_URL_node:&nbsp;重試 3/4：與 108.160.169.179:443 的連接逾時
get_URL_node:&nbsp;重試 4/4：與 108.160.169.179:443 的連接逾時
[54.226s]&nbsp;get_URL_node:&nbsp;獲取 [https://ssl.seiga.nicovideo.jp/api/v1/comicwalker/episodes/KDCW_CW01000002030001_68/frames] 出錯：與 108.160.169.179:443 的連接逾時
[.63]&nbsp;機動戰士GUNDAM THE ORIGIN: 無法獲取第 1 章的內容。
process_chapter_data:&nbsp;重試 1/4...
get_URL_node:&nbsp;重試 1/4：與 108.160.170.26:443 的連接逾時
[27.634s]&nbsp;使用代理伺服器：socks5://127.0.0.1:1080
get_URL_node:&nbsp;重試 2/4：與 108.160.170.26:443 的連接逾時
get_URL_node:&nbsp;重試 3/4：與 108.160.170.26:443 的連接逾時
get_URL_node:&nbsp;重試 4/4：與 108.160.170.26:443 的連接逾時
[1:17.569]&nbsp;get_URL_node:&nbsp;獲取 [https://ssl.seiga.nicovideo.jp/api/v1/comicwalker/episodes/KDCW_CW01000002030001_68/frames] 出錯：與 108.160.170.26:443 的連接逾時
[.13]&nbsp;機動戰士GUNDAM THE ORIGIN: 無法獲取第 1 章的內容。
process_chapter_data:&nbsp;重試 2/4...
get_URL_node:&nbsp;重試 1/4：與 108.160.170.26:443 的連接逾時
get_URL_node:&nbsp;重試 2/4：與 108.160.170.26:443 的連接逾時
[45.488s]&nbsp;使用代理伺服器：socks5://127.0.0.1:1080/
get_URL_node:&nbsp;重試 3/4：與 108.160.170.26:443 的連接逾時
[32.26s]&nbsp;使用代理伺服器：http://127.0.0.1:1080/
get_URL_node:&nbsp;重試 4/4：與 108.160.170.26:443 的連接逾時
[27.419s]&nbsp;get_URL_node:&nbsp;獲取 [https://ssl.seiga.nicovideo.jp/api/v1/comicwalker/episodes/KDCW_CW01000002030001_68/frames] 出錯：與 108.160.170.26:443 的連接逾時
[.175]&nbsp;機動戰士GUNDAM THE ORIGIN: 無法獲取第 1 章的內容。
process_chapter_data:&nbsp;重試 3/4...
[6.271s]&nbsp;使用代理伺服器：
get_URL_node:&nbsp;重試 1/4：與 108.160.170.26:443 的連接逾時
get_URL_node:&nbsp;重試 2/4：與 108.160.170.26:443 的連接逾時
get_URL_node:&nbsp;重試 3/4：與 108.160.170.26:443 的連接逾時
get_URL_node:&nbsp;重試 4/4：與 108.160.170.26:443 的連接逾時
[1:38.992]&nbsp;get_URL_node:&nbsp;獲取 [https://ssl.seiga.nicovideo.jp/api/v1/comicwalker/episodes/KDCW_CW01000002030001_68/frames] 出錯：與 108.160.169.46:443 的連接逾時
[.155]&nbsp;機動戰士GUNDAM THE ORIGIN: 無法獲取第 1 章的內容。
process_chapter_data:&nbsp;重試 4/4...
get_URL_node:&nbsp;重試 1/4：與 108.160.169.46:443 的連接逾時
get_URL_node:&nbsp;重試 2/4：與 108.160.169.46:443 的連接逾時
get_URL_node:&nbsp;重試 3/4：與 108.160.169.46:443 的連接逾時
get_URL_node:&nbsp;重試 4/4：與 69.171.234.29:443 的連接逾時
[1:45.146]&nbsp;get_URL_node:&nbsp;獲取 [https://ssl.seiga.nicovideo.jp/api/v1/comicwalker/episodes/KDCW_CW01000002030001_68/frames] 出錯：與 69.171.234.29:443 的連接逾時
[.135]&nbsp;機動戰士GUNDAM THE ORIGIN: 無法獲取第 1 章的內容。


通過軟件的搜索功能能夠找到該漫畫，但卻出現無法提取的情況。
請問大概是什麼狀況呢
基本上就是能夠找到章節甚至建立了資料夾，但一直提示連接逾時

**Comment by kanasimi** [comment]
這邊下載正常
猜測有可能是翻牆的原因?
您可以試試看 one_by_one 這個選項

**Comment by weekqin** [comment]
請問若要配合本地的ss用戶端使用，代理伺服器應該怎麼填寫呢？直接寫127.0.0.1:埠，這樣嘛？

**Comment by kanasimi** [comment]
是的 應該這樣使用proxy
