### ISSUE TITLE
在oh漫画下载电锯人的后几话出错

### ISSUE THREAD

**Issue by kuondayo** [kanasimi/work_crawler#456]
* **Version**: 2.9.0，懒人安装，windows版
* **Interface**: 图形界面
* **Arguments**:作品地址 https://www.laimanhua.com/kanmanhua/35939

在默认情况，指定开始的ID为1时，前几话可以正常下载
但当指定ID为最新的几话时，开始报错404，下载的图片全部都是bad档

**Comment by kanasimi** [comment]
Duplicate #454 
將在下一版修復

**Comment by kanasimi** [comment]
Duplicate of #454

**Comment by kuondayo** [comment]
更新一下，之前的反馈有错误
当指定最新几话的ID出现错误的网站是漫画160，网页：https://www.laimanhua.com/kanmanhua/35939

而oh漫画也有错误，下载电锯人时出现Malformed UTF-8 data，网页：https://www.cocomanhua.com/15624/1/88.html

**Comment by kanasimi** [comment]
fixed in https://github.com/kanasimi/work_crawler/commit/e0f5a5ff02ac0601a05209591ee2787a8c794337
