### ISSUE TITLE
更正之前反馈漫画下载错误的网站名

### ISSUE THREAD

**Issue by kuonji-arisu** [kanasimi/work_crawler#457]
* **Version**: 2.9.0，懒人安装，windows版
* **Interface**: 图形界面
* **Arguments**: 

更新一下，之前的反馈有错误
当电锯人指定从最新几话的ID开始下载出现错误的网站是漫画160，而不是oh漫画，网页：https://www.laimanhua.com/kanmanhua/35939

而oh漫画也有错误，下载电锯人时出现Malformed UTF-8 data，网页：https://www.cocomanhua.com/15624/1/88.html

**Comment by kanasimi** [comment]
fixed in https://github.com/kanasimi/work_crawler/commit/e0f5a5ff02ac0601a05209591ee2787a8c794337
