### ISSUE TITLE
增加网站请求：tonarinoyj.jp

### ISSUE THREAD

**Issue by ha7rock** [kanasimi/work_crawler#46]
站点地址：https://tonarinoyj.jp

有研究了一下这站点的阅读器，发现它也不是直接读取图片的。

应该不是很好爬……所以可能只能是自己的碎碎念

anyway,感谢m(_~_)m

**Comment by kanasimi** [comment]
和 #32 相同
因為圖片經過特殊處理
這邊沒有打算要增加此類型網站
