### ISSUE TITLE
请求增加网站-拷贝漫画网 https://copymanga.com

### ISSUE THREAD

**Issue by sxji** [kanasimi/work_crawler#462]
另外希望将看漫画(https://www.manhuagui.com/)的地址更新为(https://www.mhgui.com/)，劳烦了。

**Comment by kanasimi** [comment]
https://www.manhuagui.com/ 看來還能用?

**Comment by sxji** [comment]
> https://www.manhuagui.com/ 看來還能用?

大概是因为墙的关系，内陆这边用不了了……

**Comment by sxji** [comment]
顺便请求新增-嗨皮漫画网 https://m.happymh.com/

**Comment by sxji** [comment]
@kanasimi
