### ISSUE TITLE
从Oh漫画网下载时报错

### ISSUE THREAD

**Issue by sxji** [kanasimi/work_crawler#463]
报错内容：
Error: Malformed UTF-8 data

尝试多部漫画依旧如此

**Comment by kanasimi** [comment]
這家的key已經改兩次了...

**Comment by UJohn** [comment]
这家的漫画经常改域名，如果能出个配置文件自己修改漫画地址就好了

**Comment by kanasimi** [comment]
您可以回報問題
這邊統一更改
能造福更多人 😄
