### ISSUE TITLE
bilibili進度條標題連結出錯

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#467]
﻿

* **Version**: 
* **Interface**: 
* **Arguments**:

**Comment by gfhghfghfh** [comment]
點擊進度條標題後出現下方紅字訊息
<img width="585" alt="未命名" src="https://user-images.githubusercontent.com/42042168/102320331-1b07e780-3fb7-11eb-8c52-4869ec612138.png">

**Comment by gfhghfghfh** [comment]
@kanasimi 
<img width="164" alt="dft" src="https://user-images.githubusercontent.com/42042168/102515246-7675ca80-40c8-11eb-997a-60cae7820821.png">
修正完變成沒有連結
請問是正常的嗎

**Comment by kanasimi** [comment]
正常的
因為程式使用的是 JSON 作品資料
對於一些需要 POST 取得 JSON 作品資料的作品，
就算連結到 JSON
人類也看不懂
