### ISSUE TITLE
部分作品无法下载（manhuadb.com）

### ISSUE THREAD

**Issue by ha7rock** [kanasimi/work_crawler#47]
下载部分作品时候会出现错误讯息如下：

e.g:
> manhuadb: 2018-08-11T09:01:00.040Z Starting 美女强盗团, 儲存至 manhuadb\
manhuadb: Find cache: 美女强盗团→"1236"
1236 美女强盗团: **Can not get chapter count!**

源网站：manhuadb.com

**Comment by ha7rock** [comment]
> manhuadb: 2018-08-11T10:36:54.239Z Starting 美女条子, 儲存至 manhuadb\
manhuadb: Find cache: 美女条子→"1237"
1237 美女条子: Can not get chapter count!

更新后前述作品ok，但另一作品也有同样问题……

**Comment by kanasimi** [comment]
請再試試看

**Comment by ha7rock** [comment]
目前测试均通过，辛苦您。
