### ISSUE TITLE
仓库地址是不是不对了。

### ISSUE THREAD

**Issue by moment3784** [kanasimi/work_crawler#470]
懒人安装法说明中，work_crawler.updater.js 下载不到的，里面有个地址是不是失效了呢

**Comment by kanasimi** [comment]
能麻煩您貼上錯誤訊息和下載狀況嗎?
這樣比較能清楚狀況

**Comment by moment3784** [comment]
懒人安装法说明简体中文文档第二点，work_crawler.updater.js 那个链接下载不了.

**Comment by kanasimi** [comment]
會不會是被牆了 ?

**Comment by moment3784** [comment]
可以了~
