### ISSUE TITLE
toomics.com VIP會員瀏覽功能

### ISSUE THREAD

**Issue by nqianaaron** [kanasimi/work_crawler#471]
您好：
请问下toomic.com是否失效了。搜不到任何漫画。另外这个网站获取的cookie有三个set-cookie，不知道要添加哪一个。能否在read.me里面指导一下。
使用的是Releases 里面CeJS online work crawler v2.10.0  系统是win10 64位。圖形介面
期待您的回复。

**Comment by kanasimi** [comment]
請問您下載的是哪個作品呢
這邊似乎還能找到作品

Cookie的部分您可試試三個連在一起
用 `;` 分隔

**Comment by nqianaaron** [comment]
太感謝您的回復了。但是我是在toomic中，任何書籍我都搜索不到。不知道是不是我獲取的cookie不對。嘗試用；連接三個set-cookie也還是搜索不到。麻煩能再指導一下如何獲取toomic的cookie嗎？我已經購買了他們的VIP。應該是全站都能看的了

**Comment by nqianaaron** [comment]
另外麻煩在咨詢一下，開了他們的vip能否下載裡面的VIP內容呢？

**Comment by kanasimi** [comment]
請問您在另一台沒有設定cookie的電腦中是否可搜尋得到呢
VIP的部分若是可搜尋得到，您可以嘗試看看可否下載。這邊沒有會員資格，因此沒辦法幫您做測試。抱歉。

**Comment by nqianaaron** [comment]
我嘗試一共使用了三台電腦並且是不同網絡。也試過不用cookie，但是都沒有辦法搜索到，大佬能否提供一個郵箱或者其他聯繫方式，我可以免費提供vip賬號，供您測試。

**Comment by kanasimi** [comment]
這邊換了電腦做測試發現依舊無法重現問題
您能貼出您所遇到的錯誤訊息與畫面嗎
謝謝

**Comment by nqianaaron** [comment]
感謝您的回復，我嘗試使用全局代理，在不添加cookie的情況下，能搜索到toomics的免費漫畫了。
另外您能否提供一個郵箱地址，我把toomic的vip賬號發送給您，能否麻煩測試一下，是否可以獲取vip的章節？

**Comment by kanasimi** [comment]
所以看起來是代理的問題
請問您在使用全取代理的情況下
有辦法下載vip的章節嗎

**Comment by nqianaaron** [comment]
您好，首先我在沒有使用cookie的情況下，能搜索到toomics的漫畫了，但是祇有免費章節。其次我登陸了我的vip賬號，嘗試獲取cookie之後在搜索，但是都失敗了，還是衹能搜索到免費章節。我不太會獲取這個cookie。不知道是不是cookie的問題。所以我想免費提供我的vip賬號給你，供您測試。

**Comment by kanasimi** [comment]
看起來VIP會員與免費瀏覽採用了不同的機制
免費的功能正常
VIP瀏覽的部分則完全沒功用

不過因為這邊就算一時能將VIP瀏覽的功能做出來
也不可能長期維護
因此沒有打算要寫VIP瀏覽的功能
非常抱歉

**Comment by nqianaaron** [comment]
感謝回復，不是很了解裡面的機制。也行機制應該是一樣的。只是加了一個限制。例如需要登陸之後。
個人理解：是否是因為沒有添加cookie的原因，所以只能獲取到免費的。
如果登陸vip之後，獲取了cookie，是否可以獲取vip章節。
由於我不是很了解怎麼獲取登陸後的cookie，所以想提供賬號給你們測試一下。
