### ISSUE TITLE
comico_jp部分id圖檔類型問題

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#477]
﻿

* **Version**: 
* **Interface**: 
* **Arguments**:

**Comment by gfhghfghfh** [comment]
這邊測試的是日版的comico的challenge的作品
https://www.comico.jp/challenge/articleList.nhn?titleNo=31152

這邊透過將MIN_LENGTH調成很大的值來查看程式下載的圖片網址

發現此網址末端皆顯示jpg
但當MIN_LENGTH為預設值時下載到的圖片全為png


有測試其他官方和challenge的作品
似乎只有id 31152 有此情況

可以請教被存成png原因嗎

**Comment by gfhghfghfh** [comment]
這邊測試的是日版的comico的challenge的作品
https://www.comico.jp/challenge/articleList.nhn?titleNo=31152

這邊透過將MIN_LENGTH調成很大的值來查看程式下載的圖片網址

發現此網址末端皆顯示jpg
但當MIN_LENGTH為預設值時下載到的圖片全為png


有測試其他官方和challenge的作品
似乎只有id 31152 有此情況


如果這是bug的話
可以請教被存成png原因嗎

**Comment by kanasimi** [comment]
副檔名是JPG
但實際上格式是png
因此自動改成正確的副檔名了

**Comment by gfhghfghfh** [comment]
請問可以請教如何查看圖片的實際格式嗎
謝謝您

**Comment by kanasimi** [comment]
您可以試試 XnView
https://www.xnview.com/en/
