### ISSUE TITLE
无法使用recheck指令？

### ISSUE THREAD

**Issue by ha7rock** [kanasimi/work_crawler#48]
在使用manhuadb.js进行下载时，设置了recheck命令 (目的是跳过之前已经存在的图片档案进行增量下载，不知这样**是不是正确**的方式？) 但程式反馈recheck未定义，于是就会从头开始下载……

> node .\manhuadb.js "l=mhdb2.txt" recheck=true
   **recheck: undefined**
由命令列 → true
manhuadb: 2018-08-12T06:40:11.604Z Starting l=mhdb2.txt, 儲存至 manhuadb\

**Comment by kanasimi** [comment]
**recheck: undefined**
由命令列 → true

上面這一段的意思是
原先沒有設定recheck
但是由命令列手動指定了recheck
因此會執行這個功能，從頭開始下載

recheck:
從頭檢測所有作品之所有章節與所有圖片。不會重新擷取圖片。對漫畫應該僅在偶爾需要從頭檢查時開啟此選項。default:false

**Comment by kanasimi** [comment]
基本上不用加recheck就會從中斷的地方重新下載
加recheck會重頭檢查

**Comment by ha7rock** [comment]
收到，感谢答疑！
