### ISSUE TITLE
哔哩哔哩漫画 異常 HTTP 狀態碼 412

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#484]
﻿

* **Version**: 
* **Interface**: 
* **Arguments**:

**Comment by gfhghfghfh** [comment]
大概是改版了
[⚠][19.503s] get_URL_node: 異常 HTTP 狀態碼 412：https://manga.bilibili.com/twirp/comic.v1.Comic/ComicDetail?device=h5&platform=h5
[☠][60.48] get_URL_node: 獲取 [https://manga.bilibili.com/twirp/comic.v1.Comic/ComicDetail?device=h5&platform=h5] 出錯：BAD STATUS

**Comment by gfhghfghfh** [comment]
SyntaxError: Unexpected token < in JSON at position 0

**Comment by kanasimi** [comment]
請問出錯的漫畫標題是?

**Comment by gfhghfghfh** [comment]
因為當時是隨便找的ID都不行,也換過設備,或許又是暫時性問題
但是現在我更新完程式後變成無法使用
https://github.com/kanasimi/work_crawler/issues/489
目前無法再次測試
請問能給予協助嗎

**Comment by kanasimi** [comment]
#489 is fixed
