### ISSUE TITLE
如何修改预设的文件夹名和图片名？

### ISSUE THREAD

**Issue by nakamiv** [kanasimi/work_crawler#486]
使用中的一个小疑问？可以修改下载文件夹的名字和图片名吗？
例如默认下载的章节文件夹名是 自加序号+章节名，图片默认名字是  漫画id+章节id+图片自加序号.jpg

可以去哪里修改吗？ 比如文件夹名字我就使用章节名字，图片我只需要  自加序号.jpg?

不知道有没有说清楚... 比如章节文件夹：0001 我是第一章， 只使用 我是第一章 
                                    比如图片： 9999-1-001.jpg  , 只是用  001 作为图片名。

这个可以改吗？

**Comment by kanasimi** [comment]
這個現在寫死在 chapter.js 與 work.js 裡面
若是要改的話
怕也會有要採用哪種 pattern 的問題

不曉得您現在主要的困擾是...?

**Comment by nakamiv** [comment]
没什么问题，就是好奇这个可不可以自定义。如果比较麻烦就算啦。谢谢回复。
