### ISSUE TITLE
乙女漫畫改域名

### ISSUE THREAD

**Issue by auntesaunt123** [kanasimi/work_crawler#487]
nokiacn.js 乙女漫畫改域名了?

 http://www.nokiacn.net/ 到 https://www.yinvmh.com

謝謝您的好工具

**Comment by kanasimi** [comment]
這個網站好像直接消失了?

**Comment by auntesaunt123** [comment]
https://www.yinvmh.com 應該是新的域名 (網站名還是掛乙女漫畫)
現在圖片位址 http://img.yinvmh.com/upload2/693/2021/01-18/20210118112845_9214nwerpAne_small.Jpeg
(但是我測試http://n.aiwenwo.net//upload2/693/2021/01-18/20210118112845_9214nwerpAne_small.Jpeg 也是一樣能開)
我看您腳本裡有過去位址範例 http://n.aiwenwo.net:55888/upload2/1774/2018/03-17/20180317232906_4691cbjowu29a_small.jpeg
(目前網站可能防查<某國兩會??>，圖片我都是用外掛程式才找的到連結.)

**Comment by auntesaunt123** [comment]
我是用 chrome  不過 這網站目前 漫畫圖片不能正常顯示?  

我要開圖片助手(imageassistant) 這個插件才能抓到連結

如 進了這個連結 https://www.yinvmh.com/yinv/baozhuzheshigeyijinyueye/1200.html?p=2 第二頁

用插件 "提取本頁圖片" 找連結

http://img.yinvmh.com/upload2/1774/2018/03-17/20180317234007_6579lp40r17ko17_small.jpg

不過https://www.yinvmh.com 這個連結我是沒遇到問題

**Comment by kanasimi** [comment]
看起來似乎是名稱相同
但內容不同的另一個網站了
