### ISSUE TITLE
大大，请问怎么设置下载时自动压缩成zip格式

### ISSUE THREAD

**Issue by niuqudechongdong** [kanasimi/work_crawler#488]
﻿我之前下载时记得是可以自动压缩成zip格式的，但是我现在把image_archive_extension设置成zip发现还是好像不会压缩成zip格式

请问大大怎么设置参数才可以在下载时会自动压缩每一章节？

**Comment by kanasimi** [comment]
是不是沒有選擇 `archive_images` 這一項?

**Comment by niuqudechongdong** [comment]
这一项前面有打钩了，不知道为什么不能压缩

**Comment by niuqudechongdong** [comment]
我知道了。是因为“archive_program_path:”这一项出错了，我用的是懒人安装法安装的，这一项应该是自动填写的，不知道为什么会出现这种情况。

出错原因：
C:\Program Files\WinRAR\rar.exe"中的rar.exe弄错了，应该是Rar.exe才对（安装本软件时，调用了电脑自带的rar软件，但调用错误）

**Comment by kanasimi** [comment]
照理來說Windows下的程式應該不分檔名大小寫
你能找到錯誤訊息post上來嗎

不曉得您的程式是按照預設安裝嗎
或者有另外改過路徑呢

**Comment by niuqudechongdong** [comment]
我忘记安装7z程序了，应该是这个原因

我已经把程序卸载了重新安装，错误信息也没有了
我没有改过路径，因为刚才时，我也不知道那个参数是干啥的，我用的懒人安装法
（发现好像只有先安装7Z程序才能正常压缩，电脑自带的rar程序好像没什么用）

**Comment by kanasimi** [comment]
這邊只用7z測試
雖然也有為Winrar寫功能 不過未保證能用

假如問題解決的話
麻煩請關閉此議題
