### ISSUE TITLE
懶人安裝圖形介面無法使用

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#489]
﻿

* **Version**: 
* **Interface**: 
* **Arguments**:

**Comment by gfhghfghfh** [comment]
刪掉work_crawler-master資料夾後重新下載後
變成下圖的狀況
<img width="343" alt="DFSD" src="https://user-images.githubusercontent.com/42042168/109989460-79856c00-7d43-11eb-80d9-abf7330242dc.png">

**Comment by gfhghfghfh** [comment]
不好意思
刪掉work_crawler-master資料夾後重新下載後
似乎還是一樣

**Comment by kanasimi** [comment]
fixed at https://github.com/kanasimi/CeJS/commit/139975e6b6c3af24012626c1a3d86a8ff7e65a92
