### ISSUE TITLE
求助：AppImage在Debian 9 VPS运行失败

### ISSUE THREAD

**Issue by ha7rock** [kanasimi/work_crawler#49]
﻿

* **Version**: work_crawler-1.4.20180714-x86_64.AppImage
* **Interface**:  终端（Debian 9  ）

>root@Myvps:/manga# chmod a+x work_crawler-1.4.20180714-x86_64.AppImage 
root@Myvps:/manga# ./work_crawler-1.4.20180714-x86_64.AppImage 
desktop-file-install is missing. Skipping /tmp/.mount_work_cA0ubF0/AppRun. /tmp/.mount_work_cA0ubF0/work_crawler: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory

不知运行AppImage在VPS上，还有什么必要步骤和准备工作，谢谢指教

**Comment by kanasimi** [comment]
不知道這能不能幫到您:
https://github.com/cazala/coin-hive/issues/22
https://github.com/cazala/coin-hive/issues/9#issuecomment-330260973

Note that after the npm install you may need some dependencies :
`sudo apt-get install libgtk-3-0 libgconf-2-4 libpangocairo-1.0-0 chromium chromium-browser chromium-bsu`

**Comment by ha7rock** [comment]
安装了libasound2后，我安装了deb，并且AppImage也可以执行了。

> root@Myvps:/opt# work_crawler
> 
> (work_crawler:2460): Gtk-WARNING **: cannot open display:

难道linux版本反而不能运行于命令行模式？

**Comment by kanasimi** [comment]
> 难道linux版本反而不能运行于命令行模式？

不曉得您在執行命令行模式的時候
會出現什麼錯誤訊息嗎

**Comment by ha7rock** [comment]
> (work_crawler:2460): Gtk-WARNING **: cannot open display:

就是提示这个，我没办法找到像Windows下面的类似档案夹和结构，在/opt/下面找到work_crawler的档案夹，可里面的档案和Windows也是不同的

**Comment by kanasimi** [comment]
這邊先釐清一下問題
看起來您想要用執行安裝包
在命令行底下執行安裝包
但是開不起來
出現了這樣的錯誤
> (work_crawler:2460): Gtk-WARNING **: cannot open display:
這邊測試採用的是 Linux Mint-18.3
很抱歉沒辦法重現您的問題

Debian 的話
或許使用 work_crawler_1.4.20180714_amd64.deb or work_crawler_1.4.20180714_i386.deb 會比較好?

不曉得您有試過命令列模式嗎
> node 工具檔名.js "作品名" [option=true] [option=value]

**Comment by ha7rock** [comment]
是的，因为AppImage执行有问题。

我就 install 了 work_crawler_1.4.20180714_amd64.deb 的pkg，成功（没有错误讯息）后执行 work_crawler 就出现上述错误了。我找不到 *.js  的位置

**Comment by kanasimi** [comment]
你也許可參考
https://superuser.com/questions/310676/where-do-packages-get-installed-in-debian-systems
``dpkg -L work_crawler``
來了解檔案安裝到哪了

依照錯誤訊息
看起來或許是 process.stdout.write() 出了問題??
但是因為這邊沒有辦法做測試
所以也無法確認

**Comment by ha7rock** [comment]
嗯，我有用这个指令找到程式的档案夹的。

但是根据错误提示的讯息，是不是因为打不开electron的gui才报错呢？

**Comment by kanasimi** [comment]
用這個方法不知道有沒有效呢
https://blog.csdn.net/IcePrincess_1968/article/details/79941540

命令行退出root後，用當前賬戶執行命令
xhost + 是使所有用戶都能訪問Xserver 
xhost + ip 是使所有ip用戶都能訪問Xserver

**Comment by ha7rock** [comment]
嗯，因为大大您没有开发环境也是没有办法的事情。

目前看来linux版本暂时没办法用哦。（我刚才有准备安装一个远程桌面，但是转念一想，就是因为图形界面版没什么效率才会想用性能比较好，又可以无人值守的虚拟伺服器安装）

**Comment by kanasimi** [comment]
想要效率高一點的話
用命令行介面應該會比較好
不曉得您那邊環境下的命令行見面可不可以用呢
> node 工具檔名.js "作品名" [option=true] [option=value]

**Comment by kanasimi** [comment]
非常感謝您的測試
不曉得您那邊環境下可
不可以使用懶人安裝法呢
https://github.com/kanasimi/work_crawler#lazy-installation-%E6%87%B6%E4%BA%BA%E5%AE%89%E8%A3%9D%E6%B3%95

**Comment by ha7rock** [comment]
我是这样想的，大大您的教程是按照win环境去写的。

因此我不确定其中跨平台所涉的档案路径path等是否通用。

比如大大在下载完成后利用7zip自动打包的动作，不同的OS作业系统肯定大相径庭。

**Comment by kanasimi** [comment]
這邊在 Linux Mint-18.3 下測試的時候可以使用

若是您採用懶人安裝法安裝
https://github.com/kanasimi/work_crawler#lazy-installation-%E6%87%B6%E4%BA%BA%E5%AE%89%E8%A3%9D%E6%B3%95
執行的時候發生困難
可以馬上回報一下
我也許能想辦法解決 😃

**Comment by ha7rock** [comment]
啊———— （扶墙...

按照您的windows安装的方案，将档案上传至VPS，然后按照windows的方案执行就可以了……

现在正在等待测试下载完成之后的zip打包动作……

（AppImage和Deb都有点误导了啊—— T-T）

**Comment by kanasimi** [comment]
麻煩您執行一下下面幾個命令
並且貼一下輸出
看看要怎麼找到 7z 執行檔
<code>
echo $PATH
which 7z
which p7z
</code>
若是您知道要用哪個指令來執行7z
也麻煩您回覆一下
謝謝

**Comment by ha7rock** [comment]
```
程式位置：/usr/bin/7z

Usage: 7z <command> [<switches>...] <archive_name> [<file_names>...]
       [<@listfiles...>]

<Commands>
  a : Add files to archive
  b : Benchmark
  d : Delete files from archive
  e : Extract files from archive (without using directory names)
  h : Calculate hash values for files
  i : Show information about supported formats
  l : List contents of archive
  rn : Rename files in archive
  t : Test integrity of archive
  u : Update files to archive
  x : eXtract files with full paths
```

**Comment by ha7rock** [comment]
> root@MYVPS:/# echo $PATH
> /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

执行node只会进入等待输入状态

> root@MYVPS:/# node
> **>**

> root@MYVPS:/# console.log(process.env.PATH);
> bash: syntax error near unexpected token `process.env.PATH'

**Comment by kanasimi** [comment]
這程式是該改沒錯
等改完了再麻煩您試試

**Comment by ha7rock** [comment]
真是辛苦您了，忠心感谢

**Comment by ha7rock** [comment]
UPDATE:

昨天之后在VPS下载完成的作品全部有打包完成……可能也不需要修正啦
