### ISSUE TITLE
詢問本工具只能下載特定幾種圖片類型

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#490]
﻿

* **Version**: 
* **Interface**: 
* **Arguments**:

**Comment by gfhghfghfh** [comment]
acceptable_types
提到本工具只能下載特定幾種圖片類型
請問一下所有支援的圖片類型是那些

**Comment by kanasimi** [comment]
@see Magic_number @ https://github.com/kanasimi/CeJS/blob/master/application/storage/file.js

**Comment by gfhghfghfh** [comment]
請問使用acceptable_types時
輸入jpg會包含jpeg嗎
還是需要另外再輸入jpeg(像是這樣acceptable_types:jpeg|jpg)

**Comment by kanasimi** [comment]
acceptable_types: 圖片類別副檔名
需要另外再輸入jpeg(像是這樣acceptable_types:jpeg|jpg)

**Comment by gfhghfghfh** [comment]
請問輸入先後順序是不會影響吧?
像是webp|jpg|jpeg|png=jpg|jpeg|png|webp=jpg|png|webp|jpeg

**Comment by kanasimi** [comment]
應該是不會影響的，因為會先判別圖片的種類，再看看是不是在可允許的範圍內。
