### ISSUE TITLE
允许下载部分章节

### ISSUE THREAD

**Issue by poly000** [kanasimi/work_crawler#493]
﻿

* **Version**:  安裝包
* **Interface**: 图形界面
* **Arguments**: 

我希望下载136以后的章节 但是只看到全部开始下载

**Comment by kanasimi** [comment]
您可以使用設定 `start_chapter_NO` 來做到這一點

**Comment by poly000** [comment]
> 
> 
> 您可以使用設定 `start_chapter_NO` 來做到這一點

需要使用TUI吗？

**Comment by gfhghfghfh** [comment]
https://camo.githubusercontent.com/e48d0b1056372e490f826e04e64be99c91dbcb161da523ff1b3e3381c010cc03/68747470733a2f2f6c68332e676f6f676c6575736572636f6e74656e742e636f6d2f754555722d695973314a4b6f5a756b61723434734f7178534c393038755054536a5347346544636f2d4f3862466a6a49466b78535273507932554d6b636e49335a3748666e2d7a5a32776445394f6a52723143515a735f44666f476a764a4c42436f526739673447482d4a7847395a7077543866583873726e3935386a427a4a7a4e6257634d766449673d7732343030

**Comment by gfhghfghfh** [comment]
調整下載選項裡的start_chapter
