### ISSUE TITLE
[Help Wanted] 可以使用代理吗/漫画柜无法搜索

### ISSUE THREAD

**Issue by poly000** [kanasimi/work_crawler#494]
﻿

* **Version**: 安装包
* **Interface**: 图形界面
* **Arguments**: 17332

漫画柜搜索 本網站強制等待時間過長，為防封鎖不作搜尋

**Comment by kanasimi** [comment]
這個網站用代理也是一樣的，因為他是看瀏覽間隔來封鎖IP。即使用瀏覽器觀看，手速太快一樣會被封。

**Comment by poly000** [comment]
> 
> 
> 這個網站用代理也是一樣的，因為他是看瀏覽間隔來封鎖IP。即使用瀏覽器觀看，手速太快一樣會被封。

手动进行延迟可以解决吗？

**Comment by poly000** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/src/zh/manhuagui/src/eu/kanade/tachiyomi/extension/zh/manhuagui/Manhuagui.kt

**Comment by kanasimi** [comment]
這邊嘗試了很久才使用這樣的時間間隔
時間調整太短的話
就算一開始幾分鐘還能下載
幾10分鐘之後還是會被封鎖
而且一次封鎖就封鎖一整天

您若是想要調整下載速度
可以直接更改 chapter_time_interval
