### ISSUE TITLE
顯示CeL.application.net: 採用 CeL.character.decode_URI_component

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#496]
﻿

* **Version**: 
* **Interface**: 
* **Arguments**:

**Comment by gfhghfghfh** [comment]
請問顯示CeL.application.net: 採用 CeL.character.decode_URI_component
是代表出甚麼問題嗎

**Comment by kanasimi** [comment]
這是正常的訊息
不曉得您想要的結果是?

**Comment by gfhghfghfh** [comment]
因為以前不會出現
所以不太確定是甚麼
可以請問出現的時機嗎

**Comment by kanasimi** [comment]
採用非unicode編碼時就會出現
