### ISSUE TITLE
无法正常更新 - 使用socks的proxy

### ISSUE THREAD

**Issue by Fiend1019** [kanasimi/work_crawler#497]
![QQ图片20210404204052](https://user-images.githubusercontent.com/64277417/113509172-af0db700-9586-11eb-98f2-7f5b29442f88.png)
使用懒人安装法安装的，但是无法进行更新，重新安装也会失败

**Comment by kanasimi** [comment]
或許是因為被牆堵住了? 之前有些人用proxy可以成功更新
請問您之前有成功更新過嗎?

**Comment by Fiend1019** [comment]
![QQ图片20210405072829](https://user-images.githubusercontent.com/64277417/113524927-83211e80-95e4-11eb-9728-926bd6905674.png)
之前成功更新过的，用proxy同样的提示。现在重新安装都不行了，不知道问题出在哪里了。

**Comment by kanasimi** [comment]
請問您在命令列提示下執行 `nslookup raw.githubusercontent.com` 結果是?

**Comment by Fiend1019** [comment]
> 請問您在命令列提示下執行 `nslookup raw.githubusercontent.com` 結果是?

C:\Users\Mr.wu\Desktop\manga>nslookup raw.githubusercontent.com
服务器:  UnKnown
Address:  192.168.43.1

非权威应答:
名称:    raw.githubusercontent.com
Addresses:  ::
          0.0.0.0

**Comment by kanasimi** [comment]
您的proxy看起來也被擋了...
您是否能從瀏覽器下載到 https://raw.githubusercontent.com/kanasimi/work_crawler/master/work_crawler.updater.js

**Comment by Fiend1019** [comment]
开代理可以正常下载到。。。

**Comment by kanasimi** [comment]
執行 `ipconfig /flushdns` 之後再嘗試是否有用呢?

**Comment by Fiend1019** [comment]
> ipconfig /flushdns

这个我之前试过了。。。。没有用，所以就感觉很奇怪

**Comment by kanasimi** [comment]
這個工具不接受sock的形式
不曉得您有沒有 https:// , http:// 的 proxy?

**Comment by Fiend1019** [comment]
> 這個工具不接受socks的形式
> 不曉得您有沒有 https:// , http:// 的 proxy?

有的，两个我都试了

**Comment by kanasimi** [comment]
請先執行 `npm install socks-proxy-agent`
再下載最新版的 work_crawler.updater.js 試試看

**Comment by Fiend1019** [comment]
安装倒是安装上了，但是结果还是那样。可能是我网络的问题吧，这里就先不打扰您了，真是麻烦您了。

**Comment by kanasimi** [comment]
這邊會找時間嘗試看看能不能使用socks的proxy

**Comment by Fiend1019** [comment]
> 這邊會找時間嘗試看看能不能使用socks的proxy

好的，麻烦您了，谢谢！

**Comment by kanasimi** [comment]
請問您使用的socket proxy程式是哪種呢
這邊可能會當作調試時的參考

**Comment by Fiend1019** [comment]
> 請問您使用的socket proxy程式是哪種呢
> 這邊可能會當作調試時的參考

v2rayN

**Comment by kanasimi** [comment]
請問您設定過
https_proxy=https://127.0.0.1:ddd
只是因為不能使用
所以才改成 socket 的嗎

假如可以使用 https_proxy 的話，修復這個問題的時間可以大幅減少。

**Comment by Fiend1019** [comment]
我两个用了啊，每个都试过， https_proxy也可以使用，两个都有
![QQ图片20210405200700](https://user-images.githubusercontent.com/64277417/113572298-864ef580-964a-11eb-9bd6-07f3e8b06469.png)

**Comment by kanasimi** [comment]
依這邊的測試 您需要使用 http_proxy
SET http_proxy=http://127.0.0.1:dddd
像u17可以用
不過QQ似乎網路憑證有問題 就沒辦法
每個網站有各自不同的問題 需要單獨列出

**Comment by Fiend1019** [comment]
收到，这边就暂时不麻烦您了。我感觉是我电脑的问题，有时间我换台电脑试一下。

**Comment by FamilyCYZ** [comment]
我也碰到了这个问题，原因是“访问不到境外的域名服务器”，需要在本地host里面配置github对应的域名“151.101.56.133 raw.githubusercontent.com”，亲测可行，可以参考下这两篇文章的说明
https://segmentfault.com/a/1190000038719758
https://blog.csdn.net/weixin_46353030/article/details/121175878

**Comment by kanasimi** [comment]
> 我也碰到了这个问题，原因是“访问不到境外的域名服务器”，需要在本地host里面配置github对应的域名“151.101.56.133 raw.githubusercontent.com”

```
windows: %systemroot%\system32\drivers\etc
linux: /etc/hosts
```

```
# GitHub 相關 Start
151.101.108.133 user-images.githubusercontent.com
151.101.56.133 avatars0.githubusercontent.com
151.101.56.133 avatars1.githubusercontent.com
151.101.56.133 avatars2.githubusercontent.com
151.101.56.133 avatars3.githubusercontent.com
151.101.56.133 avatars4.githubusercontent.com
151.101.56.133 avatars5.githubusercontent.com
151.101.56.133 avatars6.githubusercontent.com
151.101.56.133 avatars7.githubusercontent.com
151.101.56.133 avatars8.githubusercontent.com
151.101.56.133 camo.githubusercontent.com
151.101.56.133 cloud.githubusercontent.com
151.101.56.133 gist.githubusercontent.com
151.101.56.133 marketplace-screenshots.githubusercontent.com
151.101.56.133 raw.githubusercontent.com
151.101.56.133 repository-images.githubusercontent.com
151.101.56.133 user-images.githubusercontent.com
185.199.111.153 assets-cdn.github.com
192.30.253.119 gist.github.com
192.30.255.112 gist.github.com
192.30.255.112 github.com
192.30.255.112 www.github.com
#199.232.96.133 avatars0.githubusercontent.com
#199.232.96.133 avatars1.githubusercontent.com
#199.232.96.133 avatars2.githubusercontent.com
#199.232.96.133 avatars3.githubusercontent.com
#199.232.96.133 avatars4.githubusercontent.com
#199.232.96.133 avatars5.githubusercontent.com
#199.232.96.133 avatars6.githubusercontent.com
#199.232.96.133 avatars7.githubusercontent.com
#199.232.96.133 avatars8.githubusercontent.com
#199.232.96.133 camo.githubusercontent.com
#199.232.96.133 cloud.githubusercontent.com
#199.232.96.133 gist.githubusercontent.com
#199.232.96.133 raw.githubusercontent.com
52.74.223.119 github.com
54.169.195.247 api.github.com
# GitHub 相關 End
```

顯示所有 dns內容 
```
ipconfig /displaydns &::
```
刷新所有 dns內容
```
ipconfig /flushdns &::
```
