### ISSUE TITLE
ohmanhua下載 分部

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#502]
﻿

* **Version**: 
* **Interface**: 
* **Arguments**:

**Comment by gfhghfghfh** [comment]
有些漫畫會有

這兩種分部

**Comment by kanasimi** [comment]
兩個版本的畫質比較起來如何？
有哪個版本畫質總是比較好的嗎？

另外就您所舉的例子
這邊只能看到 稳定路线

**Comment by gfhghfghfh** [comment]
稳定路线

**Comment by kanasimi** [comment]
這邊能看到兩種的有
https://www.cocomanhua.com/18071/
https://www.cocomanhua.com/18565/
https://www.cocomanhua.com/14169/
有時間會嘗試看看

**Comment by gfhghfghfh** [comment]
云播放

**Comment by gfhghfghfh** [comment]
另外可以將ohmanhua預設下載選項中recheck改成multi_parts_changed嗎

謝謝您

**Comment by gfhghfghfh** [comment]
更新程式後
下載id 18071
發現云播放下載到的圖片跟稳定路线一樣

等於是同樣的版本下載兩次

沒有真正下載到云播放的圖片


請問這個問題是可以改善的嗎
謝謝您
