### ISSUE TITLE
webtoon 遇到 invalid uri 卡住

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#503]
﻿

* **Version**: 
* **Interface**: 
* **Arguments**:

**Comment by gfhghfghfh** [comment]
請問遇到此類情況能改善成不會卡住嗎

id challenge_127863
卡住章節編號233
<img width="320" alt="gh" src="https://user-images.githubusercontent.com/42042168/115116856-6d412f80-9fce-11eb-84ad-ef7476bf552e.png">

**Comment by kanasimi** [comment]
webtoon 有兩種
包括英文版

不曉得您遇到的問題是哪個版本呢？

**Comment by gfhghfghfh** [comment]
英文版
以提供作品id
