### ISSUE TITLE
Cannot convert object to primitive value

### ISSUE THREAD

**Issue by z775729168** [kanasimi/work_crawler#504]
﻿

* **Version**: 複製倉庫下來的
* **Interface**: headless linux 
* **Arguments**: node /root/work_crawler/comic.cmn-Hans-CN/dmzj.js manhua_doupaichuanshuo skip_error=true

您好
我在下載動漫之家的漫畫時遇到一些問題。
域名是我改成dmzj1的
屏顯如下

> root@Brix ~# node /root/work_crawler/comic.cmn-Hans-CN/dmzj.js manhua_doupaichuanshuo skip_error=true
>          skip_error: undefined
> From Command-Line → true
> dmzj: 2021/4/18 1:1:39 Starting <manhua_doupaichuanshuo>, save to /mnt/nas/comics/dmzj/
> manhua_doupaichuanshuo 斗牌传说: 165 章. 连载中
> 1/165 [0001 第52话(仲井篇)] 45 images. 篇).zip
> Image damaged: http://images.dmzj1.com/d/%E6%96%97%E7%89%8C%E4%BC%A0%E8%AF%B4/%E7%AC%AC52%E8%AF%9D%E4%BB%B2%E4%BA%95%E7%AF%87/%E8%B5%8C%E5%8D%9A%E5%90%A7%E6%8B%9B%E5%8B%9F.jpg
> → /mnt/nas/comics/dmzj/斗牌传说/0001 第52话(仲井篇)/doupaichuanshuo-1-045.jpg
> get_image: Retry 1/4...
> Image damaged: http://images.dmzj1.com/d/%E6%96%97%E7%89%8C%E4%BC%A0%E8%AF%B4/%E7%AC%AC52%E8%AF%9D%E4%BB%B2%E4%BA%95%E7%AF%87/%E8%B5%8C%E5%8D%9A%E5%90%A7%E6%8B%9B%E5%8B%9F.jpg
> → /mnt/nas/comics/dmzj/斗牌传说/0001 第52话(仲井篇)/doupaichuanshuo-1-045.jpg
> get_image: Retry 2/4...
> Image damaged: http://images.dmzj1.com/d/%E6%96%97%E7%89%8C%E4%BC%A0%E8%AF%B4/%E7%AC%AC52%E8%AF%9D%E4%BB%B2%E4%BA%95%E7%AF%87/%E8%B5%8C%E5%8D%9A%E5%90%A7%E6%8B%9B%E5%8B%9F.jpg
> → /mnt/nas/comics/dmzj/斗牌传说/0001 第52话(仲井篇)/doupaichuanshuo-1-045.jpg
> get_image: Retry 3/4...
> Image damaged: http://images.dmzj1.com/d/%E6%96%97%E7%89%8C%E4%BC%A0%E8%AF%B4/%E7%AC%AC52%E8%AF%9D%E4%BB%B2%E4%BA%95%E7%AF%87/%E8%B5%8C%E5%8D%9A%E5%90%A7%E6%8B%9B%E5%8B%9F.jpg
> → /mnt/nas/comics/dmzj/斗牌传说/0001 第52话(仲井篇)/doupaichuanshuo-1-045.jpg
> get_image: Retry 4/4...
> Force storage of damaged image 162903 bytes: /mnt/nas/comics/dmzj/斗牌传说/0001 第52话(仲井篇)/doupaichuanshuo-1-045 bad.jpg
> ← http://images.dmzj1.com/d/%E6%96%97%E7%89%8C%E4%BC%A0%E8%AF%B4/%E7%AC%AC52%E8%AF%9D%E4%BB%B2%E4%BA%95%E7%AF%87/%E8%B5%8C%E5%8D%9A%E5%90%A7%E6%8B%9B%E5%8B%9F.jpg
> /root/work_crawler/node_modules/cejs/application/storage/archive.js:305ly downloaded this time: 0001 第52话(仲井篇).zip
>                 return /^"(\\.|[^\\\n])*"$/.test(arg) ? arg : '"'
>                                                      ^
> 
> TypeError: Cannot convert object to primitive value
>     at RegExp.test (<anonymous>)
>     at add_fso_path_quote (/root/work_crawler/node_modules/cejs/application/storage/archive.js:305:31)
>     at Array.map (<anonymous>)
>     at Archive_file.archive_file_execute [as execute] (/root/work_crawler/node_modules/cejs/application/storage/archive.js:396:24)
>     at Archive_file.archive_file_operation (/root/work_crawler/node_modules/cejs/application/storage/archive.js:890:21)
>     at Archive_file.<computed> [as remove] (/root/work_crawler/node_modules/cejs/application/storage/archive.js:927:35)
>     at check_if_done (/root/work_crawler/node_modules/cejs/application/net/work_crawler/chapter.js:1542:21)
>     at Work_crawler.get_URL.Object.assign.max_listeners (/root/work_crawler/node_modules/cejs/application/net/work_crawler/image.js:435:7)
>     at IncomingMessage.<anonymous> (/root/work_crawler/node_modules/cejs/application/net/Ajax.js:2222:6)
>     at IncomingMessage.emit (node:events:381:22)

圖片在瀏覽器中是可以顯示的，是一張宣傳圖片。
>return /^"(\\.|[^\\\n])*"$/.test(arg) ? arg : '"'
>                                                      ^
這個"^"指向的“test"的t

最後，謝謝您的軟件。

**Comment by kanasimi** [comment]
感謝您的試用。這邊必須要更詳細的偵錯訊息。您能下載新的版本然後重新執行一次嗎？應該會顯示更詳細的訊息。

**Comment by z775729168** [comment]
謝謝您的回復
下面是屏顯
```

root@Brix ~# node /root/work_crawler/comic.cmn-Hans-CN/dmzj.js manhua_doupaichuanshuo skip_error=true recheck=true
         skip_error: undefined
From Command-Line → true
            recheck: undefined
From Command-Line → true
dmzj: 2021/4/18 8:46:49 Starting <manhua_doupaichuanshuo>, save to /mnt/nas/comics/dmzj/
              url:http://manhua.dmzj1.com/doupaichuanshuo
New information →http://manhua.dmzj.com/doupaichuanshuo
manhua_doupaichuanshuo 斗牌传说: 165 章. 连载中
1/165 [0001 第52话(仲井篇)] 45 images. 篇).zip
Image damaged: http://images.dmzj.com/d/%E6%96%97%E7%89%8C%E4%BC%A0%E8%AF%B4/%E7%AC%AC52%E8%AF%9D%E4%BB%B2%E4%BA%95%E7%AF%87/%E8%B5%8C%E5%8D%9A%E5%90%A7%E6%8B%9B%E5%8B%9F.jpg
→ /mnt/nas/comics/dmzj/斗牌传说/0001 第52话(仲井篇)/doupaichuanshuo-1-045.jpg
get_image: Retry 1/4...
Image damaged: http://images.dmzj.com/d/%E6%96%97%E7%89%8C%E4%BC%A0%E8%AF%B4/%E7%AC%AC52%E8%AF%9D%E4%BB%B2%E4%BA%95%E7%AF%87/%E8%B5%8C%E5%8D%9A%E5%90%A7%E6%8B%9B%E5%8B%9F.jpg
→ /mnt/nas/comics/dmzj/斗牌传说/0001 第52话(仲井篇)/doupaichuanshuo-1-045.jpg
get_image: Retry 2/4...
Image damaged: http://images.dmzj.com/d/%E6%96%97%E7%89%8C%E4%BC%A0%E8%AF%B4/%E7%AC%AC52%E8%AF%9D%E4%BB%B2%E4%BA%95%E7%AF%87/%E8%B5%8C%E5%8D%9A%E5%90%A7%E6%8B%9B%E5%8B%9F.jpg
→ /mnt/nas/comics/dmzj/斗牌传说/0001 第52话(仲井篇)/doupaichuanshuo-1-045.jpg
get_image: Retry 3/4...
Image damaged: http://images.dmzj.com/d/%E6%96%97%E7%89%8C%E4%BC%A0%E8%AF%B4/%E7%AC%AC52%E8%AF%9D%E4%BB%B2%E4%BA%95%E7%AF%87/%E8%B5%8C%E5%8D%9A%E5%90%A7%E6%8B%9B%E5%8B%9F.jpg
→ /mnt/nas/comics/dmzj/斗牌传说/0001 第52话(仲井篇)/doupaichuanshuo-1-045.jpg
get_image: Retry 4/4...
Force storage of damaged image 162903 bytes: /mnt/nas/comics/dmzj/斗牌传说/0001 第52话(仲井篇)/doupaichuanshuo-1-045 bad.jpg
← http://images.dmzj.com/d/%E6%96%97%E7%89%8C%E4%BC%A0%E8%AF%B4/%E7%AC%AC52%E8%AF%9D%E4%BB%B2%E4%BA%95%E7%AF%87/%E8%B5%8C%E5%8D%9A%E5%90%A7%E6%8B%9B%E5%8B%9F.jpg
Remove 5 damaged images from the image compression file that successfully downloaded this time: 0001 第52话(仲井篇).zip/root/work_crawler/node_modules/cejs/application/storage/archive.js:305
                return /^"(\\.|[^\\\n])*"$/.test(arg) ? arg : '"'
                                            ^

TypeError: Cannot convert object to primitive value
    at RegExp.test (<anonymous>)
    at add_fso_path_quote (/root/work_crawler/node_modules/cejs/application/storage/archive.js:305:31)
    at Array.map (<anonymous>)
    at Archive_file.archive_file_execute [as execute] (/root/work_crawler/node_modules/cejs/application/storage/archive.js:396:24)
    at Archive_file.archive_file_operation (/root/work_crawler/node_modules/cejs/application/storage/archive.js:890:21)
    at Archive_file.<computed> [as remove] (/root/work_crawler/node_modules/cejs/application/storage/archive.js:927:35)
    at check_if_done (/root/work_crawler/node_modules/cejs/application/net/work_crawler/chapter.js:1542:21)
    at Work_crawler.get_URL.Object.assign.max_listeners (/root/work_crawler/node_modules/cejs/application/net/work_crawler/image.js:435:7)
    at IncomingMessage.<anonymous> (/root/work_crawler/node_modules/cejs/application/net/Ajax.js:2222:6)
    at IncomingMessage.emit (node:events:381:22)
```

**Comment by kanasimi** [comment]
這邊早上有更新過
抱歉給麻煩您下載新的版本
這樣才會有比較詳細的錯誤訊息

**Comment by z775729168** [comment]
非常抱歉，我可能找到原因了。
我刪除了原來的文件，重新下載，是可以運行的。
我才想起來，我原來改了保存文件的文件夾名。在 `node_modules/cejs/application/net/work_crawler/work.js` 的815行左右
原來是
```
                        work_data.directory_name = library_namespace.to_file_name(
                        // 允許自訂作品目錄名/命名資料夾。
                        work_data.directory_name
                        // default 作品目錄名/命名資料夾。
                        || (typeof work_data.directory_id === 'function'
                        // 自行指定作品放置目錄與 ebook 用的 work id。
                        && work_data.directory_id() || work_data.id)
```
可能改成了
```
                        work_data.directory_name = library_namespace.to_file_name(
                        // 允許自訂作品目錄名/命名資料夾。
                        work_data.directory_name
                        // default 作品目錄名/命名資料夾。
                        //|| (typeof work_data.directory_id === 'function'
                        || ''
                        // 自行指定作品放置目錄與 ebook 用的 work id。
                        //&& work_data.directory_id() || work_data.id)
```
就是把文件夾前面的前綴去掉了。
如果我要修改的話，應該fork之後再修改，現在我連之前怎麽改的都記不太清楚了。
好像cejs也有更新，這個應該沒關係。
真的非常抱歉。

**Comment by kanasimi** [comment]
您可以用 git 的 diff 來查看修改了哪些地方。

**Comment by z775729168** [comment]
謝謝，我直接把整個文件夾刪除了……現在也重現不了，算了吧，太菜了，我還是以後多檢查一下。
抱歉耽誤時間了。

**Comment by kanasimi** [comment]
所以現在一切正常了?

**Comment by z775729168** [comment]
嗯……我着急就刪除了原來的文件……我以爲就改了一個域名……文件找不回來了……抱歉……

**Comment by kanasimi** [comment]
好吧
若是一切正常
那麻煩把本議題關閉吧
