### ISSUE TITLE
关于work_crawler2.12.0更新的几个问题

### ISSUE THREAD

**Issue by comicview** [kanasimi/work_crawler#505]
首先，很高兴终于迎来了作者对work_crawler2.12.0的更新，兴奋同时尝试了一下使用的体验，发现了以下几点问题

1.work_crawler2.12.0更新以后log日志显示非安装包版本安装失败，卸载旧版重新下载程序安装依旧如此；

2.新增漫画猫选项下载失败，填上id后下载长时间没反应，log日志也没下载记录；

3.漫画猫下载选项调整，点击无反应；

4.在点击漫画猫以后，再去点击其它漫画网站，接着再回来点击漫画猫会出现没法选定的现象；

![01](https://user-images.githubusercontent.com/81540110/115247033-000dd580-a159-11eb-899c-d48f175797fd.png)
![02](https://user-images.githubusercontent.com/81540110/115247060-056b2000-a159-11eb-93fd-7bf6f15a8721.png)
![03](https://user-images.githubusercontent.com/81540110/115247114-1582ff80-a159-11eb-987f-e13393c119c1.png)

**Comment by kanasimi** [comment]
請問除了漫畫貓外其他網站有類似問題嗎
另外漫畫貓需要下載一個github上面的解碼器
不曉得您有沒有科學上網呢

**Comment by comicview** [comment]
> 请问除了漫画猫外其他网站有类似问题吗其他
> 漫画猫需要下载一个github上面的解码器
> 不晓得您有没有科学上网呢

暂时没发现漫画猫以外的网站有这样的问题，有的话会第一时间告诉你
请问要下载什么样的解码器？

**Comment by kanasimi** [comment]
下次安裝包會修復此錯誤
