### ISSUE TITLE
下载途中失败的部分章节的补救办法

### ISSUE THREAD

**Issue by ha7rock** [kanasimi/work_crawler#51]
﻿

* **Version**: 最新，安装包
* **Interface**: Linux命令行

Hi，

最近发现在下载途中会出现部分chapter出现没有打包成功或者是下载失败的问题，也许是在重试了4次之后跳过了转去下载下一个章节。

当发现了以后也只能用删除旧章节，手动的方式一个个的去补救。用：

`node xxx.js "作品名" start_chapter=下载失败的章节 recheck`

然后再ctrl+c手动中止，转去执行下一个下载失败的章节,如此这般周而复始……

所以请问有没有更智慧简便的方案可以用？ 

另外，有时会出现打包出错，请看：

>  root@VPS:/manga/work_crawler/comic.cmn-Hans-CN# node manhuadb.js "火凤燎原" start_chapter=25 recheck
> start_chapter: 1
>    由命令列 → 25
>    recheck: undefined
> 由命令列 → true
> manhuadb: 2018-08-15T02:30:52.019Z Starting 火凤燎原, 儲存至 manhuadb/
> manhuadb: Find cache: 火凤燎原→"1070"
> 若之前已經下載到最新章節，則指定 start_chapter 時，必須同時設定 recheck！
> 1070 [陈某] 火凤燎原: 62 章. 连载中
> 25/62 [0025 25[火凤燎原][陈某][东立][a09070811]Vol_25] 192 images.
> undefined:19025[火凤燎原][陈某][东立][a09070811]Vol_25.zip]...
>                                 + library_namespace.storage.working_directory(), 1,
>                                                             ^
> 
> TypeError: library_namespace.storage.working_directory is not a function
>     at Archive_file.archive_file_execute [as execute] (eval at load_named (eval at <anonymous> (/manga/work_crawler/CeJS-master/_for include/node.loader.js:78:2)), <anonymous>:190:33)
>     at Archive_file.archive_file_operation (eval at load_named (eval at <anonymous> (/manga/work_crawler/CeJS-master/_for include/node.loader.js:78:2)), <anonymous>:406:17)
>     at Archive_file.eval [as update] (eval at load_named (eval at <anonymous> (/manga/work_crawler/CeJS-master/_for include/node.loader.js:78:2)), <anonymous>:435:35)
>     at check_if_done (eval at load_named (eval at <anonymous> (/manga/work_crawler/CeJS-master/_for include/node.loader.js:78:2)), <anonymous>:2790:21)
>     at get_next_image (eval at load_named (eval at <anonymous> (/manga/work_crawler/CeJS-master/_for include/node.loader.js:78:2)), <anonymous>:2459:7)
>     at Object.assign.max_listeners (eval at load_named (eval at <anonymous> (/manga/work_crawler/CeJS-master/_for include/node.loader.js:78:2)), <anonymous>:3069:40)
>     at IncomingMessage.eval (eval at load_named (eval at <anonymous> (/manga/work_crawler/CeJS-master/_for include/node.loader.js:78:2)), <anonymous>:1783:6)
>     at IncomingMessage.emit (events.js:185:15)
>     at endReadableNT (_stream_readable.js:1106:12)
>     at process._tickCallback (internal/process/next_tick.js:178:19)

Update: 
如上述问题，原本可以正常使用的打包作业，完全无法正常使用了

**`错误信息 TypeError: library_namespace.storage.working_directory is not a function`**

**Comment by kanasimi** [comment]
封裝進去了
https://github.com/kanasimi/CeJS/commit/b3b3fdae430f4fe3659e827bd08e770a8adf3827
麻煩請下載新版

舊的圖片應該不必刪除
假如有可以用的圖片
下一次會接續下載

也許是 working_directory() 這個的問題??
若是您更新完還是發現沒有改善的話
麻煩您直接示範一下範例
這樣可能會更容易了解
謝謝您

**Comment by ha7rock** [comment]
更新后可以打包完成了，继续观察一下再回报。
