### ISSUE TITLE
bilibili 遇到付費章節的顯示情況

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#511]
﻿

* **Version**: 
* **Interface**: 
* **Arguments**:

**Comment by gfhghfghfh** [comment]
遇到付費章節會在進度條中顯示
像下方的內容
process_chapter_data: 29195 两不疑 §74/178: 本章節沒有獲取到任何圖片！

發生此情況的id
25899
29195

未發生此情況的id
26769




希望能改成遇到付費章節不會顯示本章節沒有獲取到任何圖片

**Comment by gfhghfghfh** [comment]
此外希望可以識別搶先看的標記
讓下次下載從之前 因搶先看尚未下載的部分
h ttps://manga.bilibili.com/detail/mc29721

**Comment by kanasimi** [comment]
這邊的意思是
好像不會隨時間開放變得可看
而是一直都維持著搶先看
您有遇到開放變成可看的嗎?

**Comment by gfhghfghfh** [comment]
有的
上述的網址
只要有新的話數更新
較舊的搶先看章節
會變成免費
不太清楚您沒觀察到嗎



這邊用recheck是有下載到

**Comment by gfhghfghfh** [comment]
因為剛好都錯過上述漫畫的更新時間
這邊目前只能提供另一部這邊下載到的章節
觀察修改日期能看到是有取得曾是搶先看的章節
https://manga.bilibili.com/detail/mc27660
<img width="169" alt="gfdgd" src="https://user-images.githubusercontent.com/42042168/140632020-15b4d448-76a1-49b1-b6ce-4d4ff84b59e8.png">

**Comment by gfhghfghfh** [comment]
h ttps://manga.bilibili.com/detail/mc27660
![1](https://user-images.githubusercontent.com/42042168/141140679-93356987-f786-4170-9681-24dfddef44fe.png)





![2](https://user-images.githubusercontent.com/42042168/141140580-63c8cd89-4ad6-45eb-ab7e-3d43325a4cfd.png)

**Comment by kanasimi** [comment]
問題已和標題不符。若現在還有需求，煩請開新的議題。
