### ISSUE TITLE
咚漫畫質問題

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#513]
﻿

* **Version**: 
* **Interface**: 
* **Arguments**:

**Comment by gfhghfghfh** [comment]
手機網頁版的畫質優於網頁版

**Comment by kanasimi** [comment]
要知道入口頁面及搜尋方法才能添加

**Comment by gfhghfghfh** [comment]
手機板是在首頁上面皆有搜尋
但不清楚入口的部分

**Comment by gfhghfghfh** [comment]
網頁版圖片網址 h ttps://cdn.dongmanmanhua.cn/16189006774011603165.jpg?x-oss-process=image/quality,q_90
請求去除?x-oss-process=image/quality,q_90
可會有更高的畫質

**Comment by gfhghfghfh** [comment]
仍取得h ttps://cdn.dongmanmanhua.cn/16189006774011603165.jpg?x-oss-process=image/quality,q_90
請求去除?x-oss-process=image/quality,q_90

**Comment by gfhghfghfh** [comment]
仍取得https://cdn.dongmanmanhua.cn/16189006774011603165.jpg?x-oss-process=image/quality,q_90
