### ISSUE TITLE
webtoon畫質問題

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#514]
﻿

* **Version**: 
* **Interface**: 
* **Arguments**:

**Comment by gfhghfghfh** [comment]
webtoon畫質問題

**Comment by kanasimi** [comment]
麻煩請測試後回報是否有錯誤

**Comment by gfhghfghfh** [comment]
測試後
 無法成功取得圖片。HTTP 狀態碼 200，檔案過小，僅 364144 bytes：https://webtoon-phinf.pstatic.net/20200709_151/1594259188481oJOmh_JPEG/1594259188454210459.jpg

jpg類型的的圖片後面還有問號(.jpg?)
不確定是否影響

**Comment by gfhghfghfh** [comment]
另外

ttps://webtoon-phinf.pstatic.net/20210419_168/16188057006836Pgrh_PNG/161880570064616181009.png?type=opti
ttps://webtoon-phinf.pstatic.net/20210419_33/1618805704859u773q_JPEG/161880570082416181005.jpg?type=q90
https://webtoon-phinf.pstatic.net/20200619_50/15925290127115ohRU_JPEG/WhatsApp%20Image%202020-06-05%20at%2010.46.04.jpeg?type=q90

png類型的圖檔會有與其他類型的圖檔相異的結尾 ?type=opti 能否一併去除這邊一起測試

**Comment by gfhghfghfh** [comment]
// 去掉?type=q70s的部分 畫質較好

q70是手機版
q90才是電腦版

**Comment by gfhghfghfh** [comment]
請問無法採用類似於https://github.com/kanasimi/work_crawler/issues/503的修改方式嗎


因為https://github.com/kanasimi/work_crawler/issues/503的修改方式可以不產生類似於下方的問題
get_URL_node: 獲取 [https://webtoon-phinf.pstatic.net/20200402_264/158581426679176ohM_JPEG/ปก.jpeg] 出錯：TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
