### ISSUE TITLE
oh漫畫特定圖源畫質問題

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#516]
﻿

* **Version**: 
* **Interface**: 
* **Arguments**:

**Comment by gfhghfghfh** [comment]
請問可以修改為當獲得的圖片網址結尾為-zymk.middle.webp時換成-zymk.high嗎


例如
h ttps://www.cocomanhua.com/18656/
h ttps://mhpic.xiaomingtaiji.net/comic/C/%E9%87%8D%E7%94%9F%E4%B9%8B%E5%89%91%E7%A5%9E%E5%BD%92%E6%9D%A5/%E7%AC%AC7%E8%AF%9DF0_295714/2.jpg-zymk.middle.webp

**Comment by kanasimi** [comment]
麻煩請測試後回報是否有錯誤

**Comment by gfhghfghfh** [comment]
測試之後仍舊取得-zymk.middle
原先程式就是把-zymk.middle.webp換成-zymk.middle

**Comment by gfhghfghfh** [comment]
測試之後仍舊取得-zymk.middle

**Comment by gfhghfghfh** [comment]
不好意思
測試之後仍舊取得-zymk.middle
