### ISSUE TITLE
gufengmh出現將資料寫入快取文件

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#522]
﻿

* **Version**: 
* **Interface**: 
* **Arguments**:

**Comment by gfhghfghfh** [comment]
在有json的情況下
下載選項為recheck:false
接續接續下載的情況下發生


<img width="506" alt="v" src="https://user-images.githubusercontent.com/42042168/126961235-190fc00b-1ad8-4520-b9b3-ff3ecf4a5f01.png">
<img width="107" alt="c" src="https://user-images.githubusercontent.com/42042168/126961239-d35643ad-5a9c-43f2-b730-8cbb29f7c300.png">

**Comment by kanasimi** [comment]
可能是設定了 write_chapter_metadata?

**Comment by gfhghfghfh** [comment]
這邊沒有將write_chapter_metadata設定為true

此外
試著將上方的json
使用下載選項recheck:true start_chapter=112
就不會有此問題

**Comment by kanasimi** [comment]
無法重現
