### ISSUE TITLE
關於已 *年 沒有更新，時間過久不再強制重新下載，僅在章節數量有變化時才重新下載。此功能

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#524]
﻿

* **Version**: 
* **Interface**: 
* **Arguments**:

**Comment by gfhghfghfh** [comment]
請問可否將此功能改成下載選項
自行決定是否開啟此功能

因為像下方的作品

comic-walker網站的作品id:KDCW_MF07000027010000_68
更新
第3話前編
【配信期限】〜2021/08/04 11:00
第3話後編
【配信期限】〜2021/08/04 11:00





但是因為更新日期仍顯示2017/12/13 更新
所以被判定為已 4年 沒有更新，時間過久不再強制重新下載，僅在章節數量有變化時才重新下載。
(剛好章節數量也沒有變化)
所以沒有下載到新更的章節

**Comment by kanasimi** [comment]
應該取得正確的更新時間。
現在似乎已經沒有這樣的作品。
若沒其他例子以做測試的話，將關閉此議題。

**Comment by gfhghfghfh** [comment]
https://comic-walker.com/contents/detail/KDCW_CB01200590010000_68/

**Comment by gfhghfghfh** [comment]
KDCW_CB01200590010000_68
KDCW_MF00000020010000_68
