### ISSUE TITLE
[.74] check_and_run.run: Error to run function: Cannot read property 'default_program_type' of undefined

### ISSUE THREAD

**Issue by 1405308186** [kanasimi/work_crawler#527]
https://imgtu.com/i/fX4Qw6
This is my first use.

**Comment by kanasimi** [comment]
請問您有7-zip嗎
不曉得安裝路徑(可執行檔)是哪裡呢

**Comment by 1405308186** [comment]
哦  是我的问题   我使用的是安装包   我没有下载7-Zip  
我单纯的认为如果需要7-Zip，我的Bandzip也会起到同样的效果
现在我下载了7-Zip，问题解决了
十分感谢

**Comment by baichoulishang** [comment]
测试

发自我的iPhone
