### ISSUE TITLE
dmzj referer error

### ISSUE THREAD

**Issue by z775729168** [kanasimi/work_crawler#530]
﻿

* **Version**: git clone下載 work_crawler
* **Interface**: 命令列介面
* **Arguments**: node work_crawler/comic.cmn-Hans-CN/dmzj.js manhua_huangdiyuwo skip_error=true recheck=true

動漫之家的圖片好像有403問題
`root@Brix ~# curl -I http://images.dmzj.com/h/%E7%9A%87%E5%B8%9D%E4%B8%8E%E6%88%91/01/03.jpg`
`HTTP/1.1 403 Forbidden`
`Server: kngx/1.10.2`
`Date: Sat, 11 Sep 2021 19:02:29 GMT`
`Content-Type: text/html`
`Content-Length: 168`
`Connection: keep-alive`
`KS-Deny-Reason: referer-acl-deny`
`X-Cdn-Request-ID: 5f598dd13434ebd2164e3dc635116165`

加一個頭信息
`root@Brix ~ [23]# curl -I --header 'Referer: http://manhua.dmzj.com' http://images.dmzj.com/h/%E7%9A%87%E5%B8%9D%E4%B8%8E%E6%88%91/01/03.jpg`
`HTTP/1.1 200 OK`
`Content-Type: image/jpeg`
`Content-Length: 378641`
`Connection: keep-alive`
`Server: Tengine`
`ETag: "e368b11fabe2776b3b9ae4494db87b8e"`
`Date: Sat, 11 Sep 2021 16:19:20 GMT`
`Last-Modified: Thu, 02 Sep 2021 09:13:55 GMT`
`Expires: Mon, 11 Oct 2021 16:19:20 GMT`
`Age: 9776`
`Accept-Ranges: bytes`
`X-Application-Context: application`
`x-kss-request-id: 6478e91af66c44d09dcb909ebafa7bd3`
`X-Info-StorageClass: -`
`Content-MD5: 42ixH6vid2s7muRJTbh7jg==`
`X-Cache-Status: MISS from KS-CLOUD-TAIZ-MP-07-17`
`X-Cache-Status: HIT from KS-CLOUD-XM-CM-24-05`
`X-Cache-Status: HIT from KS-CLOUD-TZ-CM-01-03`
`X-Cdn-Request-ID: eb1946f0d25f5c0a8ee6612a759c8a0f`

試了一下，不會寫，只好求大大幫忙了😘

**Comment by kanasimi** [comment]
無法重現。
