### ISSUE TITLE
咚漫使用借阅卷/支付提前看的漫画无法下载

### ISSUE THREAD

**Issue by ruzhe85** [kanasimi/work_crawler#532]
最近在使用咚漫 在程序里面找不到登陆入口，但是已经把cookie加入了 
看了readme没提到不能下载借阅卷的漫画 想确认一下是我操作失当还是本身不支持

软件很好用 比tachiyomi自带下载舒服多了 感谢

**Comment by kanasimi** [comment]
或許是cookie格式的問題？若有必要請重開本議題。
