### ISSUE TITLE
mangabilibili 下載出現.tmp資料夾

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#542]
﻿

* **Version**: 
* **Interface**: 
* **Arguments**:

**Comment by gfhghfghfh** [comment]
更新後下載出現
![螢幕擷取畫面 2022-01-21 112852](https://user-images.githubusercontent.com/42042168/150460655-c283f346-a528-4e47-b631-9da91406a54e.png)

使用的下載選項
"cache_title_to_id":false,"archive_images":false

**Comment by kanasimi** [comment]
作品ID？
以及是否有沒有錯誤訊息？

**Comment by gfhghfghfh** [comment]
好的因為初次下載時無錯誤訊息所以沒注意到

任一ｉｄ似乎都會發生


![image](https://user-images.githubusercontent.com/42042168/150466586-dcf784a2-5c20-4f32-bfb9-7da964dc5e1d.png)


![image](https://user-images.githubusercontent.com/42042168/150466651-89bdb4ef-f870-4210-893e-38a0b0036056.png)

![image](https://user-images.githubusercontent.com/42042168/150466679-570136a0-d968-496f-a668-fc2d821e6c43.png)

**Comment by kanasimi** [comment]
這邊測試正常
請您確認cejs是否已更新至最新版本
