### ISSUE TITLE
快看漫畫遇到搶先看集數卡住

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#543]
﻿

* **Version**: 
* **Interface**: 
* **Arguments**:

**Comment by gfhghfghfh** [comment]
沒有顯示任何錯誤訊息
www.kuaikanmanhua.com/web/topic/96/
![image](https://user-images.githubusercontent.com/42042168/150666692-e2c16f8f-4515-4e64-974d-c7c0a0efffaa.png)

**Comment by kanasimi** [comment]
這是遵循了 #511 這邊的設計
下次下載從之前 因搶先看尚未下載的部分下載

**Comment by gfhghfghfh** [comment]
這邊是指他會一直卡在這個狀態
進度調會卡在這狀態
不太確定是因為網站有改甚麼
還是跟最近的更新有關
