### ISSUE TITLE
關於圖片檔案格式的問題

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#548]
﻿

* **Version**: 
* **Interface**: 
* **Arguments**:

**Comment by gfhghfghfh** [comment]
關於圖片檔案格式的問題

**Comment by kanasimi** [comment]
本工具下載時預設的使用者代理為 Chrome，所以下載的檔案格式基本上依循用 Chrome 瀏覽時的檔案格式。

**Comment by gfhghfghfh** [comment]
那可以請問一下以前在https://github.com/kanasimi/work_crawler/issues/477 提到的
《副檔名是JPG，但實際上格式是png，因此自動改成正確的副檔名了》
是由程式另外再去判別，還是也是依照chrome

不好意思可以再請問一下，這邊還是不太不明白，因為是從同一個網址取得的圖片為什麼下載到的位元數會不相同（是webp jpg其中一個有被轉檔嗎）

**Comment by kanasimi** [comment]
下載下來之後會判別下載的檔案格式，並以之設定副檔名。

由於IE無法顯示webp，因此有些網站會對不同瀏覽器展示不同的檔案格式。
