### ISSUE TITLE
默认下载位置的更改，以及屏蔽搜索某些网站（直接不搜索某些网站）

### ISSUE THREAD

**Issue by MRDG001** [kanasimi/work_crawler#550]
* **Version**: 安裝包
1.我在下载选项那一栏的data_directory（默认主要下载目录）安装好以后是是:C:\Users\Downloads\ 
我更改到我其他盘（H盘）的文件夹里，下载是成功的。但重启软件以后默认下载目录依旧是C:\Users\Downloads\ 
求教如何永久更改默认下载目录
2.腾讯动漫、有妖气之类的网站我个人没有需求，以及有些网站长期丢失连接，我想屏蔽搜索他们（直接不搜索免得占用太长搜索时间）
看教程没看到怎么操作，也请求指导，感谢大佬了！~

**Comment by kanasimi** [comment]
1. 無法重現
2. 設定太過複雜。若有無法連結的網站，請提出議題以刪除。其他請利用中斷搜尋。
