### ISSUE TITLE
章節命名問題

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#551]
﻿

* **Version**: 
* **Interface**: 
* **Arguments**:

**Comment by gfhghfghfh** [comment]
想請問命名方式是要全部改了嗎
因為這樣往後如果需要重新下載似乎都要全改?
![image](https://user-images.githubusercontent.com/42042168/158053271-6b303a65-bec6-4c41-88cc-a2ba73fa9256.png)

**Comment by gfhghfghfh** [comment]
另外這邊嘗試最新的程式碼

您是似乎是改成隨總章節數的[數位]來變化
1
01
001
0001
想請問這樣有甚麼好處嗎
因為總章節的數位會隨章節更新而變化
這樣需要使用重新下載時不是還是會被下載到另一個資料夾

**Comment by gfhghfghfh** [comment]
請問如果不能改回以前的命名方式的話
這個部分可以做成選項之類的嗎?

因為目前累積一些未完結的作品
往後可能因為網站改版或是經常增刪章節的網站或是具有分部的作品
需要recheck 都會要重新爬一次圖


或是您可以教我如何更改嗎?
這邊試著將
Cejs的
application/net/work_crawler/work.js
的1180行
this.need_create_ebook ? 4 : 3,
改成
this.need_create_ebook ? 4 : 4,

但您似乎是設定成將圖片的數位跟章節的數位相同
所以圖片的位數也會變成2245-1-0003

**Comment by kanasimi** [comment]
這邊回退了改變，您先試試看。
