### ISSUE TITLE
migudm 咪咕漫画搜索报错

### ISSUE THREAD

**Issue by karma-sun** [kanasimi/work_crawler#556]
﻿

* **Version**: 
安裝包
* **Interface**: 
圖形介面
* **Arguments**: 

咪咕漫画搜索报错
https://www.migudm.cn/search/result/list.html?hintKey=JUU4JUFGJUI4JUU1JUE0JUE5JUU3JUJBJUFB&hintType=2&pageSize=30&pageNo=1 出错：Error: Parse Error

**Comment by kanasimi** [comment]
網站版的搜尋似乎也不能用了。

**Comment by karma-sun** [comment]
刚测试网页版，可以正常搜索啊

**Comment by kanasimi** [comment]
又恢復正常了
