### ISSUE TITLE
請求新增 bilibili  接續搶先看章節的功能

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#562]
﻿

* **Version**: 
* **Interface**: 
* **Arguments**:

**Comment by gfhghfghfh** [comment]
希望可以識別搶先看的標記讓下次下載從"之前因搶先看尚未下載的章節"
或是設計成與kuaikan搶先看相同的機制




有搶先看得作品範例
h/ttps://manga.bilibili.com/detail/mc29721


![1](https://user-images.githubusercontent.com/42042168/141140679-93356987-f786-4170-9681-24dfddef44fe.png)


![2](https://user-images.githubusercontent.com/42042168/141140580-63c8cd89-4ad6-45eb-ab7e-3d43325a4cfd.png)

**Comment by gfhghfghfh** [comment]
不好意思
已修正

**Comment by kanasimi** [comment]
related #511
