### ISSUE TITLE
快看漫畫非搶先看作品無法下載後續

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#565]
﻿

* **Version**: 
* **Interface**: 
* **Arguments**:

**Comment by gfhghfghfh** [comment]
h ttps://www.kuaikanmanhua.com/web/topic/68/
非搶先看
但無法下載後續
![image](https://user-images.githubusercontent.com/42042168/176809335-5d46fd49-b457-4d4f-a5bd-1275d90fa6cf.png)

**Comment by kanasimi** [comment]
這個作品後續都要收費，似乎本來就看不到了？

**Comment by gfhghfghfh** [comment]
但這邊點擊是可觀看的?

**Comment by kanasimi** [comment]
您有輸入帳號嗎?

**Comment by gfhghfghfh** [comment]
這邊清除瀏覽器紀錄後重新開啟網址會出現您說APP專享
但嘗試跳轉到其他kuaikanmanhua頁面幾次後又消失
嘗試輸入COOKIE 會顯示TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

**Comment by kanasimi** [comment]
這邊在作品頁面按F5無法重現...

**Comment by gfhghfghfh** [comment]
還是這邊可以用甚麼方式提供給您網頁的檔案分析嗎
或是能否支援kuaikanmanhua的COOKIE(無帳號情況下的cookie)
因為這邊也是跳轉畫面就得到可閱讀的頁面
![image](https://user-images.githubusercontent.com/42042168/176860073-a8dd27ae-4992-4e96-81de-bb45c984bb91.png)

**Comment by gfhghfghfh** [comment]
開啟無紀錄的視窗

**Comment by kanasimi** [comment]
抱歉 依此方法試過仍無法重現...

**Comment by gfhghfghfh** [comment]
這邊利用chrome擴充先匯出在匯入cookie似乎能取得閱讀頁面
[cookie.txt](https://github.com/kanasimi/work_crawler/files/9027834/cookie.txt)

可能只能考慮藉由支援快看的cookie解決此問題

**Comment by gfhghfghfh** [comment]
這邊透過將cookie編碼轉換再輸入到程式中可正常使用
不好意思勞煩您了

**Comment by kanasimi** [comment]
所以您是登入帳號或者採用APP呢?

**Comment by gfhghfghfh** [comment]
這邊真的沒有登入也是用網頁板
單純一直跳轉頁面獲得cookie

如果您需要分析的話這邊也可以提供剛剛取得的cookie

我的說法可能讓您誤會了
轉碼cookie是因為
因為快看cookie含簡體中文
這邊本來是直接複製從瀏覽器或的的cookie
導致本工具會出現報錯
因此這邊使用網路上的Unicode 編碼轉換

**Comment by kanasimi** [comment]
了解。這邊反覆嘗試也無法重現，似乎也不是個泛用的方法。
