### ISSUE TITLE
有关打包的问题

### ISSUE THREAD

**Issue by Z-fly** [kanasimi/work_crawler#569]
![image](https://user-images.githubusercontent.com/10470892/176990148-a9b4cbd6-e94b-4da5-970b-f390e4709c6a.png)
electron-builder打包报错了，win-unpacked文件夹里的程序运行结果是这样的

**Comment by Z-fly** [comment]
如果打包没问题的话，请在https://github.com/kanasimi/work_crawler/releases更新下吧。

**Comment by Z-fly** [comment]
如果打包没问题的话，请在https://github.com/kanasimi/work_crawler/releases 更新下吧。

**Comment by kanasimi** [comment]
新版本 CeJS online work crawler v2.14.0 已出
