### ISSUE TITLE
nokiacn 下載失敗

### ISSUE THREAD

**Issue by sandycheng1** [kanasimi/work_crawler#57]
http://www.nokiacn.net/yinv/25nvzigaosheng/

**Comment by kanasimi** [comment]
請貼上錯誤訊息或者執行時的畫面

**Comment by sandycheng1** [comment]
好的,不好意思
<img width="946" alt="default" src="https://user-images.githubusercontent.com/41149813/44213700-e85c4300-a1a0-11e8-97c0-0c1b6af92e0f.PNG">
