### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by xingsuxingchen** [kanasimi/work_crawler#573]
﻿

* **Version**: 2.13.0
* **Interface**: windows,exe
* **Arguments**: 

①繁体仍有部分未翻译成简体
②漫画下载只能下载第一章节，剩下的未能下载！
③能否自行设置下载目录
④漫画网站能否自己添加（有这样的漫画源社区最好）

**Comment by xingsuxingchen** [comment]
![image](https://user-images.githubusercontent.com/87761930/181148054-d9e018bd-cdfe-4f21-859a-5e49d39f4238.png)

**Comment by kanasimi** [comment]
1. 您可參考以解決翻譯問題
2. 請問您下載的是哪個網站呢?
3. 您可使用 data_directory, main_directory 來更改下載目錄
4. 現在沒有...歡迎有志之士一同改進本工具並且增加網站！

**Comment by xingsuxingchen** [comment]
这图形界面的似乎不管下哪个站的都是一章节

**Comment by xingsuxingchen** [comment]
733动漫网只下载一章节

**Comment by kanasimi** [comment]
您可能要等下一版更新或者採用懶人更新法

**Comment by xingsuxingchen** [comment]
我还是等下一版本吧！谢谢啦

**Comment by Yucie** [comment]
アルファポリス 公式下載失敗
![error2](https://user-images.githubusercontent.com/12384865/184045313-d362437b-8ac1-47aa-a986-38cbec033c56.jpg)

**Comment by kanasimi** [comment]
@Yucie 煩請另開新議題 謝謝

**Comment by kanasimi** [comment]
新版本 CeJS online work crawler v2.14.0 已出
