### ISSUE TITLE
請問comico 要怎麼搭配閱讀卷 在程式內中使用

### ISSUE THREAD

**Issue by sandycheng1** [kanasimi/work_crawler#59]
在使用時上面會出現
已無閱讀卷可用。跳過 2話 俺､今発情中だから，不使用閱讀券。
所以是有辦法使用閱讀卷嗎

**Comment by kanasimi** [comment]
若想要讓本工具自動使用閱讀卷，請在 work_crawler_loder.configuration.js 這個檔案中設定  "auto_use_ticket:true"。您可以參考 work_crawler_loder.js 這個檔案來做設定。

**Comment by sandycheng1** [comment]
請問可以示範怎麼打嗎

**Comment by kanasimi** [comment]
``` JavaScript
site_configuration.comico = site_configuration.comico_jp = site_configuration.comico_jp_plus = {
	// 警告:帳號資訊是用明碼存放在檔案中。
	loginid : 'a@b.c',
	password : 'xxxxxxxxx',
	// 讓本工具自動使用閱讀卷。警告:閱讀券使用完就沒了。不可回復。
	auto_use_ticket : true
};
```

**Comment by sandycheng1** [comment]
請問我能去哪裡編輯work_crawler_loder.js

**Comment by kanasimi** [comment]
請到安裝本工具的目錄下

**Comment by sandycheng1** [comment]
我的意思是我能如何打開work_crawler_loder.js
並且編輯它
請問是先按fork再改裡面的東西嗎
(不好意思我沒概念

**Comment by kanasimi** [comment]
在檔案的上面按右鍵
應該會出現一個"編輯"的選項

**Comment by sandycheng1** [comment]
謝謝您

**Comment by kanasimi** [comment]
@sandycheng1
請不要按fork然後編輯!
在網路上面這樣子編輯會公開帳號密碼!

您應該打開檔案總管
找尋您安裝的目錄

若是您使用安裝包，就不能夠設定帳號密碼了。

**Comment by sandycheng1** [comment]
好的,我沒試(後來有想到
所以在等待您的回覆
安裝包不是還沒有comico

**Comment by kanasimi** [comment]
安裝包不含最新的功能

**Comment by sandycheng1** [comment]
日版 中文版 皆適用嗎(我把帳密用同個

**Comment by sandycheng1** [comment]
沒事了
日版好像沒這功能
