### ISSUE TITLE
请教怎么修改所要使用的 7z.exe 的位置

### ISSUE THREAD

**Issue by mengmo** [kanasimi/work_crawler#6]
因为没有将 7-Zip 安装在这个位置`C:\Program Files\7-Zip`，但是将`7z.exe`所在的路径添加到了 PATH 中
以为应该是修改这一句的
https://github.com/kanasimi/work_crawler/blob/master/arrangement/classify_and_compress.js#L439
但是改过之后发现还是用的`C:\Program Files\7-Zip\7z.exe`

**Comment by kanasimi** [comment]
已經做了些調整, 現在應該會 search $PATH, 搜尋可執行檔案的完整路徑. 若是仍然發現有問題麻煩請重開這個 issue, 謝謝您的利用 :)

**Comment by mengmo** [comment]
不行啊，现在都不生成批处理文件了
是不是这儿的原因，看起来还是默认的安装位置
https://github.com/kanasimi/CeJS/blob/master/application/OS/Windows/archive.js#L80

**Comment by kanasimi** [comment]
其實應該是改
https://github.com/kanasimi/CeJS/blob/ed806f5f8524069b216561895fdcc080e4edf72d/application/storage/EPUB.js#L1851

很抱歉能麻煩您把生成的批次檔案貼上來看看嗎？謝謝

**Comment by mengmo** [comment]
不好意思，应该是我搞错了，没有认真检查。给您添麻烦了。
------------------------------------------------------------------
不过能解下惑吗？
因为原来都是直接在`...\work_crawler\novel.cmn-Hans-CN\网站名\小说名\小说名\`下修改并执行批处理，所以`.epub`也都是在这个位置生成
实际上`.epub`文件应该在`...\work_crawler\novel.cmn-Hans-CN\网站名\`下吧？
而且生成`.epub`文件后批处理就自动删除了吧？
还是现在不需要生成批处理而是直接调用`7z.exe`处理

**Comment by kanasimi** [comment]
您說的沒錯，.epub 文件會放在 novel.cmn-Hans-CN\网站名\ 下面。
.bat 還是會生成，但是作業完畢之後就會自動被刪除。

若是你有其他建議也可以提出來。
若是問題已經解決，麻煩請關掉這個 issue，謝謝。

**Comment by mengmo** [comment]
好的。多谢耐心解答。
