### ISSUE TITLE
請求將baozimh加入圖形介面,以及增加baozimh的id下載功能

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#600]
﻿

* **Version**: 
* **Interface**: 
* **Arguments**:

**Comment by kanasimi** [comment]
2022/11/19 已採用 Cloudflare 的阻斷服務攻擊保護。
本來準備移除這個網站,所以不會添加上這個功能.

**Comment by gfhghfghfh** [comment]
這邊是使用comic.cmn-Hant-TW下的baozimh似乎沒有 Cloudflare保護
能正常下載

**Comment by kanasimi** [comment]
這邊嘗試過，量稍微大就會鎖了，所以就算放進去，也不好當正規使用。
