### ISSUE TITLE
請求將challenge網址更名為canvas

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#606]
﻿

* **Version**: 
* **Interface**: 
* **Arguments**:

**Comment by gfhghfghfh** [comment]
a

**Comment by kanasimi** [comment]
現在使用起來有問題嗎?因為這好像不是寫死在程式裡面的...

**Comment by gfhghfghfh** [comment]
目前下載貌似不會有問題

但這邊觀察圖形介面的下載進度條的網址是challenge 

然後點擊該網址，跳轉瀏覽器查看
網址雖然不一樣（id 的部分不知道為什麽重複兩次）
但是網頁內容也是可以正常顯示

**Comment by gfhghfghfh** [comment]
目前下載貌似不會有問題

這邊是觀察圖形介面的下載進度條顯示的網址是challenge
ex:
https //www.webtoons.com/challenge/episodeList?titleNo=875471

因為這邊不確定如果以後challenge不再能自動跳轉成canvas
會不會對下載產生影響

所以才提交請求
如果不影響的話
就不麻煩您了

感謝閱讀

**Comment by kanasimi** [comment]
好的。那就有問題再說了。
