### ISSUE TITLE
是否支持付费小说章节，漫画的下载？

### ISSUE THREAD

**Issue by weishijie-detail** [kanasimi/work_crawler#607]
﻿

* **Version**: 
* **Interface**: 
* **Arguments**:

**Comment by kanasimi** [comment]
您可以試試[利用cookie ](https://github.com/kanasimi/work_crawler/blob/master/document/README.cmn-Hant-TW.md#get-cookies-from-browser-%E5%BE%9E%E7%80%8F%E8%A6%BD%E5%99%A8%E7%8D%B2%E5%8F%96-cookies)
