### ISSUE TITLE
webtoon_en id:4678 圖片參數沒有被去除

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#608]
﻿

* **Version**: 
* **Interface**: 
* **Arguments**:

**Comment by gfhghfghfh** [comment]
https //www.webtoons.com/en/romance/the-dukes-cursed-charm/list?title_no=4678
這邊使用圖形介面的版本
將MIN_LENGTH值調大
取得以下的圖片網址

**Comment by kanasimi** [comment]
用瀏覽器也會出現 `?type=q90`
這個有必要手動去除嗎?

**Comment by gfhghfghfh** [comment]
關於去除"?type=*"的部分
