### ISSUE TITLE
试着用69shu.js爬了一下epub，如何去除右上角添加的时间和字数？

### ISSUE THREAD

**Issue by sao321** [kanasimi/work_crawler#619]
* **Version**: work_crawler.updater.js最新版安装
* **Interface**: Command prompt
* **Arguments**: node 69shu.js "47012" && echo "via id"

使用以上command生成的epub在右上角会有时间和字数，并且第一行最开头的“  ”漏掉了，请问有办法修正吗？感谢

实际效果参考：https://p.inari.site/guest/24-01/06/6598e74435cdd.png

**Comment by kanasimi** [comment]
您需要採用懶人安裝法的最新版本
