### ISSUE TITLE
使用proxy设置后连接报错sslv3 alert handshake failure

### ISSUE THREAD

**Issue by karma-sun** [kanasimi/work_crawler#628]
﻿

* **Version**: 懶人安裝法
* **Interface**: 命令行
* **Arguments**: node manhuadb.js 青之驱魔师

因为manhuadb不能直连，所以使用 export HTTPS_PROXY=http://127.0.0.1:3128 命令设置了proxy，然后执行命令
node manhuadb.js 青之驱魔师
报错
Error: C077C2900D7F0000:error:0A000410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1586:SSL alert number 40

Emitted 'error' event on TLSSocket instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  library: 'SSL routines',
  reason: 'sslv3 alert handshake failure',
  code: 'ERR_SSL_SSLV3_ALERT_HANDSHAKE_FAILURE'
}

然而同时使用curl https://www.manhuadb.com/ 能正确获得网页内容
可以确认程序使用了proxy,不设置代理时是另一个报错

**Comment by kanasimi** [comment]
不太確定是不是本函式庫的問題...您採用什麼代理程式呢?
