### ISSUE TITLE
可否刪掉資料夾內的 .json 檔案

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#63]
請問慢慢資料夾內的search.json
或是像是
6009 幸亏是你.json

這種檔案刪掉應該不影響檔案漫畫圖片的檔案吧?

**Comment by kanasimi** [comment]
這些json檔是用來記錄程式執行的狀態。可以刪除，但若常常接續下載，可能會受影響。例如必須重新搜尋作品、重新檢查下載狀況等等。

**Comment by kanasimi** [comment]
若是您已無疑問
煩請關閉此議題
謝謝
