### ISSUE TITLE
Translate README.md into English

### ISSUE THREAD

**Issue by Korb** [kanasimi/work_crawler#630]
This will make it possible for not only developers who speak hieroglyphic language to participate in testing and developing the "CeJS online novels / comics downloader" application.

**Comment by kanasimi** [comment]
There is already an English translation. Are you referring to the enhancement of the English translation?

**Comment by Korb** [comment]
I apologize for the inaccuracy and misleading. I was confused by the abundance of hieroglyphs in the repository description and screenshots, which gave me the impression that the metadata and README.md are written exclusively using hieroglyphs.

I highlighted in the screenshot what I think is better left in English — [Translate README.md into English.png](https://drive.google.com/file/d/1Lfp_WdXiB0Wlphzjhli1JXdl8vQ7vxOt/view).

Also, I am sure that for most users it is more convenient to see in README.md first a block in English, and then in other languages, if you like.

English is not my native language, nor is any of the languages ​​in hieroglyphs. But English allows us to understand each other regardless of where we were born and live. Unlike other languages, including my native one. This should be kept in mind.

**Comment by kanasimi** [comment]
I understand what you mean. The tool is now mostly working on Chinese and Japanese sites, and users of the tool should be able to read Chinese or Japanese, hence this is the reason why the documentation is in its current form. Your example reminds me that there are users with different needs. Can you tell me your main goals and expectations for using this tool? Knowing this should allow me to better handle situations like yours.
