### ISSUE TITLE
您好，能否考虑增加几个漫画网站。

### ISSUE THREAD

**Issue by 1608637229** [kanasimi/work_crawler#7]
动漫之家，http://manhua.dmzj.com。
汗汗漫画，http://www.hhcool.com
57漫画，http://www.57mh.com

**Comment by kanasimi** [comment]
57漫画似乎與爱漫画相同，沒有再更新了。或許您採用其他的網站會能夠得到更新的資料。

**Comment by firstuanl** [comment]
你好，

加上这个吧
57 漫画，http://www.57mh.com

**Comment by kanasimi** [comment]
@1608637229 已加入动漫之家

**Comment by kanasimi** [comment]
若有其他的需求，請每一個網站另開一個issue，謝謝。

**Comment by kanasimi** [comment]
已增加，請重新下載測試，謝謝。您需要直接到 GitHub 下載最新版本 CeJS 壓縮檔，解開後配置。
