### ISSUE TITLE
作品目錄的 cache    是指哪裏

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#71]
由於本工具會 cache 作品資訊，更新幅度較大的時候您可能需要刪除作品目錄的 cache，重新下載作品。

請問這段話中＂作品目錄的 cache＂是指哪裏

**Comment by kanasimi** [comment]
例如 search.json, servers.json 以及作品目錄下面，以作品名稱為名的 .json 檔案。
