### ISSUE TITLE
關於程式製作

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#73]
大大您好
因為我喜歡您做的程式
我想要以後私下學習如何製作
以後想一起來更新這個程式
（當然我知道學習程式很漫長，所以這有點癡人說夢）
不過我還是想試試
請問您可以告訴我
我應該從什麼開始學習

**Comment by kanasimi** [comment]
歡迎您的加入
若是您還沒學過JavaScript的話
您可以從JavaScript教程開始學起
例如
http://docs.cocos.com/creator/manual/zh/scripting/javascript-primer.html

**Comment by gfhghfghfh** [comment]
謝謝，希望我學得來
