### ISSUE TITLE
請問如何處理

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#75]
<img width="427" alt="default" src="https://user-images.githubusercontent.com/42042168/45914944-fc215600-be7e-11e8-91e3-57834a4bdcdb.PNG">

**Comment by gfhghfghfh** [comment]
還有這會影響到檔案嗎

**Comment by gfhghfghfh** [comment]
我使用1.6

**Comment by kanasimi** [comment]
這個問題已經在
https://github.com/kanasimi/work_crawler/commit/31de9ee42349c5e8a64003a15703c6c34a91c7b5#diff-f3fa73589c9a722d80fe6ad0c18e8929R540
修復
通常再下載一次
錯誤訊息應該會消失

若是您沒有使用懶人安裝法的話
那麼可能得要等到下一版的安裝包了

**Comment by gfhghfghfh** [comment]
再下載一次是指
所有漫畫都要嗎

**Comment by gfhghfghfh** [comment]
還是在這個錯誤畫面出現時
正在下載的漫畫需要重新下載

**Comment by kanasimi** [comment]
在這個錯誤畫面出現時
正在下載的漫畫需要重新下載
