### ISSUE TITLE
另外可否支持bandizip这个解压缩软件，

### ISSUE THREAD

**Issue by 1608637229** [kanasimi/work_crawler#8]
我在这个解压缩的软件目录发现有7z的文件，因为7z是开源的，所以理论上我安装了bandizip你是不是也可以调用呢。

**Comment by kanasimi** [comment]
很抱歉，這邊在安裝完這個軟體之後，似乎沒有發現7z的執行檔。

**Comment by kanasimi** [comment]
@1608637229 若是您沒有其他意見，將關閉這個議題。
