### ISSUE TITLE
下載一半白屏

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#81]
下載一半白屏
http://www.dm5.com/manhua-wodeshaonian/
我使用懶人安裝法

**Comment by kanasimi** [comment]
這邊下載正常
能附上個錯誤訊息或者截圖嗎

**Comment by gfhghfghfh** [comment]
但就是突然白屏
我使用懶人安裝法的圖形介面

**Comment by gfhghfghfh** [comment]
我沒看到錯誤就突然白屏了

**Comment by kanasimi** [comment]
若重新下載仍然沒有變好的話
您可以嘗試用命令列的方式
應該能獲得錯誤訊息

**Comment by gfhghfghfh** [comment]
只有用圖形介面有問題

**Comment by gfhghfghfh** [comment]
每次都會
02 连载 0007 第7话 境界 （31P）

**Comment by gfhghfghfh** [comment]
然後我嘗試另一個漫畫
manhua-yingxiongxueyuandeliedengsheng 英雄学院的劣等生
則是第一卷的126頁
然後白屏

**Comment by gfhghfghfh** [comment]
<img width="960" alt="default" src="https://user-images.githubusercontent.com/42042168/45926573-d1a2cc00-bf56-11e8-90db-6a2d6739e95c.PNG">
請問怎麼看

**Comment by gfhghfghfh** [comment]
應該是window10

**Comment by gfhghfghfh** [comment]
<img width="490" alt="default" src="https://user-images.githubusercontent.com/42042168/45926585-fd25b680-bf56-11e8-9f85-fde364cab1cd.PNG">

**Comment by gfhghfghfh** [comment]
這次停在02 连载 0003 第3话 兔子 （32P）

**Comment by kanasimi** [comment]
請問您有並行下載其他的作品嗎

**Comment by gfhghfghfh** [comment]
沒有

**Comment by kanasimi** [comment]
簡單的說
看起來是這個工具取得了錯誤的網頁內容
但是這邊下載的時候沒有問題
因此就不知道內容是長什麼樣子
可能得要麻煩您提供一下您取得的內容

請更新之後再次下載看看
這次在Console應該會顯示出錯誤的內容

**Comment by gfhghfghfh** [comment]
更新的話
只要輸入node work_crawler.updater.js
就可以嗎

**Comment by kanasimi** [comment]
是的沒錯

**Comment by gfhghfghfh** [comment]
clear log | show/hidden log log
[📝]複製貼上快速鍵: Ctrl + C 複製選取的項目, Ctrl + V 貼上選取的項目
[🐛][17:45:52.102] open DevTools
[ℹ][.2] 預設的主要下載目錄: C:\Users\abc\Downloads\
[📝]自動更新檢測並執行中。
[ℹ][12.071s] import configuration of comic.cmn-Hans-CN/nokiacn: {"main_directory":"D:\\work crawler\\nokiacn\\"}
[ℹ][4.806s] import configuration of comic.cmn-Hans-CN/dm5: {"main_directory":"D:\\work crawler\\dm5\\"}
[📝]dm5: 2018-09-23T09:46:37.148Z Starting manhua-wodeshaonian, 儲存至 D:\work crawler\dm5\
[📝]manhua-wodeshaonian [高野一深] 我的少年: 26 章. 连载中
[📝]1/26 [01 番外 0001 作者访谈 （1P）] 1 images.
[📝]2/26 [01 番外 0002 作者访谈2 （5P）] 5 images.
[📝]3/26 [01 番外 0003 第1卷附录 （5P）] 5 images.
[📝]4/26 [01 番外 0004 第3卷后记 （5P）] 5 images.
[📝]5/26 [01 番外 0005 圣诞特别篇 （10P）] 10 images.
[📝]6/26 [02 连载 0001 第1话 体温计 （51P）] 51 images.
[📝]7/26 [02 连载 0002 第2话 Over Drive （32P）] 32 images.
[📝]8/26 [02 连载 0003 第3话 兔子 （32P）] 32 images.
[ℹ][59.07s] get_URL_node: timeout 30s [http://www.dm5.com//m432871/chapterfun.ashx]
[☠][199.6] Error @CeL: 0 [TypeError] (facility code 0): 
 Cannot read property 'replace' of undefined
[ℹ][211.6] get_URL_node: timeout 30s [http://www.dm5.com//m432871/chapterfun.ashx]
[☠][.3] Error @CeL: 0 [TypeError] (facility code 0): 
 Cannot read property 'replace' of undefined
[📝]9/26 [02 连载 0004 第4话 礼物 （34P）] 34 images.
[📝]10/26 [02 连载 0005 第5话 手机吊坠 （32P）] 32 images.
[📝]11/26 [02 连载 0006 第6话 喜欢的东西 （31P）] 31 images.
[ℹ][23.362s] get_URL_node: timeout 30s [http://manhua1031-104-250-150-10.cdndm5.com/30/29978/458457/2_2139.jpg?cid=458457&key=b0bb08ad7c317cb1ae09c3d28be288bb]
[☠][.2] get_URL_cache_node.cache: Error to get URL: [http://manhua1031-104-250-150-10.cdndm5.com/30/29978/458457/2_2139.jpg?cid=458457&key=b0bb08ad7c317cb1ae09c3d28be288bb].
[📝]12/26 [02 连载 0007 第7话 境界 （31P）] 31 images.
[ℹ][7.213s] get_URL_node: timeout 30s [http://www.dm5.com//m463726/chapterfun.ashx]
[☠][.2] Error @CeL: 0 [TypeError] (facility code 0): 
 Cannot read property 'replace' of undefined
[ℹ][2.245s] get_URL_node: timeout 30s [http://www.dm5.com//m463726/chapterfun.ashx]
[☠][.7] Error @CeL: 0 [TypeError] (facility code 0): 
 Cannot read property 'replace' of undefined
[📝]13/26 [02 连载 0008 第8话 水和光 （32P）] 32 images.
[📝]14/26 [02 连载 0009 第9话 谎言 （37P）] 37 images.
[ℹ][14.222s] get_URL_node: timeout 30s [http://manhua1031-104-250-151-178.cdndm5.com/30/29978/469995/6_3368.jpg?cid=469995&key=b0bb08ad7c317cb1ae09c3d28be288bb]
[☠][.2] get_URL_cache_node.cache: Error to get URL: [http://manhua1031-104-250-151-178.cdndm5.com/30/29978/469995/6_3368.jpg?cid=469995&key=b0bb08ad7c317cb1ae09c3d28be288bb].
[📝]15/26 [02 连载 0010 第10话 欲求之物 （32P）] 32 images.
[ℹ][13.167s] get_URL_node: timeout 30s [http://manhua1031-104-250-150-10.cdndm5.com/30/29978/478694/1_5218.jpg?cid=478694&key=b0bb08ad7c317cb1ae09c3d28be288bb]
[☠][.2] get_URL_cache_node.cache: Error to get URL: [http://manhua1031-104-250-150-10.cdndm5.com/30/29978/478694/1_5218.jpg?cid=478694&key=b0bb08ad7c317cb1ae09c3d28be288bb].
[ℹ][3.18s] get_URL_node: timeout 30s [http://www.dm5.com//m478694/chapterfun.ashx]
[☠][.3] Error @CeL: 0 [TypeError] (facility code 0): 
 Cannot read property 'replace' of undefined
[ℹ][4.362s] get_URL_node: timeout 30s [http://www.dm5.com//m478694/chapterfun.ashx]
[☠][1] Error @CeL: 0 [TypeError] (facility code 0): 
 Cannot read property 'replace' of undefined
[📝]16/26 [02 连载 0011 第11话 噪音 （32P）] 32 images.
[📝]17/26 [02 连载 0012 第12话 玻璃珠 （32P）] 32 images.
[📝]18/26 [02 连载 0013 第13话 终结 （35P）] 35 images.
[📝]19/26 [02 连载 0014 第14话 戏剧性 （31P）] 31 images.
[📝]20/26 [02 连载 0015 第15话 再会 （50P）] 50 images.
[ℹ][33.431s] get_URL_node: timeout 30s [http://www.dm5.com//m521721/chapterfun.ashx]
[☠][.5] Error @CeL: 0 [TypeError] (facility code 0): 
 Cannot read property 'replace' of undefined
[ℹ][637.5] get_URL_node: timeout 30s [http://www.dm5.com//m521721/chapterfun.ashx]
[☠][.2] Error @CeL: 0 [TypeError] (facility code 0): 
 Cannot read property 'replace' of undefined
[📝]21/26 [02 连载 0016 第16话 创可贴 （35P）] 35 images.
[📝]22/26 [02 连载 0017 第17话 电一 （31P）] 31 images.
[📝]23/26 [02 连载 0018 第18话 距离 （34P）] 34 images.
[ℹ][30.752s] get_URL_node: timeout 30s [http://www.dm5.com//m559540/chapterfun.ashx]
[☠][.3] Error @CeL: 0 [TypeError] (facility code 0): 
 Cannot read property 'replace' of undefined
[📝]24/26 [02 连载 0019 第19话 酸素 （52P）] 52 images.
[ℹ][10.978s] get_URL_node: timeout 30s [http://www.dm5.com//m620797/chapterfun.ashx]
[☠][.8] Error @CeL: 0 [TypeError] (facility code 0): 
 Cannot read property 'replace' of undefined
[📝]25/26 [02 连载 0020 第20话 黄色和青色 （34P）] 34 images.
[📝]26/26 [02 连载 0021 第21话 洞 （35P）] 35 images.
[📝]manhua-wodeshaonian 我的少年: 26 章 done. 2018-09-23T09:49:52.633Z 本作品下載作業結束.

**Comment by gfhghfghfh** [comment]
vm103:1065 platform: navigator engine error! [Gecko] != [WebKit](anonymous) @ VM103:1065D:\work_crawler-master\node_modules\electron\dist\resources\electron.asar\renderer\security-warnings.js:184 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security      Policy set or a policy with "unsafe-eval" enabled. This exposes users of      this app to unnecessary security risks. For more information and help, consulthttps://electronjs.org/docs/tutorial/security. This warning will not show uponce the app is packaged.warnAboutInsecureCSP @ D:\work_crawler-master\node_modules\electron\dist\resources\electron.asar\renderer\security-warnings.js:184D:\work_crawler-master\comic.cmn-Hans-CN\dm5.js:314 TypeError: Cannot read property 'replace' of undefined    at D:\work_crawler-master\comic.cmn-Hans-CN\dm5.js:311    at _onfail (eval at load_named (eval at <anonymous> (D:\work_crawler-master\CeJS-master\_for include\node.loader.js:78)), <anonymous>:1483:36)    at ClientRequest._ontimeout (eval at load_named (eval at <anonymous> (D:\work_crawler-master\CeJS-master\_for include\node.loader.js:78)), <anonymous>:1956:4)    at ClientRequest.emit (events.js:182)    at Socket.emitTimeout (_http_client.js:706)    at Object.onceWrapper (events.js:273)    at Socket.emit (events.js:182)    at Socket._onTimeout (net.js:445)    at ontimeout (timers.js:427)    at tryOnTimeout (timers.js:289)(anonymous) @ D:\work_crawler-master\comic.cmn-Hans-CN\dm5.js:314_onfail @ VM118:1483_ontimeout @ VM118:1956emit @ events.js:182emitTimeout @ _http_client.js:706onceWrapper @ events.js:273emit @ events.js:182Socket._onTimeout @ net.js:445ontimeout @ timers.js:427tryOnTimeout @ timers.js:289listOnTimeout @ timers.js:252processTimers @ timers.js:212D:\work_crawler-master\comic.cmn-Hans-CN\dm5.js:315 undefinedD:\work_crawler-master\comic.cmn-Hans-CN\dm5.js:314 TypeError: Cannot read property 'replace' of undefined    at D:\work_crawler-master\comic.cmn-Hans-CN\dm5.js:311    at _onfail (eval at load_named (eval at <anonymous> (D:\work_crawler-master\CeJS-master\_for include\node.loader.js:78)), <anonymous>:1483:36)    at ClientRequest._ontimeout (eval at load_named (eval at <anonymous> (D:\work_crawler-master\CeJS-master\_for include\node.loader.js:78)), <anonymous>:1956:4)    at ClientRequest.emit (events.js:182)    at Socket.emitTimeout (_http_client.js:706)    at Object.onceWrapper (events.js:273)    at Socket.emit (events.js:182)    at Socket._onTimeout (net.js:445)    at ontimeout (timers.js:427)    at tryOnTimeout (timers.js:289)(anonymous) @ D:\work_crawler-master\comic.cmn-Hans-CN\dm5.js:314_onfail @ VM118:1483_ontimeout @ VM118:1956emit @ events.js:182emitTimeout @ _http_client.js:706onceWrapper @ events.js:273emit @ events.js:182Socket._onTimeout @ net.js:445ontimeout @ timers.js:427tryOnTimeout @ timers.js:289listOnTimeout @ timers.js:252processTimers @ timers.js:212D:\work_crawler-master\comic.cmn-Hans-CN\dm5.js:315 undefinedD:\work_crawler-master\comic.cmn-Hans-CN\dm5.js:314 TypeError: Cannot read property 'replace' of undefined    at D:\work_crawler-master\comic.cmn-Hans-CN\dm5.js:311    at _onfail (eval at load_named (eval at <anonymous> (D:\work_crawler-master\CeJS-master\_for include\node.loader.js:78)), <anonymous>:1483:36)    at ClientRequest._ontimeout (eval at load_named (eval at <anonymous> (D:\work_crawler-master\CeJS-master\_for include\node.loader.js:78)), <anonymous>:1956:4)    at ClientRequest.emit (events.js:182)    at Socket.emitTimeout (_http_client.js:706)    at Object.onceWrapper (events.js:273)    at Socket.emit (events.js:182)    at Socket._onTimeout (net.js:445)    at ontimeout (timers.js:427)    at tryOnTimeout (timers.js:289)(anonymous) @ D:\work_crawler-master\comic.cmn-Hans-CN\dm5.js:314_onfail @ VM118:1483_ontimeout @ VM118:1956emit @ events.js:182emitTimeout @ _http_client.js:706onceWrapper @ events.js:273emit @ events.js:182Socket._onTimeout @ net.js:445ontimeout @ timers.js:427tryOnTimeout @ timers.js:289listOnTimeout @ timers.js:252processTimers @ timers.js:212D:\work_crawler-master\comic.cmn-Hans-CN\dm5.js:315 undefinedD:\work_crawler-master\comic.cmn-Hans-CN\dm5.js:314 TypeError: Cannot read property 'replace' of undefined    at D:\work_crawler-master\comic.cmn-Hans-CN\dm5.js:311    at _onfail (eval at load_named (eval at <anonymous> (D:\work_crawler-master\CeJS-master\_for include\node.loader.js:78)), <anonymous>:1483:36)    at ClientRequest._ontimeout (eval at load_named (eval at <anonymous> (D:\work_crawler-master\CeJS-master\_for include\node.loader.js:78)), <anonymous>:1956:4)    at ClientRequest.emit (events.js:182)    at Socket.emitTimeout (_http_client.js:706)    at Object.onceWrapper (events.js:273)    at Socket.emit (events.js:182)    at Socket._onTimeout (net.js:445)    at ontimeout (timers.js:427)    at tryOnTimeout (timers.js:289)(anonymous) @ D:\work_crawler-master\comic.cmn-Hans-CN\dm5.js:314_onfail @ VM118:1483_ontimeout @ VM118:1956emit @ events.js:182emitTimeout @ _http_client.js:706onceWrapper @ events.js:273emit @ events.js:182Socket._onTimeout @ net.js:445ontimeout @ timers.js:427tryOnTimeout @ timers.js:289listOnTimeout @ timers.js:252processTimers @ timers.js:212D:\work_crawler-master\comic.cmn-Hans-CN\dm5.js:315 undefinedD:\work_crawler-master\comic.cmn-Hans-CN\dm5.js:314 TypeError: Cannot read property 'replace' of undefined    at D:\work_crawler-master\comic.cmn-Hans-CN\dm5.js:311    at _onfail (eval at load_named (eval at <anonymous> (D:\work_crawler-master\CeJS-master\_for include\node.loader.js:78)), <anonymous>:1483:36)    at ClientRequest._ontimeout (eval at load_named (eval at <anonymous> (D:\work_crawler-master\CeJS-master\_for include\node.loader.js:78)), <anonymous>:1956:4)    at ClientRequest.emit (events.js:182)    at Socket.emitTimeout (_http_client.js:706)    at Object.onceWrapper (events.js:273)    at Socket.emit (events.js:182)    at Socket._onTimeout (net.js:445)    at ontimeout (timers.js:427)    at tryOnTimeout (timers.js:289)(anonymous) @ D:\work_crawler-master\comic.cmn-Hans-CN\dm5.js:314_onfail @ VM118:1483_ontimeout @ VM118:1956emit @ events.js:182emitTimeout @ _http_client.js:706onceWrapper @ events.js:273emit @ events.js:182Socket._onTimeout @ net.js:445ontimeout @ timers.js:427tryOnTimeout @ timers.js:289listOnTimeout @ timers.js:252processTimers @ timers.js:212D:\work_crawler-master\comic.cmn-Hans-CN\dm5.js:315 undefinedD:\work_crawler-master\comic.cmn-Hans-CN\dm5.js:314 TypeError: Cannot read property 'replace' of undefined    at D:\work_crawler-master\comic.cmn-Hans-CN\dm5.js:311    at _onfail (eval at load_named (eval at <anonymous> (D:\work_crawler-master\CeJS-master\_for include\node.loader.js:78)), <anonymous>:1483:36)    at ClientRequest._ontimeout (eval at load_named (eval at <anonymous> (D:\work_crawler-master\CeJS-master\_for include\node.loader.js:78)), <anonymous>:1956:4)    at ClientRequest.emit (events.js:182)    at Socket.emitTimeout (_http_client.js:706)    at Object.onceWrapper (events.js:273)    at Socket.emit (events.js:182)    at Socket._onTimeout (net.js:445)    at ontimeout (timers.js:427)    at tryOnTimeout (timers.js:289)(anonymous) @ D:\work_crawler-master\comic.cmn-Hans-CN\dm5.js:314_onfail @ VM118:1483_ontimeout @ VM118:1956emit @ events.js:182emitTimeout @ _http_client.js:706onceWrapper @ events.js:273emit @ events.js:182Socket._onTimeout @ net.js:445ontimeout @ timers.js:427tryOnTimeout @ timers.js:289listOnTimeout @ timers.js:252processTimers @ timers.js:212D:\work_crawler-master\comic.cmn-Hans-CN\dm5.js:315 undefinedD:\work_crawler-master\comic.cmn-Hans-CN\dm5.js:314 TypeError: Cannot read property 'replace' of undefined    at D:\work_crawler-master\comic.cmn-Hans-CN\dm5.js:311    at _onfail (eval at load_named (eval at <anonymous> (D:\work_crawler-master\CeJS-master\_for include\node.loader.js:78)), <anonymous>:1483:36)    at ClientRequest._ontimeout (eval at load_named (eval at <anonymous> (D:\work_crawler-master\CeJS-master\_for include\node.loader.js:78)), <anonymous>:1956:4)    at ClientRequest.emit (events.js:182)    at Socket.emitTimeout (_http_client.js:706)    at Object.onceWrapper (events.js:273)    at Socket.emit (events.js:182)    at Socket._onTimeout (net.js:445)    at ontimeout (timers.js:427)    at tryOnTimeout (timers.js:289)(anonymous) @ D:\work_crawler-master\comic.cmn-Hans-CN\dm5.js:314_onfail @ VM118:1483_ontimeout @ VM118:1956emit @ events.js:182emitTimeout @ _http_client.js:706onceWrapper @ events.js:273emit @ events.js:182Socket._onTimeout @ net.js:445ontimeout @ timers.js:427tryOnTimeout @ timers.js:289listOnTimeout @ timers.js:252processTimers @ timers.js:212D:\work_crawler-master\comic.cmn-Hans-CN\dm5.js:315 undefinedD:\work_crawler-master\comic.cmn-Hans-CN\dm5.js:314 TypeError: Cannot read property 'replace' of undefined    at D:\work_crawler-master\comic.cmn-Hans-CN\dm5.js:311    at _onfail (eval at load_named (eval at <anonymous> (D:\work_crawler-master\CeJS-master\_for include\node.loader.js:78)), <anonymous>:1483:36)    at ClientRequest._ontimeout (eval at load_named (eval at <anonymous> (D:\work_crawler-master\CeJS-master\_for include\node.loader.js:78)), <anonymous>:1956:4)    at ClientRequest.emit (events.js:182)    at Socket.emitTimeout (_http_client.js:706)    at Object.onceWrapper (events.js:273)    at Socket.emit (events.js:182)    at Socket._onTimeout (net.js:445)    at ontimeout (timers.js:427)    at tryOnTimeout (timers.js:289)(anonymous) @ D:\work_crawler-master\comic.cmn-Hans-CN\dm5.js:314_onfail @ VM118:1483_ontimeout @ VM118:1956emit @ events.js:182emitTimeout @ _http_client.js:706onceWrapper @ events.js:273emit @ events.js:182Socket._onTimeout @ net.js:445ontimeout @ timers.js:427tryOnTimeout @ timers.js:289listOnTimeout @ timers.js:252processTimers @ timers.js:212D:\work_crawler-master\comic.cmn-Hans-CN\dm5.js:315 undefinedD:\work_crawler-master\comic.cmn-Hans-CN\dm5.js:314 TypeError: Cannot read property 'replace' of undefined    at D:\work_crawler-master\comic.cmn-Hans-CN\dm5.js:311    at _onfail (eval at load_named (eval at <anonymous> (D:\work_crawler-master\CeJS-master\_for include\node.loader.js:78)), <anonymous>:1483:36)    at ClientRequest._ontimeout (eval at load_named (eval at <anonymous> (D:\work_crawler-master\CeJS-master\_for include\node.loader.js:78)), <anonymous>:1956:4)    at ClientRequest.emit (events.js:182)    at Socket.emitTimeout (_http_client.js:706)    at Object.onceWrapper (events.js:273)    at Socket.emit (events.js:182)    at Socket._onTimeout (net.js:445)    at ontimeout (timers.js:427)    at tryOnTimeout (timers.js:289)(anonymous) @ D:\work_crawler-master\comic.cmn-Hans-CN\dm5.js:314_onfail @ VM118:1483_ontimeout @ VM118:1956emit @ events.js:182emitTimeout @ _http_client.js:706onceWrapper @ events.js:273emit @ events.js:182Socket._onTimeout @ net.js:445ontimeout @ timers.js:427tryOnTimeout @ timers.js:289listOnTimeout @ timers.js:252processTimers @ timers.js:212D:\work_crawler-master\comic.cmn-Hans-CN\dm5.js:315 undefinedD:\work_crawler-master\comic.cmn-Hans-CN\dm5.js:314 TypeError: Cannot read property 'replace' of undefined    at D:\work_crawler-master\comic.cmn-Hans-CN\dm5.js:311    at _onfail (eval at load_named (eval at <anonymous> (D:\work_crawler-master\CeJS-master\_for include\node.loader.js:78)), <anonymous>:1483:36)    at ClientRequest._ontimeout (eval at load_named (eval at <anonymous> (D:\work_crawler-master\CeJS-master\_for include\node.loader.js:78)), <anonymous>:1956:4)    at ClientRequest.emit (events.js:182)    at Socket.emitTimeout (_http_client.js:706)    at Object.onceWrapper (events.js:273)    at Socket.emit (events.js:182)    at Socket._onTimeout (net.js:445)    at ontimeout (timers.js:427)    at tryOnTimeout (timers.js:289)(anonymous) @ D:\work_crawler-master\comic.cmn-Hans-CN\dm5.js:314_onfail @ VM118:1483_ontimeout @ VM118:1956emit @ events.js:182emitTimeout @ _http_client.js:706onceWrapper @ events.js:273emit @ events.js:182Socket._onTimeout @ net.js:445ontimeout @ timers.js:427tryOnTimeout @ timers.js:289listOnTimeout @ timers.js:252processTimers @ timers.js:212D:\work_crawler-master\comic.cmn-Hans-CN\dm5.js:315 undefined

**Comment by gfhghfghfh** [comment]
我試著截圖一下

**Comment by kanasimi** [comment]
請點開"open DevTools"
應該在Console有錯誤的網頁內容

**Comment by gfhghfghfh** [comment]
<img width="404" alt="1" src="https://user-images.githubusercontent.com/42042168/45926730-a53c7f00-bf59-11e8-9ebc-cfaea5105ac8.PNG">
<img width="408" alt="2" src="https://user-images.githubusercontent.com/42042168/45926731-a53c7f00-bf59-11e8-9839-61b8108fd695.PNG">
<img width="405" alt="3" src="https://user-images.githubusercontent.com/42042168/45926732-a5d51580-bf59-11e8-8860-f6fbdf55f2be.PNG">
<img width="403" alt="4" src="https://user-images.githubusercontent.com/42042168/45926733-a5d51580-bf59-11e8-8b4e-8f6224e36c5e.PNG">
<img width="409" alt="5" src="https://user-images.githubusercontent.com/42042168/45926734-a5d51580-bf59-11e8-9cbc-858dbb75dccf.PNG">

**Comment by gfhghfghfh** [comment]
請問這樣可以嗎

**Comment by kanasimi** [comment]
謝謝您

出錯的原因是沒有辦法從DM5網站獲得通行碼
不過這邊無論是圖形介面或者命令列介面都沒有遇到這樣的問題
而您那邊看起來在命令列介面也沒有出現問題
因此還得要再觀察看看到底是什麼樣的原因...

**Comment by gfhghfghfh** [comment]
似乎錯誤的地方會不同
目前的狀況是下載有缺頁

**Comment by kanasimi** [comment]
不是在同一個章節出錯的話
那麼重新下載應該能夠補回之前沒有下載到的圖片和章節

**Comment by gfhghfghfh** [comment]
謝謝
我剛剛嘗試了

**Comment by gfhghfghfh** [comment]
不過這種錯誤類型
希望您也能放入#80
因為可能被忽略掉

**Comment by gfhghfghfh** [comment]
謝謝
