### ISSUE TITLE
請問作品目錄下可否放置無關的檔案

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#85]
請問我為了快速新增最愛清單
採用http://chilimurmur.pixnet.net/blog/post/96556023-%E5%B7%A5%E4%BD%9C%E5%B0%8F%E7%A5%95%E8%A8%A3%EF%BC%9A%E8%B3%87%E6%96%99%E5%A4%BE%E5%85%A7%E6%AA%94%E5%90%8D%E5%85%A8%E8%A4%87%E8%A3%BD%EF%BC%81

<img width="587" alt="default" src="https://user-images.githubusercontent.com/42042168/45937323-707c0680-bff1-11e8-86b2-4177da154aef.PNG">

檔名.bat放置在此
應無不妥吧
不會影響到程式和檔案吧

**Comment by kanasimi** [comment]
不會影響到程式和檔案 😃
