### ISSUE TITLE
為何需要下載本工具安裝檔 work_crawler.updater.js

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#86]
下載並儲存本工具安裝檔 work_crawler.updater.js（按右鍵另存新檔）。本工具安裝檔 預設會將所有組件放在 work_crawler-master 目錄下。

請問當我下載壓縮檔時
work_crawler.updater.js
就已包含了
請問為什麼還要按右鍵另存新檔

**Comment by kanasimi** [comment]
若是您不想下載整個壓縮檔的話
光是靠執行這個檔
也會自動下載
並且更新部署更新作業

**Comment by gfhghfghfh** [comment]
請問利用<只利用work_crawler.updater.js >下載
<img width="188" alt="擷取" src="https://user-images.githubusercontent.com/42042168/63568887-ac28a300-c5a9-11e9-83f9-f592563f7492.PNG">

除了資料夾以外的檔案可以刪除嗎
因為<利用壓縮包下載搭配work_crawler.updater.js >下載時
並不會出現資料夾外

**Comment by gfhghfghfh** [comment]
因為資料夾裡GitHub.updater.node.js
和資料夾外的GitHub.updater.node.js
好像不是完全一樣
所以想問問

**Comment by gfhghfghfh** [comment]
@kanasimi 
請問利用<只利用work_crawler.updater.js >下載
<img width="188" alt="擷取" src="https://user-images.githubusercontent.com/42042168/63568887-ac28a300-c5a9-11e9-83f9-f592563f7492.PNG">

會出現資料夾外的檔案

我利用壓縮包搭配work_crawler.updater.js下載
不會出現資料夾外的檔案

這不影響程式運行嗎

**Comment by kanasimi** [comment]
執行完畢後，除了 `work_crawler-master` 這個目錄，還會出現一些附屬檔案。這些檔案是幫助更新用的，就算刪除也不會影響程式運行。

**Comment by gfhghfghfh** [comment]
所以我<利用壓縮包搭配work_crawler.updater.js>下載
沒有"一些附屬檔案"在資料夾外
也不影響影更新,程式運行嗎

**Comment by kanasimi** [comment]
yes
