### ISSUE TITLE
下載問題: The file type [undefined] is not image types accepted

### ISSUE THREAD

**Issue by haowenjhang** [kanasimi/work_crawler#88]
版本為[ 10.0.17134.320 ]
使用懶人安裝法/命令提示字元介面

下載時出現了 The file type [undefined] is not image types accepted
下載完成後JPG圖檔無法開啟，請問該如何解決

![default](https://user-images.githubusercontent.com/30752142/46392183-0232f480-c713-11e8-829b-a11ae57c2b11.png)

**Comment by kanasimi** [comment]
這邊測試的時候正常
不曉得是不是網站防止下載的機制

麻煩請等待一段時間再下載看看
並且回覆一下 下載的狀況
謝謝

**Comment by haowenjhang** [comment]
經測試後已可正常下載，謝謝
