### ISSUE TITLE
有妖氣 非鎖住章節被顯示為鎖住章節 還有仍舊下載到模糊圖片

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#90]
http://www.u17.com/comic/70568.html

非鎖住章節被顯示為鎖住章節

<img width="613" alt="default" src="https://user-images.githubusercontent.com/42042168/46577814-010b0b80-ca22-11e8-983b-4600c9cfb1df.PNG">

雖然有顯示下列圖片
<img width="943" alt="default" src="https://user-images.githubusercontent.com/42042168/46577825-44fe1080-ca22-11e8-9b49-6ee602745589.PNG">

仍舊下載到模糊圖片

**Comment by kanasimi** [comment]
被mask的圖片還是會下載儲存
但會被標記為有問題的圖片
因此之後下載時仍然會重新檢查是否有完整的圖片
