### ISSUE TITLE
如果改動大時，若不刪除會如何

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#95]
由於本工具會 cache 作品資訊，更新幅度較大的時候您可能需要刪除下載目錄中所有的 cache，重新下載作品。例如 search.json, servers.json 以及作品目錄下面，以作品名稱為名的 .json 檔

如果改動大時，若不刪除會如何

**Comment by kanasimi** [comment]
更新幅度較大的時候，新程式可能無法讀取這些舊格式的 cache，會產生錯誤
