### ISSUE TITLE
圖質問題

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#96]
我想問一下，有些程式會有什麼image quality 的設定，雖然我不是很懂，但應該跟畫質有關吧。我想請問大大的程式所下載圖，應該都是取最好的吧

**Comment by gfhghfghfh** [comment]
因為我偏好最好的圖質，所以想問問

**Comment by kanasimi** [comment]
本工具會盡量取得原有的圖片檔案中最高品質的

**Comment by gfhghfghfh** [comment]
謝謝您
