### ISSUE TITLE
CeJS問題

### ISSUE THREAD

**Issue by Ecauchy** [kanasimi/work_crawler#98]
﻿

* **Version**: 懶人安裝法，最後一步手動解壓
* **Interface**: 命令行界面

壓縮包裡並無CeJS檔案，導致無法使用。
![image](https://user-images.githubusercontent.com/7821408/46868068-b4786380-ce59-11e8-828f-79b7f114e3bd.png)

Edit: 我有安裝7zip64[最新版](https://www.7-zip.org/a/7z1805-x64.exe/)，但是仍然報錯講我未安裝。
![image](https://user-images.githubusercontent.com/7821408/46868422-dfaf8280-ce5a-11e8-8a22-59f9066ef1e8.png)

**Comment by kanasimi** [comment]
謝謝您回報問題
請問您能否確認7zip的執行檔路徑呢
例如
"C:\\Program Files\\7-Zip\\7z.exe"

**Comment by Ecauchy** [comment]
> 
> 
> 謝謝您回報問題
> 請問您能否確認7zip的執行檔路徑呢
> 例如
> "C:\Program Files\7-Zip\7z.exe"

"F:\Program Files\7-Zip\7z.exe"
