### ISSUE TITLE
讓json都以記事本方式顯示

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#99]
請問我不小心讓json都以記事本方式顯示
請問不會影響到檔案吧
<img width="507" alt="default" src="https://user-images.githubusercontent.com/42042168/46901339-2e552f00-cee4-11e8-88fc-0783244ff119.PNG">

**Comment by kanasimi** [comment]
不會影響到本工具的操作與使用
至於日常的操作
就您的狀況來說
應該也不會有太大的問題
